### PR TITLE
FirebaseInstanceID integration tests

### PR DESCRIPTION
**Pull request by maksymmalyhin**

### CODE REVIEW

**Comment by maksymmalyhin** [comment]
NOTE: currently the tests are failing because of most likely a server issue. It supposed to be fixed before the PR merge.

**Comment by maksymmalyhin** [comment]
I temporary disable a failing test so the PR can be submitted earlier to leverage the rest of the tests for testing other PRs.

**Comment by maksymmalyhin** [comment]
@paulb777 see the [PR](https://travis-ci.org/firebase/firebase-ios-sdk/builds/632013629?utm_medium=notification&utm_source=github_status) demonstrating the integration tests disabled for forks.

**Comment by paulb777** [comment]
The referenced PR link has failing Installations tests?

**Comment by maksymmalyhin** [comment]
@paulb777 Right, the PR doesn't have Installations changes now. Are you fine with a separate PR since it's been like this for a while?

**Pull request merged**
