### PR TITLE
FirebaseAnalytics 7.11.1 release.

### PR DESCRIPTION
**Pull request by ryanwilson**
This includes the same artifact as 7.11.0 but put into the proper .zip format (with zip on the command line instead of Finder's compress menu option).

#no-changelog

### CODE REVIEW

**Review by maksymmalyhin — APPROVED** [review]
LGTM on CI green

**Review by paulb777 — APPROVED** [review]

**Comment by ryanwilson** [comment]
I was able to test this via Xcode, depending on the `rw-7.11.1-patch` branch and successfully imported Firebase and compiled Analytics calls.

**Comment by ryanwilson** [comment]
This will resolve #7962 after this lands and is tagged.

**Comment by ryanwilson** [comment]
Cancelled the test_coverage for Firestore since it should be unaffected.

**Pull request merged**
