### PR TITLE
Bump App Check version to 8.5.0-beta

### PR DESCRIPTION
**Pull request by maksymmalyhin**
Should fix https://github.com/firebase/firebase-ios-sdk/runs/3083903668?check_suite_focus=true

Test run: https://github.com/firebase/firebase-ios-sdk/actions/runs/1037955080

### CODE REVIEW

**Comment by paulb777** [comment]
Isn't the prerleease script supposed to manage the versions? @granluo

**Comment by maksymmalyhin** [comment]
> Isn't the prerleease script supposed to manage the versions? @granluo

It doesn't look like we bump the version for prerelease testing (see [here](https://github.com/firebase/firebase-ios-sdk/blob/41b00739990d098c48fa4fc63dbf764af434c34e/scripts/release_testing_setup.sh#L37)) which, I think, we should do.

**Comment by paulb777** [comment]
I'm going to merge this as a workaround to get the prerelease nightly working. We should still get the prerelease scripting fixed to manage the version correctly.

**Review by paulb777 — APPROVED** [review]

**Comment by granluo** [comment]
> Isn't the prerleease script supposed to manage the versions? @granluo

Yes, the prerelease will manage the versions but for `beta` version will be excluded. Should we include `beta` version?

**Comment by maksymmalyhin** [comment]
> Yes, the prerelease will manage the versions but for `beta` version will be excluded. Should we include `beta` version?

@granluo  Yes, we need update update all tags including `beta` for prerelease testing.

**Pull request merged**
