### PR TITLE
Remove ProviderID for Microsoft and Yahoo

### PR DESCRIPTION
**Pull request by Yue-Wang-Google**

### CODE REVIEW

**Comment by Yue-Wang-Google** [comment]
we never document this api in the doc, so it's not public. none of the user use this api because the related feature is not announced yet anywhere. So we can safely remove. @ryanwilson

**Comment by Yue-Wang-Google** [comment]
As an alternative, we can just modify the const string and change "hotmail.com" to "microsoft.com". This does not make any api changes.

**Comment by ryanwilson** [comment]
These APIs are part of our reference docs:
[FIRMicrosoftAuthProviderID](https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Constants#/c:@FIRMicrosoftAuthProviderID), [FIRYahooAuthProviderID](https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Constants#/c:@FIRYahooAuthProviderID)

Regardless if they're mentioned elsewhere, they're still part of the public API and developers could have started using them. Even if nobody is using them, it would break semantic versioning.

Changing the const string is also a breaking change since it's a change in behaviour which is probably worse than just removing the API - developers would have to find out at runtime (if discovered at all) instead of compile time.

**Comment by Yue-Wang-Google** [comment]
OK. Then we'll just change the sample code for now. 
We will file a document to go through the api review and  mark it as deprecated.

**Pull request closed without merging**
