### PR TITLE
[auth-swift] Merge main

### PR DESCRIPTION
**Pull request by paulb777**
#no-changelog

### CODE REVIEW

**Comment by ncooke3** [comment]
Is this just a result of:
```
git fetch origin
git checkout auth-swift
git pull
git checkout -b  pb-merge-main-529
git merge main
# resolve conflicts and commit
```
?

**Comment by paulb777** [comment]
Yes.

**Comment by ncooke3** [comment]
The SPM failures will be fixed by #13016. I don't quite understand the [`cocoapods-integration / tests (pull_request)` ](https://github.com/firebase/firebase-ios-sdk/actions/runs/9293778108/job/25577664516?pr=13034) failure.

**Comment by paulb777** [comment]
I'll disregard the failures that will be fixed by #13016.

https://github.com/firebase/firebase-ios-sdk/pull/13034/commits/a5c67218b5860d4ae3c316c64f76b1e5e76dcb43 should fix the CocoaPods integration tests

**Pull request merged**
