### PR TITLE
Revert "Revert "Migrate from using IID SDK for Remote Config to the new FIS SDK""

### PR DESCRIPTION
**Pull request by maksymmalyhin**
Reverts firebase/firebase-ios-sdk#5159

Server side support is expected to be rolled out by the end of the week (b/152426175).

### CODE REVIEW

**Comment by paulb777** [comment]
Isn't the end of the week too late to test for M69?

**Comment by dmandar** [comment]
Per Erik, testing can be done immediately with a project WL.

**Comment by maksymmalyhin** [comment]
Discussed offline, decided to postpone until M70 to be on the safe side.

**Comment by maksymmalyhin** [comment]
release-6.23.0 branch was cut. Merging the PR.

**Pull request merged**
