### PR TITLE
MacOS auth issue fix.

### LINKED ISSUE #7049: Integrating PhoneAuth with Firebase for Mac Catalyst
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 6.9.2
  * Installation method: CocoaPods
  * Firebase Component: Auth

### [REQUIRED] Step 2: Describe the problem

With Mac Catalyst when the `PhoneAuthProvider.provider().verifyPhoneNumber(:, uiDelegate:, completion:)` calls the Safari on Mac opens and the user receives following error:

> FIRAuthErrorDomain Code=17058 "The interaction was cancelled by the user." UserInfo={NSLocalizedDescription=The interaction was cancelled by the user., FIRAuthErrorUserInfoNameKey=ERROR_WEB_CONTEXT_CANCELLED}

#### Steps to reproduce:

1. Run any app with phone auth on Mac OS.
2. Call `PhoneAuthProvider.provider().verifyPhoneNumber(:, uiDelegate:, completion:)` method with valid phone number

#### Relevant Code:

```
PhoneAuthProvider.provider().verifyPhoneNumber(validPhoneNumber, uiDelegate: nil) { ( _, error) in
                    if let error = error {
                        // User receives an error
                        assertionFailure(error.localizedDescription)
                    }
                    ...
                }
```

### PR DESCRIPTION
**Pull request by gevorgyanvahagn**
When trying to open SFSafariViewController the default browser opens and the safariViewControllerDidFinish(_ controller: SFSafariViewController) on MacOS
Fixes #7049.

### CODE REVIEW

**Comment by paulb777** [comment]
Thanks for the PR!

See other usages of `TARGET_OS_MACCATALYST` in the repo for more typical usages of the Catalyst check and to fix the CI failure.

**Comment by gevorgyanvahagn** [comment]
Thanks for your comment @paulb777!

I've found few usages of `TARGET_OS_MACCATALYST` in the project similar to the following

```
#if TARGET_OS_MACCATALYST
  // some code here
#elif
  // some code here
#endif
```

is this what you mean?

**Comment by paulb777** [comment]
Yes

**Comment by gevorgyanvahagn** [comment]
@googlebot I fixed it.

**Comment by vahagngevorgyanpicsart** [comment]
@googlebot I consent.

**Comment by paulb777** [comment]
Thanks @gevorgyanvahagn ! The change looks good to me and safe since it only changes code for the Catalyst community-supported distribution.

Assigning to the FirebaseAuth team for review and merge.

**Review by rosalyntan — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
