### PR TITLE
Lock reads and writes to session map

### LINKED ISSUE #1964: GULNetworkURLSession crashes
### Environment

  * Xcode version: 10.0 (10A255)
  * Firebase SDK version: 5.10.0
  * Firebase Component: Utilities (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 5.3.2

### Problem

App crashes in `GULNetworkURLSession`, line 162. Code:
```
// Save the session into memory.
NSMapTable *sessionIdentifierToFetcherMap = [[self class] sessionIDToFetcherMap];
[sessionIdentifierToFetcherMap setObject:self forKey:_sessionID];
```
Log output:
```
malloc: *** error for object 0x6000014bc080: pointer being freed was not allocated
malloc: *** set a breakpoint in malloc_error_break to debug
```

#### Steps to reproduce:

Crash occurs on startup but not every time. It happens very often when running unit tests.
We have 26k crashes affecting 18k users.
It was introduced in version using Firebase v5.8.0 and GoogleUtilities v5.2.0. Preceding version used Firebase v4.13.0 (no GoogleUtilities) and everything worked well.

Crash log:
```
#14. Crashed: com.apple.root.background-qos
0  libsystem_kernel.dylib         0x20686d104 __pthread_kill + 8
1  libsystem_pthread.dylib        0x2068eca00 pthread_kill$VARIANT$armv81 + 296
2  libsystem_c.dylib              0x2067c4d78 abort + 140
3  libsystem_malloc.dylib         0x2068c1768 _malloc_put + 570
4  libsystem_malloc.dylib         0x2068c1924 malloc_report + 64
5  libsystem_malloc.dylib         0x2068b42d0 free + 376
6  Foundation                     0x20765f2d8 -[NSConcreteMapTable grow] + 740
7  Foundation                     0x207651000 -[NSConcreteMapTable setObject:forKey:] + 168
8  GoogleUtilities                0x1057ed3c4 -[GULNetworkURLSession sessionIDFromAsyncPOSTRequest:completionHandler:] (GULNetworkURLSession.m:160)
9  GoogleUtilities                0x1057eb454 -[GULNetwork postURL:payload:queue:usingBackgroundSession:completionHandler:] (GULNetwork.m:143)
10 SofascoreCommon                0x106141488 -[FIRClearcutLogger sendNextPendingRequestWithCompletionHandler:] + 16248
11 SofascoreCommon                0x1061416f0 __65-[FIRClearcutLogger sendNextPendingRequestWithCompletionHandler:]_block_invoke + 16864
12 libdispatch.dylib              0x20670f6c8 _dispatch_call_block_and_release + 24
13 libdispatch.dylib              0x206710484 _dispatch_client_callout + 16
14 libdispatch.dylib              0x2066f2c24 _dispatch_root_queue_drain + 640
15 libdispatch.dylib              0x2066f335c _dispatch_worker_thread2 + 116
16 libsystem_pthread.dylib        0x2068f2190 _pthread_wqthread + 472
17 libsystem_pthread.dylib        0x2068f4d00 start_wqthread + 4
```

### PR DESCRIPTION
**Pull request by morganchen12**
Potentially fix #1964.

TAP runs over at cr/217930814.

### CODE REVIEW

**Comment by morganchen12** [comment]
I wanted an explicit object to lock/unlock on rather than an implicit lock associated with a class instance or something. This isn't a hugely important decision, and I can rewrite to use `@synchronized` if preferable.

**Comment by morganchen12** [comment]
Build is broken, do not merge

**Comment by ryanwilson** [comment]
I think this may be causing a deadlock based on [Travis](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/443894515#L2854). Please try to catch this locally if you can to make sure we aren't causing a deadlock anywhere. 

Using `NSLock` is good with me, or I started an implementation with GCD if locking is causing issues (I'd prefer to avoid `@synchronized`).

**Comment by morganchen12** [comment]
Fixed deadlock and passed travis.

**Pull request merged**
