### PR TITLE
[WIP] Firestore tvOS support

### PR DESCRIPTION
**Pull request by ay8s**
As discussed in #10 this enables Firestore to work on tvOS. It requires the latest dev versions of gRPC-C++ & gRPC-Core which is why I've marked it as WIP. 

I've been able to successfully use Firestore on tvOS by pointing both gRPC-C++ & gRPC-Core pods to the grpc repo. We can reintroduce the version within the podspec once those versions are released.

I haven't looked at what is required for the FirestoreSwift pod yet.

### CODE REVIEW

**Comment by ay8s** [comment]
I signed it!

**Comment by wilhuff** [comment]
Cool!

Unfortunately, we can't take the abseil change because that's a vendored library and patching it locally makes it harder to upgrade. However, #2597 is alternative that just avoids adding those problematic parts to the Firestore framework altogether. We weren't using them.

We also can't allow our dependency on gRPC-C++ to float. One of the reasons why that pod hasn't been made a formal part of the gRPC release process is that the regular gRPC C++ API tests don't yet work completely or iOS. We (the Firestore team) carefully vet any upgrades we take to that package while we're waiting for that to land.

Is there a specific thing we need from the development version to make this work? If we can point to specific fixes we need we can get that pod respun.

**Comment by ay8s** [comment]
👍 on the abseil change. 

Marked this as WIP due to the requirement of the latest gRPC-C++. 

I think they only recently added support for tvOS, looking again it looks like gRPC-C++ 0.0.8 includes the tvOS support also if pointing to that is a possibility https://github.com/grpc/grpc/blob/v1.19.1/gRPC-C%2B%2B.podspec

**Comment by wilhuff** [comment]
That's a possibility, for sure :-). I've submitted the abseil exclusion PR. If you update your branch I'll run the integration tests to verify that we're not broken.

**Comment by wilhuff** [comment]
gRPC 0.0.8 was released today.

I have an experimental branch containing that and a tvos deployment target in #2648. Could you try it out by adding this to your `Podfile`?

```
pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'pull/2648/head'
pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'pull/2648/head'
```

**Comment by wilhuff** [comment]
Closing this in favor of #2648.

**Comment by ay8s** [comment]
Sorry I missed this @wilhuff. Will give it a go 👍

**Pull request closed without merging**
