### PR TITLE
Firestore Travis: ensure CTest outputs the log on failure.

### PR DESCRIPTION
**Pull request by var-const**
In CMake build of Firestore, configure CTest so that upon failure, it
prints out the full log of the failing test(s).

### CODE REVIEW

**Comment by var-const** [comment]
[Example](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/366669999) of the printout.

**Comment by wilhuff** [comment]
What happened to xcpretty in the output of the build of FirebaseCore?

**Comment by var-const** [comment]
@wilhuff Can you please give a link?

**Comment by var-const** [comment]
@wilhuff After your comment in the other PR, I probably get what you mean. The links are to a different wip PR where I removed xcpretty, among other things. That would explain what you're seeing (sorry, I didn't pay attention to intermediate build steps).

**Pull request merged**
