### PR TITLE
 `pod lib lint GoogleUtilities.podspec` warnings fixes

### LINKED ISSUE #2743: pod lib lint warnings introduced in cron tests
The `pod lib lint GoogleUtilities.podspec --use-libraries` cron tests have new failures from new iOS 7+ APIs.  See https://travis-ci.org/firebase/firebase-ios-sdk/jobs/516474925

```
    - WARN  | [GoogleUtilities/AppDelegateSwizzler] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m:806:44: warning: 'UIBackgroundFetchResult' is only available on iOS 7.0 or newer [-Wunguarded-availability]
    - WARN  | [GoogleUtilities/AppDelegateSwizzler] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m:818:50: warning: 'application:didReceiveRemoteNotification:fetchCompletionHandler:' is only available on iOS 7.0 or newer [-Wunguarded-availability]
```

Please fix, test, retag, and copybara.

### PR DESCRIPTION
**Pull request by maksymmalyhin**
Fixes #2743

### CODE REVIEW

**Comment by paulb777** [comment]
More specifically 

```
// The #else is for pre Xcode 9 where @available is not yet implemented.
#if __has_builtin(__builtin_available)
  if (@available(iOS 7.0, *)) {
#else
  if ([[UIDevice currentDevice].systemVersion integerValue] >= 7) {
#endif
```

See https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m#L190.

I'm not sure if a pragma to disable the warning would be needed or not.

**Comment by maksymmalyhin** [comment]
@paulb777 I am not sure the runtime check is needed here. If an app is built with iOS SDK 6.0, the method will be never called even if the app is run on a newer iOS. Am I missing anything?

**Comment by paulb777** [comment]
Isn't the warning about APIs that don't exist on iOS 6? It doesn't matter what SDK GoogleUtiliities is built with.

**Comment by maksymmalyhin** [comment]
@paulb777 You are right, runtime check is needed here as well. Thanks!

**Comment by maksymmalyhin** [comment]
Sorry, just realized, the compile time one also have to be updated. I’ll update it soon.

**Comment by maksymmalyhin** [comment]
I hope we will drop support of Xcode 8/iOS 6 soon, so we can cleanup all these checks a bit :)

**Pull request merged**
