### PR TITLE
Merge master into googledatatransport

### PR DESCRIPTION
**Pull request by mikehaney24**

### CODE REVIEW

**Comment by paulb777** [comment]
Please investigate the travis failure. I'm not sure why Firestore would check differently on this branch than master.

**Comment by paulb777** [comment]
Seems to be gone in #2829

**Comment by mikehaney24** [comment]
> Seems to be gone in #2829

I still see it in #2829

**Comment by paulb777** [comment]
It's on the googledatatransport branch travis run but not the PR travis run.

**Pull request merged**
