### PR TITLE
Fix email-link-auth (issue #974)

### LINKED ISSUE #974: Bug in FirAuth.m breaks email-auth-link 100% of the time
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2 latest
  * Firebase SDK version: 4.11.0 latest
  * Firebase Component: AUTH
  * Component version: latest

### [REQUIRED] Step 3: Describe the problem

There is a bug in `FirAuth.m` -> `isSignInWithEmailLink`: on line 1154:
`  NSDictionary<NSString *, NSString *> *queryItems = FIRAuthParseURL(urlComponents.query);
`

... you see that **.query** is passed in, ie just the part of the URL after the '?'

In `FIRAuthParseURL` (lines 1170 and 1171 shown below):
```
static NSDictionary<NSString *, NSString *> *FIRAuthParseURL(NSString *urlString) {
NSString *linkURL = [NSURLComponents componentsWithString:urlString].query;
```

... the linkURL is attempting to load **.query** also. This is always going to be nil, because it was the query that was passed into this function. Either the .query should not be passed in, or .query should not be accessed in `FIRAuthParseURL`

**The impact of this is that email-link-auth is broken** all the time, (probably?) for everyone.
Maybe there are tests missing in this area?
I love the Firebase team -- you are awesome, the project is awesome, keep up the great work.

### PR DESCRIPTION
**Pull request by xaphod**
Fixes #974 
I don't expect anyone to actually accept this into release-4.11.0, but I don't know where this PR should actually go to.
I tested this to the following extent: after making this change, I can use isSigninLink: and get the expected results, and I can also sign in with the link. Both were broken before.

### CODE REVIEW

**Comment by xaphod** [comment]
... signed the CLA

**Comment by paulb777** [comment]
Thanks for the PR @xaphod!! Our standard development process is to send bugfix PR's to master.  I retargeted the PR. 

We also should have a TravisCi run which should automatically kick off on a commit to a branch with a PR targeted to master. Would you send another commit to trigger Travis?

I'll ask someone from the FirebaseAuth team to do a review.

**Comment by paulb777** [comment]
Nevermind I kicked off travis by closing and reopening the PR.

**Comment by xaphod** [comment]
Thanks for letting me know @paulb777 - I'll target master next time.

**Comment by paulb777** [comment]
The [travis log](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/358211682) is showing this failure:

```
FIRAuthTests
  testIsSignInWithEmailLink, (([[FIRAuth auth] isSignInWithEmailLink:kFakeEmailSignInlink]) is true) failed
  ```
  **/Users/travis/build/firebase/firebase-ios-sdk/Example/Auth/Tests/FIRAuthTests.m:1791**
  ```
- (void)testIsSignInWithEmailLink {
  XCTAssertTrue([[FIRAuth auth] isSignInWithEmailLink:kFakeEmailSignInlink]);
  XCTAssertFalse([[FIRAuth auth] isSignInWithEmailLink:kBadSignInEmailLink]);

	 Executed 311 tests, with 1 failure (0 unexpected) in 13.878 (14.155) seconds 
```

**Comment by xaphod** [comment]
The test is using a link that looks nothing like what my real app receives when it generates the link.

```
static NSString *const kFakeEmailSignInlink = @"https://fex9s.app.goo.gl?link="
"https://fb-sa-upgraded.firebaseapp.com/_?mode%3DsignIn%26oobCode%3Dtestoobcode";
```

This looks nothing like the link I receive when I follow the guides. Here's a link I get:
`https://<redacted>.firebaseapp.com/__/auth/action?apiKey=<redacted>&mode=signIn&oobCode=123459g71QBFRozWp4fvi-izDstx9BE2o3zhPc_jZQAAAFiU_tqpg&continueUrl=https://<redacted>/applinks/firebaseprovider/signin`

Perhaps the way these links are generated changed, so the test & code are now out of date and broken.
In any case, this is beyond me - someone from the Firebase Auth team needs to take a look and figure out what the right thing to do is. All I can say is that if you make a test project with 4.11.0, and try to use the email-link-auth feature, I do not believe it will work. (I have only tried integrating it into my existing project)

**Comment by xaphod** [comment]
Thanks @protocol86 that makes perfect sense, I appreciate the detailed response.
One thing that would really help is updating the snippet of code in [the guide](https://firebase.google.com/docs/auth/ios/email-link-auth) in the section entitled "**Verify link and sign in**" to include where the link comes from. For example, show that code inside the openURL/continueActivity methods. That would have made it clear to me to not handle the dynamic link myself.
Keep up the great work, thank you for Firebase.

**Pull request closed without merging**
