### PR TITLE
Rename iOS-specific targets with iOS-specific names

### PR DESCRIPTION
**Pull request by wilhuff**
This brings the Firestore sub-repo in line with the Firebase sub-repo for target naming.

### CODE REVIEW

**Comment by wilhuff** [comment]
This change looks huge, but `pod update` output is interspersed. Taken a commit at a time it makes more sense.

**Comment by paulb777** [comment]
Good to go on green

**Comment by paulb777** [comment]
Looks like a simulator restart caused the test fail - restarted

**Comment by paulb777** [comment]
OK with me to merge anyway - or wait for #1156

**Pull request merged**
