### PR TITLE
Move reachability flags initialization to +initialize from +load

### LINKED ISSUE #5463: Watchdog Transgression crash (0x8badf00d)
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.13.0 and 6.14.0 tried both (unity SDK version, see Podfile.lock below)
  * Firebase Component: (Analytics, InstanceId, Messaging, Crashlytics, RemoteConfig)
  * Component version: Whatever .unitypackage brings
  * Installation method: `CocoaPods (importing .unitypackage)`
  * Unity Version: 2019.3.9f1

#### Steps to reproduce:

When updating the app from a previous version, app does not start and gets killed by watchdog after some time. Subsequent launches are fine. Only the first launch after an update crashes. Also installing from scratch does not have any issue. I'm only posting this here because I see **GDTCORReachability** on the crash log. 

We dont have background entitlements.

Also doesnt appear on Crashlytics.

The UnityFramework addresses are symbolicated by me using:
` atos -arch arm64 -o UnityFramework.framework.dSYM/Contents/Resources/DWARF/UnityFramework -l 0x105000000 0x000000010522fee4`

etc.

Please tell me if I'm symbolicating these incorrectly.

Other addesses are symbolicated by Xcode (by dragging the crash file to Xcode)

Stack trace:

```
Date/Time:           2020-04-26 14:49:19.6359 +0300
Launch Time:         2020-04-26 14:48:59.4194 +0300
OS Version:          iPhone OS 13.4 (17E255)
Release Type:        User
Baseband Version:    2.05.13
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, process-launch watchdog transgression: application<com.redacted>:90943 exhausted real (wall clock) time allowance of 20.00 seconds | ProcessVisibility: Unknown | ProcessState: Running | WatchdogEvent: process-launch | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 15.590 (user 15.590, system 0.000), 13% CPU", | "Elapsed application CPU time (seconds): 0.130, 0% CPU" | )
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001a744f7e4 __ulock_wait + 8
1   libdispatch.dylib             	0x00000001a7308cd8 _dlock_wait + 56
2   libdispatch.dylib             	0x00000001a7308c10 _dispatch_once_wait + 124
3   UnityFramework                	0x000000010522ff2c 0x105000000 + 2293548 +[GDTCORReachability sharedInstance] (in UnityFramework) (GDTCORReachability.m:53)
4   UnityFramework                	0x000000010522fee4 0x105000000 + 2293476 +[GDTCORReachability load] (in UnityFramework) (GDTCORReachability.m:0)
5   libobjc.A.dylib               	0x00000001a7385be0 load_images + 952
6   libdyld.dylib                 	0x00000001a746843c invocation function for block in dyld3::AllImages::runInitialzersBottomUp+ 66620 (dyld3::closure::Image const*) + 224
7   libdyld.dylib                 	0x00000001a745aba8 dyld3::closure::Image::forEachImageToInitBefore(void + 11176 (unsigned int, bool&) block_pointer) const + 104
8   libdyld.dylib                 	0x00000001a7468e20 dyld3::AllImages::loadImage+ 69152 (Diagnostics&, unsigned int, dyld3::closure::DlopenClosure const*, bool, bool, bool, bool) + 652
9   libdyld.dylib                 	0x00000001a74689ec dyld3::AllImages::dlopen+ 68076 (Diagnostics&, char const*, bool, bool, bool, bool, bool, void const*) + 868
10  libdyld.dylib                 	0x00000001a746a434 dyld3::dlopen_internal+ 74804 (char const*, int, void*) + 364
11  libdyld.dylib                 	0x00000001a745d6c0 dlopen + 116
12  CoreFoundation                	0x00000001a766f7e8 _CFBundleDlfcnLoadFramework + 140
13  CoreFoundation                	0x00000001a7591ee8 _CFBundleLoadExecutableAndReturnError + 432
14  Foundation                    	0x00000001a79627a8 -[NSBundle loadAndReturnError:] + 316
15  redacted                       	0x0000000102bcfd54 0x102bc8000 + 32084
16  redacted                       	0x0000000102bcfdfc 0x102bc8000 + 32252
17  libdyld.dylib                 	0x00000001a74591ec start + 4

Thread 1 name:  Dispatch queue: com.google.GDTCORUploadCoordinator
Thread 1:
0   libsystem_kernel.dylib        	0x00000001a744ec10 __psynch_mutexwait + 8
1   libsystem_pthread.dylib       	0x00000001a7372808 _pthread_mutex_firstfit_lock_wait + 92
2   libsystem_pthread.dylib       	0x00000001a7372778 _pthread_mutex_firstfit_lock_slow + 260
3   libdyld.dylib                 	0x00000001a746a314 dyld3::dlopen_internal+ 74516 (char const*, int, void*) + 76
4   libdyld.dylib                 	0x00000001a745d6c0 dlopen + 116
5   libnetwork.dylib              	0x00000001a9d038d4 __nw_protocol_get_tcp_image_block_invoke + 60
6   libdispatch.dylib             	0x00000001a730833c _dispatch_client_callout + 20
7   libdispatch.dylib             	0x00000001a7309a68 _dispatch_once_callout + 32
8   libnetwork.dylib              	0x00000001a9c91680 nw_path_network_is_satisfied_update_reason + 2944
9   libnetwork.dylib              	0x00000001a9c92a68 nw_path_get_interface_index + 76
10  libnetwork.dylib              	0x00000001a9c92608 __nw_path_snapshot_fallback_block_invoke + 136
11  libxpc.dylib                  	0x00000001a726291c _xpc_dictionary_apply_apply + 68
12  libxpc.dylib                  	0x00000001a7261914 _xpc_dictionary_apply_node_f + 156
13  libxpc.dylib                  	0x00000001a72628b8 xpc_dictionary_apply + 148
14  libnetwork.dylib              	0x00000001a9c8ffec nw_path_snapshot_fallback + 424
15  libnetwork.dylib              	0x00000001a9c8f5e0 nw_path_snapshot_path + 764
16  libnetwork.dylib              	0x00000001a9c8ed24 nw_path_evaluator_evaluate + 2524
17  libnetwork.dylib              	0x00000001a9c8e050 nw_path_create_evaluator_for_endpoint + 784
18  SystemConfiguration           	0x00000001a78d85c0 __SCNetworkReachabilitySetDispatchQueue + 508
19  SystemConfiguration           	0x00000001a78d8950 SCNetworkReachabilitySetDispatchQueue + 132
20  UnityFramework                	0x000000010523014c 0x105000000 + 2294092 -[GDTCORReachability init] (in UnityFramework) (GDTCORReachability.m:83)
21  UnityFramework                	0x000000010522ff54 0x105000000 + 2293588 __36+[GDTCORReachability sharedInstance]_block_invoke (in UnityFramework) (GDTCORReachability.m:54)
22  libdispatch.dylib             	0x00000001a730833c _dispatch_client_callout + 20
23  libdispatch.dylib             	0x00000001a7309a68 _dispatch_once_callout + 32
24  UnityFramework                	0x000000010522ff2c 0x105000000 + 2293548 +[GDTCORReachability sharedInstance] (in UnityFramework) (GDTCORReachability.m:53)
25  UnityFramework                	0x000000010522ffa4 0x105000000 + 2293668 +[GDTCORReachability currentFlags] (in UnityFramework) (GDTCORReachability.m:0)
26  UnityFramework                	0x0000000105232d34 0x105000000 + 2305332 -[GDTCORUploadCoordinator uploadConditions] (in UnityFramework) (GDTCORUploadCoordinator.m:150)
27  UnityFramework                	0x000000010523274c 0x105000000 + 2303820 __37-[GDTCORUploadCoordinator startTimer]_block_invoke_2 (in UnityFramework) (GDTCORUploadCoordinator.m:73)
28  libdispatch.dylib             	0x00000001a730833c _dispatch_client_callout + 20
29  libdispatch.dylib             	0x00000001a730aaf8 _dispatch_continuation_pop + 408
30  libdispatch.dylib             	0x00000001a731b624 _dispatch_source_invoke + 1224
31  libdispatch.dylib             	0x00000001a730e72c _dispatch_lane_serial_drain + 264
32  libdispatch.dylib             	0x00000001a730f290 _dispatch_lane_invoke + 400
33  libdispatch.dylib             	0x00000001a7318928 _dispatch_workloop_worker_thread + 584
34  libsystem_pthread.dylib       	0x00000001a736f714 _pthread_wqthread + 276
35  libsystem_pthread.dylib       	0x00000001a73759c8 start_wqthread + 8

Thread 2:
0   libsystem_pthread.dylib       	0x00000001a73759c0 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00000001a73759c0 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0xfffffffffffffffc   x1: 0x0000000000000000   x2: 0x0000000000000d01   x3: 0x0000000000000000
    x4: 0x00000000000062dc   x5: 0x00000002817c6b40   x6: 0x00000001e3ab1b3f   x7: 0x0000000000000000
    x8: 0x0000000000000907   x9: 0x0000000000000d00  x10: 0x0000000000000001  x11: 0x00030002817c9180
   x12: 0x000000026abe59ba  x13: 0x0000000108483a30  x14: 0x0000000082a24000  x15: 0x0000000000000048
   x16: 0x0000000000000203  x17: 0x000000010522ff34  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000010861e6b8  x21: 0x0000000001000002  x22: 0x0000000000000d01  x23: 0x00000001f5027000
   x24: 0x000000010980b800  x25: 0x00000001e38aecd5  x26: 0x0000000108483a08  x27: 0x00000001f5027000
   x28: 0x00000001f219c000   fp: 0x000000016d2323d0   lr: 0x00000001a7308cd8
    sp: 0x000000016d2323b0   pc: 0x00000001a744f7e4 cpsr: 0x00000000
   esr: 0x56000080  Address size fault
```

Podfile.lock:

```
PODS:
  - AppLovinSDK (6.12.2)
  - Crashlytics (3.14.0):
    - Fabric (~> 1.10.2)
  - Fabric (1.10.2)
  - FBAudienceNetwork (5.8.0):
    - FBSDKCoreKit/Basics (>= 5.6.0)
  - FBSDKCoreKit (6.5.1):
    - FBSDKCoreKit/Basics (= 6.5.1)
    - FBSDKCoreKit/Core (= 6.5.1)
  - FBSDKCoreKit/Basics (6.5.1)
  - FBSDKCoreKit/Core (6.5.1):
    - FBSDKCoreKit/Basics
  - FBSDKGamingServicesKit (6.5.1):
    - FBSDKShareKit (~> 6.5.1)
  - FBSDKLoginKit (6.5.1):
    - FBSDKLoginKit/Login (= 6.5.1)
  - FBSDKLoginKit/Login (6.5.1):
    - FBSDKCoreKit (~> 6.5.1)
  - FBSDKShareKit (6.5.1):
    - FBSDKShareKit/Share (= 6.5.1)
  - FBSDKShareKit/Share (6.5.1):
    - FBSDKCoreKit (~> 6.5.1)
  - Firebase/Analytics (6.21.0):
    - Firebase/Core
  - Firebase/Core (6.21.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.4.0)
  - Firebase/CoreOnly (6.21.0):
    - FirebaseCore (= 6.6.5)
  - Firebase/Messaging (6.21.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.3.0)
  - Firebase/RemoteConfig (6.21.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.4.9)
  - FirebaseABTesting (3.2.0):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.1)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseAnalytics (6.4.0):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.1)
    - GoogleAppMeasurement (= 6.4.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - FirebaseAnalyticsInterop (1.5.0)
  - FirebaseCore (6.6.5):
    - FirebaseCoreDiagnostics (~> 1.2)
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.2.4):
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleDataTransportCCTSupport (~> 3.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.2.0)
  - FirebaseInstallations (1.2.0):
    - FirebaseCore (~> 6.6)
    - GoogleUtilities/Environment (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.6)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.3.2):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
  - FirebaseMessaging (4.3.1):
    - FirebaseAnalyticsInterop (~> 1.5)
    - FirebaseCore (~> 6.6)
    - FirebaseInstanceID (~> 4.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Reachability (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseRemoteConfig (4.4.9):
    - FirebaseABTesting (~> 3.1)
    - FirebaseAnalyticsInterop (~> 1.4)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - GoogleUtilities/Environment (~> 6.2)
    - "GoogleUtilities/NSData+zlib (~> 6.2)"
    - Protobuf (>= 3.9.2, ~> 3.9)
  - Fyber_Marketplace_MoPubAdapter (0.9.4):
    - Fyber_Marketplace_SDK (= 7.5.4)
    - mopub-ios-sdk/Core (>= 5.5.0)
  - Fyber_Marketplace_SDK (7.5.4):
    - Fyber_Marketplace_SDK/IASDKCore (= 7.5.4)
    - Fyber_Marketplace_SDK/IASDKMRAID (= 7.5.4)
    - Fyber_Marketplace_SDK/IASDKVideo (= 7.5.4)
  - Fyber_Marketplace_SDK/IASDKCore (7.5.4)
  - Fyber_Marketplace_SDK/IASDKMRAID (7.5.4):
    - Fyber_Marketplace_SDK/IASDKCore
  - Fyber_Marketplace_SDK/IASDKVideo (7.5.4):
    - Fyber_Marketplace_SDK/IASDKCore
  - Google-Mobile-Ads-SDK (7.57.0):
    - GoogleAppMeasurement (~> 6.0)
  - GoogleAppMeasurement (6.4.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - GoogleDataTransport (6.0.0)
  - GoogleDataTransportCCTSupport (3.0.0):
    - GoogleDataTransport (~> 6.0)
    - nanopb (~> 0.3.901)
  - GoogleUtilities/AppDelegateSwizzler (6.6.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.6.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.6.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.6.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.6.0)"
  - GoogleUtilities/Reachability (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.6.0):
    - GoogleUtilities/Logger
  - IronSourceSDK (6.16.0.0)
  - MintegralAdSDK (6.2.0.0):
    - MintegralAdSDK/NativeAd (= 6.2.0.0)
  - MintegralAdSDK/BannerAd (6.2.0.0):
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/BidBannerAd (6.2.0.0):
    - MintegralAdSDK/BidNativeAd
  - MintegralAdSDK/BidInterstitialVideoAd (6.2.0.0):
    - MintegralAdSDK/BidNativeAd
  - MintegralAdSDK/BidNativeAd (6.2.0.0)
  - MintegralAdSDK/BidRewardVideoAd (6.2.0.0):
    - MintegralAdSDK/BidNativeAd
  - MintegralAdSDK/InterstitialVideoAd (6.2.0.0):
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/NativeAd (6.2.0.0)
  - MintegralAdSDK/RewardVideoAd (6.2.0.0):
    - MintegralAdSDK/NativeAd
  - MoPub-AdMob-Adapters/Network (7.57.0.0):
    - Google-Mobile-Ads-SDK (= 7.57.0)
    - mopub-ios-sdk/Core (~> 5.8)
    - mopub-ios-sdk/NativeAds (~> 5.8)
  - MoPub-Applovin-Adapters/Network (6.12.2.0):
    - AppLovinSDK (= 6.12.2)
    - mopub-ios-sdk/Core (~> 5.8)
  - MoPub-FacebookAudienceNetwork-Adapters/Network (5.8.0.0):
    - FBAudienceNetwork (= 5.8.0)
    - mopub-ios-sdk/Core (~> 5.6)
    - mopub-ios-sdk/NativeAds (~> 5.6)
  - mopub-ios-sdk/Core (5.12.1)
  - mopub-ios-sdk/NativeAds (5.12.1):
    - mopub-ios-sdk/Core
  - MoPub-IronSource-Adapters/Network (6.16.0.0.0):
    - IronSourceSDK (= 6.16.0.0)
    - mopub-ios-sdk/Core (~> 5.6)
  - MoPub-Mintegral-Adapters/Network (6.2.0.0.0):
    - MintegralAdSDK (= 6.2.0.0)
    - MintegralAdSDK/BannerAd (= 6.2.0.0)
    - MintegralAdSDK/BidBannerAd (= 6.2.0.0)
    - MintegralAdSDK/BidInterstitialVideoAd (= 6.2.0.0)
    - MintegralAdSDK/BidNativeAd (= 6.2.0.0)
    - MintegralAdSDK/BidRewardVideoAd (= 6.2.0.0)
    - MintegralAdSDK/InterstitialVideoAd (= 6.2.0.0)
    - MintegralAdSDK/RewardVideoAd (= 6.2.0.0)
    - mopub-ios-sdk/Core (~> 5.8)
    - mopub-ios-sdk/NativeAds (~> 5.8)
  - MoPub-SDK-Plugin (5.12.1)
  - MoPub-UnityAds-Adapters/Network (3.4.2.0):
    - mopub-ios-sdk/Core (~> 5.8)
    - UnityAds (= 3.4.2)
  - MoPub-Vungle-Adapters/Network (6.5.3.0):
    - mopub-ios-sdk/Core (~> 5.8)
    - VungleSDK-iOS (= 6.5.3)
  - nanopb (0.3.9011):
    - nanopb/decode (= 0.3.9011)
    - nanopb/encode (= 0.3.9011)
  - nanopb/decode (0.3.9011)
  - nanopb/encode (0.3.9011)
  - PromisesObjC (1.2.8)
  - Protobuf (3.11.4)
  - UnityAds (3.4.2)
  - VungleSDK-iOS (6.5.3)

DEPENDENCIES:
  - Crashlytics (= 3.14.0)
  - Fabric (= 1.10.2)
  - FBSDKCoreKit (~> 6.2)
  - FBSDKGamingServicesKit (~> 6.2)
  - FBSDKLoginKit (~> 6.2)
  - FBSDKShareKit (~> 6.2)
  - Firebase/Analytics (= 6.21.0)
  - Firebase/Core (= 6.21.0)
  - Firebase/Messaging (= 6.21.0)
  - Firebase/RemoteConfig (= 6.21.0)
  - FirebaseInstanceID (= 4.3.2)
  - Fyber_Marketplace_MoPubAdapter (= 0.9.4)
  - MoPub-AdMob-Adapters/Network (= 7.57.0.0)
  - MoPub-Applovin-Adapters/Network (= 6.12.2.0)
  - MoPub-FacebookAudienceNetwork-Adapters/Network (= 5.8.0.0)
  - mopub-ios-sdk/Core (= 5.12.1)
  - MoPub-IronSource-Adapters/Network (= 6.16.0.0.0)
  - MoPub-Mintegral-Adapters/Network (= 6.2.0.0.0)
  - MoPub-UnityAds-Adapters/Network (= 3.4.2.0)
  - MoPub-Vungle-Adapters/Network (= 6.5.3.0)

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - AppLovinSDK
    - Crashlytics
    - Fabric
    - FBAudienceNetwork
    - FBSDKCoreKit
    - FBSDKGamingServicesKit
    - FBSDKLoginKit
    - FBSDKShareKit
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseAnalyticsInterop
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreDiagnosticsInterop
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - FirebaseRemoteConfig
    - Fyber_Marketplace_MoPubAdapter
    - Fyber_Marketplace_SDK
    - Google-Mobile-Ads-SDK
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleDataTransportCCTSupport
    - GoogleUtilities
    - IronSourceSDK
    - MintegralAdSDK
    - MoPub-AdMob-Adapters
    - MoPub-Applovin-Adapters
    - MoPub-FacebookAudienceNetwork-Adapters
    - mopub-ios-sdk
    - MoPub-IronSource-Adapters
    - MoPub-Mintegral-Adapters
    - MoPub-UnityAds-Adapters
    - MoPub-Vungle-Adapters
    - nanopb
    - PromisesObjC
    - Protobuf
    - UnityAds
    - VungleSDK-iOS

SPEC CHECKSUMS:
  AppLovinSDK: 921463134d97f9ced16ffb0586e9b332e769b0a9
  Crashlytics: 540b7e5f5da5a042647227a5e3ac51d85eed06df
  Fabric: 706c8b8098fff96c33c0db69cbf81f9c551d0d74
  FBAudienceNetwork: 98c125767300048ad46c756680644f4ecb7c4040
  FBSDKCoreKit: 3ecb604427e115bd90ff7fc62ee1e30ebd12285b
  FBSDKGamingServicesKit: a09826780864f0875656b0e19b7b9d8f1d05d3c3
  FBSDKLoginKit: 8b2bc5fa30ea269e9d7208a1165c0a668c0ae826
  FBSDKShareKit: 9ad7b8d097fc568e911452feb8112ad7f04bb8a2
  Firebase: f378c80340dd41c0ad0914af740c021eb282a04b
  FirebaseABTesting: 821a3a3e4a145987e80fee3657c4de1cb9adf693
  FirebaseAnalytics: a1a0b3327ceb5cd5b4bacffdb293f6c909aa087d
  FirebaseAnalyticsInterop: 3f86269c38ae41f47afeb43ebf32a001f58fcdae
  FirebaseCore: 9f495d3afacb7b558711e6218ebb14b1c51b5802
  FirebaseCoreDiagnostics: b59c024493a409f8aecba02c99928d0d8431d159
  FirebaseCoreDiagnosticsInterop: 296e2c5f5314500a850ad0b83e9e7c10b011a850
  FirebaseInstallations: 2119fb3e46b0a88bfdbf12562f855ee3252462fa
  FirebaseInstanceID: 7ee0d6777013bb952f377b41965bf132b6a075be
  FirebaseMessaging: 828e66eb357a893e3cebd9ee0f6bc1941447cc94
  FirebaseRemoteConfig: 47abf7a04a9082091955ea555aa79cfdd249b19c
  Fyber_Marketplace_MoPubAdapter: 987aa149f0b436fc958fb9021b8b9a6a55916e9d
  Fyber_Marketplace_SDK: b72d26c042c5577096095d29d3c414bc2b9c9090
  Google-Mobile-Ads-SDK: ec897018b9ab9b447e7aa4876e7f75aba13ba2de
  GoogleAppMeasurement: 6e68a94d0eaeb1d73ef6b0ed4f7334e29d63ae29
  GoogleDataTransport: 061fe7d9b476710e3cd8ea51e8e07d8b67c2b420
  GoogleDataTransportCCTSupport: 0f39025e8cf51f168711bd3fb773938d7e62ddb5
  GoogleUtilities: 39530bc0ad980530298e9c4af8549e991fd033b1
  IronSourceSDK: 60f16cbdc91777e554f110a4d556c6aec2347609
  MintegralAdSDK: 038c5f82fa9312bbebea626282bf18f92037a50c
  MoPub-AdMob-Adapters: caa45d156ca6c22f50b2431d5f9df3fb2c709abf
  MoPub-Applovin-Adapters: 4f411bf0fa1c273ed4697ec63343ccb3f31b2938
  MoPub-FacebookAudienceNetwork-Adapters: d8685afd43497425c2338477faa3780eaadfc973
  mopub-ios-sdk: d1640225b34ad74700e2acddb116cac634fc45d8
  MoPub-IronSource-Adapters: 007bf62fe1dd1f1123dd0831f2486133f4217002
  MoPub-Mintegral-Adapters: bc30f18c02c884fd7815c5c8c51ddb32ce300fb1
  MoPub-SDK-Plugin: 1decbdb27df5424a87c36c31e5b3b149bc969408
  MoPub-UnityAds-Adapters: 686fcb4efac29e58e0264b5fec0be40d687b607a
  MoPub-Vungle-Adapters: 352e6334c33652a4c707ec633bebb28f567b794d
  nanopb: 18003b5e52dab79db540fe93fe9579f399bd1ccd
  PromisesObjC: c119f3cd559f50b7ae681fa59dc1acd19173b7e6
  Protobuf: 176220c526ad8bd09ab1fb40a978eac3fef665f7
  UnityAds: db0da29fa3a7e519bceea56693909df0dd83caa5
  VungleSDK-iOS: f54778abc3ebe6542e1000e5a83e5e35716e0d09

PODFILE CHECKSUM: 583df57468f4994ca27a178cc1087b9420f38654

COCOAPODS: 1.9.1
```

### PR DESCRIPTION
**Pull request by mikehaney24**
Fixes #5463

### CODE REVIEW

**Comment by mikehaney24** [comment]
> @mikehaney24 Could you please provide a bit more info why this will fix the issue?

The app seems to be getting stuck in +load for some reason (I don't know why in Unity vs. non-Unity). Moving the flag initialization out of +load hopefully will allow the app to get out of that. I believe that the OS still has the app 'in the background' because loading doesn't finish quickly enough to trigger foregrounding lifecycle events.

**Comment by maksymmalyhin** [comment]
Looking and the call stack it seems like another option why the crash may happen is a deadlock involving `dispatch_once`, `dispatch_sync` and an internal synchronization in `SCNetworkReachabilitySetDispatchQueue`.  If it is true, then the root cause of the issue may not be solved by the change. 

I wonder, if it is possible to avoid using `dispatch_sync` to prevent the deadlock conditions?

**Comment by mikehaney24** [comment]
> Looking and the call stack it seems like another option why the crash may happen is a deadlock involving `dispatch_once`, `dispatch_sync` and an internal synchronization in `SCNetworkReachabilitySetDispatchQueue`. If it is true, then the root cause of the issue may not be solved by the change.
> 
> I wonder, if it is possible to avoid using `dispatch_sync` to prevent the deadlock conditions?

I don't think it's possible for dispatch_once to deadlock here (or in general with normal usage), and calling SCNetworkReachabilitySetDispatchQueue occurs off the reachabilityQueue. There's no dispatch_sync here, but there is a dispatch_async in -init that's called in +sharedInstance. I'd expect a deadlock to crash differently rather than wait for 20s before being killed.

**Comment by maksymmalyhin** [comment]
I'm referring to dispatch_sync in [currentFlags](https://github.com/firebase/firebase-ios-sdk/blob/56f68a3e3cc4f7f31ea50abd59fde8bf0755cf1f/GoogleDataTransport/GDTCORLibrary/GDTCORReachability.m#L61) method which is called from `-[GDTCORUploadCoordinator uploadConditions]` method. Looks like `[GDTCORReachability sharedInstance]`  called from the coordinator makes `load` method waiting on the main thread (main thread is blocked), so if `SCNetworkReachabilitySetDispatchQueue` by chance waits for main thread, it closes the deadlock.

**Comment by mikehaney24** [comment]
> I'm referring to dispatch_sync in [currentFlags](https://github.com/firebase/firebase-ios-sdk/blob/56f68a3e3cc4f7f31ea50abd59fde8bf0755cf1f/GoogleDataTransport/GDTCORLibrary/GDTCORReachability.m#L61) method which is called from `-[GDTCORUploadCoordinator uploadConditions]` method. Looks like `[GDTCORReachability sharedInstance]` called from the coordinator makes `load` method waiting on the main thread (main thread is blocked), so if `SCNetworkReachabilitySetDispatchQueue` by chance waits for main thread, it closes the deadlock.

The coordinator runs on its own queue, I don't think calling -currentFlags->sharedInstance is causing +load to wait. +load is likely still running (on the main thread) and GDTCORUploadCoordinator is waiting for that to finish so it can finish its call to -currentFlags. I'm not convinced my change will fix the problem (I think there's a good chance a different part of the SDK that gets hung up on launch), but it's what I got for now.

**Pull request merged**
