### PR TITLE
fix typo in tests

### PR DESCRIPTION
**Pull request by yoyomyo**
s/Veriy/Verify in tests.
 #no-changelog

### CODE REVIEW

**Comment by yoyomyo** [comment]
Creating a new PR to address the comment 
https://github.com/firebase/firebase-ios-sdk/pull/8560#discussion_r698850531

**Review by rosalyntan — APPROVED** [review]
Nice, thanks for the cleanup!

**Comment by yoyomyo** [comment]
Not sure why `./scripts/build.sh AuthUnit iOS spm` is complaining about the following

```
Failing tests:
	AuthUnit:
		-[UseUserAccessGroupTests testUseUserAccessGroup]
```

Test passes locally. Maybe it is flaky?

**Comment by paulb777** [comment]
Almost certainly a flake based on history in https://github.com/firebase/firebase-ios-sdk/actions/workflows/auth.yml. You could do a rerun to confirm.

**Comment by yoyomyo** [comment]
> Almost certainly a flake based on history in https://github.com/firebase/firebase-ios-sdk/actions/workflows/auth.yml. You could do a rerun to confirm.

Thank you, Paul!

**Pull request merged**
