### PR TITLE
Fix Sessions on Xcode 13

### PR DESCRIPTION
**Pull request by samedson**
Fixes: https://github.com/firebase/firebase-ios-sdk/issues/10793

#no-changelog

### CODE REVIEW

**Review by andrewheard — APPROVED** [review]
You beat me to this [fix](https://github.com/firebase/firebase-ios-sdk/commit/1e2d7773a6593334e2a3d35e051005678b13ebe0). I needed to get Xcode 13 working to try deploying to my old iPad for the bug bash :P

**Comment by samedson** [comment]
@andrewheard on an M1 mac running Ventura, `/Applications/Xcode_13_3_1.app/Contents/MacOS/Xcode` is the secret password for running Xcode 13

**Review by visumickey — APPROVED** [review]
Glad to see the change exactly the same between you and @andrewheard . Curious on how this answer was found? Is this a common practice documented anywhere?

**Comment by samedson** [comment]
@visumickey Swift has great error messages - I used them to guide me: https://github.com/firebase/firebase-ios-sdk/issues/10793

Screenshot 2023-02-09 at 11 32 33 AM

These 2 statements are equivalent:

```
UnsafeMutablePointer<pb_bytes_array_t>
```

```
UnsafeMutablePointer: where Pointee == pb_bytes_array_t
```

Because UnsafeMutablePointer is defined as `UnsafeMutablePointer<Pointee>`

**Pull request merged**
