### PR TITLE
[Storage] Debug updateMetadata customMetadata iniWithDictionary issue

### PR DESCRIPTION
**Pull request by andrewheard**
Debugging the issue `updateMetadata` method fails to update `customMetadata` when you initialize metadata with `initWithDictionary`. See #10374 issue 6 for further details.

### CODE REVIEW

**Comment by andrewheard** [comment]
Nick found some important details:
> Debugging further, I isolated the difference in behavior through this call stack. The `StorageMetadata.remove` API functions differently depending on the initialization pattern because when you use initWithDictionary, both the `matchingMetadata` and `oldMetadata` are the same and the `StorageMetadata.remove` cancels them out (removing the custom metadata).

**Comment by andrewheard** [comment]
I added some inline comments to the files for debugging. @paulb777 made a good suggestion to check if the issue existed in the old implementation. A quick look at [FIRStorageMetadata.m](https://github.com/firebase/firebase-ios-sdk/blob/111d8d6ad1a1afd6c8e9561d26e55ab1e74fcb42/FirebaseStorage/Sources/FIRStorageMetadata.m#L169-L195) makes me think that it would but I haven't tested to verify.

**Comment by paulb777** [comment]
Both Firebase 8 and 9 fail the test in the same way.

**Comment by paulb777** [comment]
Closing. See the explanation in #10374

**Pull request closed without merging**
