### PR TITLE
Merge release 7.2.0

### PR DESCRIPTION
**Pull request by ryanwilson**
Will wait for publishing, but needs to be merged right after publishing so our release notes have a live link to point to.

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]
LGTM on green

**Comment by mikehardy** [comment]
@paulb777 / @ryanwilson 

I recognize publishing may still be in progress - if so apologies for the noise - but on the off chance they appear to be completed on your end, as a consume they appear either incomplete or to have changed in a way where there is no .zip associated with the tag?

Previous: https://github.com/firebase/firebase-ios-sdk/releases/tag/CocoaPods-7.1.0
Current: https://github.com/firebase/firebase-ios-sdk/releases/tag/CocoaPods-7.2.0

Noticed since I our "firestore compile time optimization" dependency publish script busted on 7.2.0: https://github.com/invertase/firestore-ios-sdk-frameworks/runs/1492499554?check_suite_focus=true

**Comment by paulb777** [comment]
@mikehardy Yes the 7.2.0 release was still in progress. The zip should now be available at https://github.com/firebase/firebase-ios-sdk/releases/tag/CocoaPods-7.2.0

**Comment by mikehardy** [comment]
Excellent @paulb777 thanks - hopefully we handle all the new apple silicon / arm slice stuff correctly and don't mess up our downstream, but that's on us :-). Cheers

**Pull request merged**
