### PR TITLE
[Auth] Migrate setFields behavior to Response initializer

### PR DESCRIPTION
**Pull request by ncooke3**
#no-changelog

### CODE REVIEW

**Comment by ncooke3** [comment]
@andrewheard, assuming I did this correctly, this is a refactor to address https://github.com/firebase/firebase-ios-sdk/pull/14012#pullrequestreview-2413789293. While it does remove the `let`, I may have made it more convoluted. WDYT?

**Comment by andrewheard** [comment]
> @andrewheard, assuming I did this correctly, this is a refactor to address [#14012 (review)](https://github.com/firebase/firebase-ios-sdk/pull/14012#pullrequestreview-2413789293). While it does remove the `let`, I may have made it more convoluted. WDYT?

I think you're right that it was more readable before. If this isn't blocking your plans to make `AuthBackend` an actor, potentially we could defer to Paul for a second opinion later in the week?

**Comment by ncooke3** [comment]
> > @andrewheard, assuming I did this correctly, this is a refactor to address [#14012 (review)](https://github.com/firebase/firebase-ios-sdk/pull/14012#pullrequestreview-2413789293). While it does remove the `let`, I may have made it more convoluted. WDYT?
> 
> I think you're right that it was more readable before. If this isn't blocking your plans to make `AuthBackend` an actor, potentially we could defer to Paul for a second opinion later in the week?

Yes, SG. You're right that this won't block future improvements. I think we'd have to do a larger refactor to make response handling code better, and I'm unsure if we can make some of the assumptions along the way.

**Review by paulb777 — APPROVED** [review]
Replacing `setFields` with an `init` is a nice cleanup and I don't think the call-site is any more convoluted than it already was.

**Review by andrewheard — APPROVED** [review]

**Pull request merged**
