### PR TITLE
Improve confusing FirebaseCommunity pod usage instructions

### PR DESCRIPTION
**Pull request by paulb777**
See the comment at https://stackoverflow.com/a/45472783/556617

### CODE REVIEW

**Comment by ryanwilson** [comment]
May be a silly question: does leaving out the git repo link cause issues when using it outside of the repo itself? `FirebaseCommunity` pod isn't published at all, so using it outside of the project would break, no?

**Comment by paulb777** [comment]
@ryanwilson FirebaseCommunity was published several weeks ago.

**Comment by ryanwilson** [comment]
My bad :) Thanks!

**Comment by mcdonamp** [comment]
@ryanwilson I had the same initial confusion. I think it's because using it directly (without a subspec) doesn't have anything besides `firebase.h`, which led me to believe it was published in name only.

**Pull request merged**
