### PR TITLE
Use at least Protobuf 3.9.2

### PR DESCRIPTION
**Pull request by paulb777**
To ensure that we get the fix in Protobuf 3.9.2 for #3851

### CODE REVIEW

**Comment by wilhuff** [comment]
Why not specify at least 3.9.2?

**Comment by paulb777** [comment]
Because we want to pick up 3.10.0 automatically when it comes out - which should fix #2665

**Comment by wilhuff** [comment]
In that case, we want multiple version specs:

```
  s.dependency 'Protobuf', '~> 3.9', '>= 3.9.2'
```

I had version 3.9.0 installed in my project and got this this error on pod install after adding that to Firestore:

```
[!] CocoaPods could not find compatible versions for pod "Protobuf":
  In snapshot (Podfile.lock):
    Protobuf (= 3.9.0, ~> 3.0, ~> 3.1)

  In Podfile:
    FirebaseFirestore (from `../../`) was resolved to 1.5.0, which depends on
      Protobuf (>= 3.9.2, ~> 3.9)

It seems like you've changed the constraints of dependency `Protobuf` inside your development pod `FirebaseFirestore`.
You should run `pod update Protobuf` to apply changes you've made.
```

**Comment by cruisediary** [comment]
I'm waiting for next SDK release include this PR :D

**Pull request merged**
