### PR TITLE
[Vertex AI] Prepare podspec for a CocoaPods release

### PR DESCRIPTION
**Pull request by andrewheard**
- Renamed `FirebaseVertexAI-Docs.not_podspec` to `FirebaseVertexAI.podspec` in preparation for a CocoaPods release
- Removed an extraneous dependency on `SharedTestUtilities`
- Updated resource loading to handle both SPM and CocoaPods tests

Note: CI and ZipBuilder changes will still be needed before a release.

#no-changelog

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]
I'm ok for it to be a follow up PR, but a podspec build and tests should be added to CI similar to other products

Also configuration is needed to include in the zip build

Does anything need to change on the docs gen side to find the new path?

**Comment by andrewheard** [comment]
> I'm ok for it to be a follow up PR, but a podspec build and tests should be added to CI similar to other products
> 
> Also configuration is needed to include in the zip build
> 
> Does anything need to change on the docs gen side to find the new path?

@paulb777 I'm working on adding a `pod-lib-lint` job similar to the [storage one](https://github.com/firebase/firebase-ios-sdk/blob/7c6c5556de9c5db6b7dc64eba8ddf5f495f572cd/.github/workflows/storage.yml#L152-L179) in another PR. Any other tests that should be included as well?

For docs gen, just won't need to manually rename `FirebaseVertexAI-Docs.not_podspec` to `FirebaseVertexAI.podspec` first (@morganchen12 please let me know if that's not accurate).

**Comment by andrewheard** [comment]
> > I'm ok for it to be a follow up PR, but a podspec build and tests should be added to CI similar to other products
> > Also configuration is needed to include in the zip build
> > Does anything need to change on the docs gen side to find the new path?
> 
> @paulb777 I'm working on adding a `pod-lib-lint` job similar to the [storage one](https://github.com/firebase/firebase-ios-sdk/blob/7c6c5556de9c5db6b7dc64eba8ddf5f495f572cd/.github/workflows/storage.yml#L152-L179) in another PR. Any other tests that should be included as well?
> 
> For docs gen, just won't need to manually rename `FirebaseVertexAI-Docs.not_podspec` to `FirebaseVertexAI.podspec` first (@morganchen12 please let me know if that's not accurate).

Note: Added a basic `pod-lib-lint` job in this PR and verified with Morgan for docs generation (he said this would simplify it for him).

**Comment by paulb777** [comment]
LGTM thanks

**Pull request merged**
