### PR TITLE
updating change log

### PR DESCRIPTION
**Pull request by eldhosembabu**
updating change log wrt https://github.com/firebase/firebase-ios-sdk/pull/9134

### CODE REVIEW

**Comment by eldhosembabu** [comment]
We could hold this merge until the backend fix for the issue is done. wdyt?

**Review by paulb777 — APPROVED** [review]
I think it's fine to merge now since the 8.12.0 SDK will support the feature. If we think the back end change will take more than a few weeks, I would suggest adding something like - "This SDK fix will work once the backend is also updated."

**Comment by eldhosembabu** [comment]
filed an internal bug to track the backend issue : b/216496087

**Comment by eldhosembabu** [comment]
> I think it's fine to merge now since the 8.12.0 SDK will support the feature. If we think the back end change will take more than a few weeks, I would suggest adding something like - "This SDK fix will work once the backend is also updated."

Done. added the above mentioned comment. It seems like backend team needs prioritize this fix and probably would take couple of weeks.

**Pull request merged**
