### PR TITLE
add NSLocalizedString()

### PR DESCRIPTION
**Pull request by rohandandavati**
add NSLocalizedString() to user-facing strings to fix https://github.com/firebase/firebase-ios-sdk/issues/5255

### CODE REVIEW

**Comment by christibbs** [comment]
LGTM, add a PR description though.

**Comment by christibbs** [comment]
@paulb777 this is a fix for #5255. Is there a way to check if this resolves warnings in the next version of CocoaPods?

**Comment by morganchen12** [comment]
You could try using CocoaPods from master. Here's a [guide on using prerelease CocoaPods features](https://guides.cocoapods.org/using/unreleased-features).

**Comment by paulb777** [comment]
If you want to avoid diving too deep into Ruby configuration foo, I have CocoaPods master set up on machine and can verify later this afternoon.

**Comment by rohandandavati** [comment]
Hey Paul if you wouldn't mind that would be great, thanks!

**Comment by paulb777** [comment]
Verified that CocoaPods master fails to lint on Firebase master and passes lint on this branch.

**Comment by christibbs** [comment]
> Verified that CocoaPods master fails to lint on Firebase master and passes lint on this branch.

Thanks Paul!

**Pull request merged**
