### PR TITLE
Minimal fix for b/74357976.

### PR DESCRIPTION
**Pull request by mikelehen**
This is a more minimal alternative to #887.

### CODE REVIEW

**Comment by wilhuff** [comment]
Oh also, changelog

**Comment by mikelehen** [comment]
Good call, added changelog entry.

**Comment by paulb777** [comment]
I made a release-4.10.1 branch. Please target it there.

**Comment by mikelehen** [comment]
I've changed the target branch, but we're looking into an additional (perhaps related issue) so may want to hold off on merging this.

**Comment by mikelehen** [comment]
Okay, I've incorporated the second fix that @wilhuff tracked down. PTAL

**Comment by mikelehen** [comment]
Actually @wilhuff is doing a further audit of WrapNSStringNoCopy() usages for additional potential bugs...

**Comment by mikelehen** [comment]
@wilhuff is going to create a separate PR for all of the util:WrapNSStringNoCopy() fixes. This PR will just be for the original token issue and should be good-to-go now.

**Pull request merged**
