### PR TITLE
Xcode 12.2 and other doc updates

### LINKED ISSUE #7837: Update minimum supported Xcode version
For Firebase 8, review minimum supported Xcode, update, and make sure docs are consistent.  Perhaps 12.2?

### PR DESCRIPTION
**Pull request by paulb777**
Fix #7837

Update minimum Xcode version to 12.2.
Update minimum Xcode version for SPM usage to 12.5.

Now that M1 Macs are supported by default, remove special instructions.

### CODE REVIEW

**Review by ryanwilson — APPROVED** [review]

**Comment by lumaxis** [comment]
@paulb777 @ryanwilson Just a heads-up that the `AppleSilicon.md` file is still referenced from the main Readme

**Comment by lumaxis** [comment]
… and from https://firebase.google.com/docs/ios/setup

**Comment by paulb777** [comment]
Thanks @lumaxis ! The Readme is fixed in #8104 and I'll get started on the internal link.

**Comment by paulb777** [comment]
Internal cl/374446302

**Comment by lumaxis** [comment]
Great, thanks for the quick fix! 😊

**Pull request merged**
