### PR TITLE
import `abseil::optional`

### PR DESCRIPTION
**Pull request by zxu123**
Based on abseil version bf7fc99, the same version as the other imported abseil libraries.

Will eventually merge to `abseil-mirror`; right now into the pending branch `cpp/port_optional_unchanged` for easy review.

### CODE REVIEW

**Comment by rsgowman** [comment]
Before reviewing, I've got an optional suggestion:

Rather than importing this as one big commit (or I guess, 2 in this case,) could you instead:
1) Create a commit with the files from absl *without* changes. Don't worry that it's not hooked into the build (or doesn't build) or doesn't pass style.sh/lint.sh, etc.
2) Create a second commit (or more) that actually makes the changes (i.e. hooks it into the build, removes unnecessary stuff, passes lint, etc.)

This should make it easier to see which lines came from absl, and which were introduced to fit it into our build.

**Comment by wilhuff** [comment]
@var-const we have a tracking branch specifically for the unmodified changes: Could you commit the unmodified versions of these files on the `abseil-mirror` branch, rebase these changes on top of that, and then propose the merge?

That way you'll have a commit in the sequence that just shows what you had to do to make it work and when we upgrade the underlying abseil sources we'll have an obvious three-way merge to work with (rather than a two-way conflict see this way)

**Comment by rsgowman** [comment]
@wilhuff's suggestion is better. Do that. :)

**Comment by var-const** [comment]
@wilhuff I can do that if you'd like (unless you meant to notify Zhi)

**Comment by wilhuff** [comment]
No no I meant merely to call it out as a refinement of what you were proposing--not that you should do it.

**Comment by zxu123** [comment]
Please check the cleaner PR #1093 instead, where the branch is based on `abseil-mirror`. This PR branch is based on a more recent version of `master` and has irrelevant commits from master.

**Comment by wilhuff** [comment]
This is obsoleted by #1112.

**Pull request closed without merging**
