### PR TITLE
Update to CocoaPods 1.10.1

### PR DESCRIPTION
**Pull request by paulb777**
#no-changelog

### CODE REVIEW

**Comment by paulb777** [comment]
Only failure is one that has been frequent lately on travis:

`    - NOTE  | xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m:1265: error: -[GDTCORFlatFileStorageTest testStoreEvent_WhenSizeLimitReached_ThenNewEventIsSkipped] : Asynchronous wait failed: Exceeded timeout of 1 seconds, with unfulfilled expectations: "eventStored".`

**Comment by maksymmalyhin** [comment]
> Only failure is one that has been frequent lately on travis:
> 
> ` - NOTE | xcodebuild: /Users/travis/build/firebase/firebase-ios-sdk/GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m:1265: error: -[GDTCORFlatFileStorageTest testStoreEvent_WhenSizeLimitReached_ThenNewEventIsSkipped] : Asynchronous wait failed: Exceeded timeout of 1 seconds, with unfulfilled expectations: "eventStored".`

This test is resource heavy, so I think increasing the timeout should be a reasonable attempt to fix. Alternatively, I think, we may disable GDT tests on Travis.

**Review by maksymmalyhin — APPROVED** [review]
👍

**Comment by paulb777** [comment]
Sounds reasonable. Travis will likely be disabled soon anyway.

**Pull request merged**
