### PR TITLE
Add counter for errors and warnings logged.

### PR DESCRIPTION
**Pull request by ryanwilson**

### CODE REVIEW

**Comment by paulb777** [comment]
How is this intended to be used?

I re-kicked the tests since it wasn't clear why they failed.

**Comment by ryanwilson** [comment]
Hmm, I'll try to figure out the test issue. Can't seem to see exactly which tests are failing!

Ideally `5.0.0`, yes.

**Comment by paulb777** [comment]
I see a crash running the Core unit tests locally in your branch. The location isn't clear because it's from an async call to FIRLogBasic.

screen shot 2018-04-24 at 8 13 13 pm

**Comment by ryanwilson** [comment]
I think it's from `[NSUserDefaults standardUserDefaults]`. I've broken it out into separate lines and it seems consistent there, trying to resolve it.

**Comment by ryanwilson** [comment]
I removed it from the `dispatch_async` block and everything is working as expected. Couldn't find any reasoning but I'll upload a new commit making that change.

**Comment by ryanwilson** [comment]
Yeah, I'll try to figure out what's failing. `[NSUserDefaults standardUserDefaults]` says it's thread safe, but maybe it's something to do with being on a background thread...

**Comment by paulb777** [comment]
Merging now for 5.0.0 RC.

**Pull request merged**
