### PR TITLE
[#9291] Removed `FIRAppAssociationRegistration`

### LINKED ISSUE #9291: Remove `FIRAppAssociationRegistration` class.
This is no longer used in any Firebase SDK. I'm not sure when the last usage was removed, so it's safest to wait until the next breaking change to do so.

https://github.com/firebase/firebase-ios-sdk/blob/78b9b7fb10fa10d8605c865eb660b921afe0a27c/FirebaseCore/Sources/FIRAppAssociationRegistration.h#L27

### PR DESCRIPTION
**Pull request by yakovmanshin**
[Closes #9291]

* Removed the `FIRAppAssociationRegistration` class which is no longer used in Firebase Core
* Removed `FIRAppAssociationRegistrationTests`

### CODE REVIEW

**Comment by paulb777** [comment]
Thanks! I'll mark this for our next breaking change release since older versions of MLKit might still be relying on this.

**Comment by paulb777** [comment]
Plan to merge once the v9 branch merges to master

**Comment by yakovmanshin** [comment]
> Plan to merge once the v9 branch merges to master

Hi @paulb777! Should I redirect this PR to the `v9` branch?

**Comment by paulb777** [comment]
Hi @yakovmanshin!  Either way. If you like, you could rebase the commit to v9 and redirect the PR.

**Comment by yakovmanshin** [comment]
> Hi @yakovmanshin! Either way. If you like, you could rebase the commit to v9 and redirect the PR.

I updated this PR so it can be merged to `v9`.

FYI @paulb777

**Review by paulb777 — APPROVED** [review]

**Pull request merged**
