### PR TITLE
Require Xcode 14.1

### PR DESCRIPTION
**Pull request by paulb777**

### CODE REVIEW

**Comment by paulb777** [comment]
Ugh! It looks like Xcode 14.1 built binaries are not supported by Xcode 14.2!

/Users/runner/work/firebase-ios-sdk/firebase-ios-sdk/quickstart-ios/config/ConfigExample/RemoteConfigViewController.swift:17:8: error: failed to build module 'FirebaseRemoteConfigSwift'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)'). Please select a toolchain which matches the SDK.
import FirebaseRemoteConfigSwift

From https://github.com/firebase/firebase-ios-sdk/actions/runs/4520048182/jobs/7962839871

**Comment by paulb777** [comment]
Some context at https://github.com/facebook/facebook-ios-sdk/issues/2180#issuecomment-1485905206

**Comment by paulb777** [comment]
This PR can be updated or used as a reference after #11522 merges. cc: @ncooke3

**Comment by ncooke3** [comment]
Closing in favor of #11522

**Pull request closed without merging**
