### PR TITLE
[Release] Update binary SPM Firestore distro for 10.24.0

### PR DESCRIPTION
**Pull request by ncooke3**
#no-changelog

### CODE REVIEW

**Comment by ncooke3** [comment]
I'm working on re-publishing the FST deps right now (because of the macOS/Catalyst framework changes). Do you think we should pin to their new versions in the Firebase `Package.swift`?

**Comment by paulb777** [comment]
So the FST updates will be patch version updates?

It might be better to pin to the update since we know the current version is bad (and not detectable until App Store deployment)

**Comment by ncooke3** [comment]
> So the FST updates will be patch version updates?

Yes

**Review by paulb777 — APPROVED** [review]
I'm OK either way on updating the absl and grpc deps.

**Comment by ncooke3** [comment]
> I'm OK either way on updating the absl and grpc deps.

Will do so in a follow-up PR!

**Pull request merged**
