### PR TITLE
Run Danger from GHA

### PR DESCRIPTION
**Pull request by maksymmalyhin**
Move Danger job from Travis to GitHub Actions.

#no-changelog

### CODE REVIEW

**Comment by paulb777** [comment]
What's different about the danger that is directly integrated to GitHub versus the danger run that is integrated into GHA (and was travis)?

**Comment by maksymmalyhin** [comment]
@paulb777 TBH I was not aware of a GitHub danger version. Would you share a link please?

**Comment by paulb777** [comment]
See the two danger runs in this PR - @morganchen12, do you know how danger is integrated?

Screen Shot 2020-03-30 at 9 47 07 AM

**Comment by maksymmalyhin** [comment]
> See the two danger runs in this PR - @morganchen12, do you know how danger is integrated?
> 

Discussed with Morgan: the check is added by the Danger run from CI - it is not a separate run.

**Comment by paulb777** [comment]
Do you know why the check and danger runs are now both doubled on the PR?

**Comment by morganchen12** [comment]
Danger reports a separate check because it was initially designed to run from a travis `before_script`, which is unable to separate danger failures and main job script failures. It still does this in GHA, even though the GHA job is granular enough to report its own success/failure.

**Pull request merged**
