### PR TITLE
Merge updated abseil-cpp to master

### PR DESCRIPTION
**Pull request by wilhuff**
This brings in these changes:
  * Update abseil-cpp to a new upstream (#754)
  * Add StrCat, StrJoin and the rest of //strings from abseil-cpp (#756)

### CODE REVIEW

**Comment by var-const** [comment]
IIUC, absl/strings/CMakeLists.txt is not touched by this merge (the version currently in master is truncated from the original). Is this intentional?

**Comment by wilhuff** [comment]
Apologies. I had managed to push this PR up while my local modifications were in the index but otherwise uncommitted. PTAL

**Comment by var-const** [comment]
@wilhuff Gil, I can merge this into my feature branch to make sure everything compiles/works correctly, but feel free to merge without waiting for that.

**Comment by wilhuff** [comment]
I'll wait for travis to confirm my local builds before merging to master.

**Pull request merged**
