### PR TITLE
fix for _userAccessGroup being nil when getStoredUserForAccessGroup is called

### PR DESCRIPTION
**Pull request by joehinkle11**
This is a small change which fixes a significant bug. Basically the app doesn't let users share access groups until second launch

To reproduce:
 1. build 2 apps with a shared access group (useUserAccessGroup)
 2. sign in the first app
 3. open the second app (for the first time! if you already opened it, delete and reinstall)
 4. notice the second app is unable to load the access group
 5. force close the second app
 6. reopen the second app
 7. notice the second app is now able to load the access group

The cause: `_userAccessGroup` is set AFTER `getStoredUserForAccessGroup` is called, and `getStoredUserForAccessGroup` depends on `_userAccessGroup` not being null

Solution: swap the order of when `_userAccessGroup` is set and when `getStoredUserForAccessGroup` is called

### CODE REVIEW

**Comment by paulb777** [comment]
@joehinkle11 Thanks for the fix and PR. 

@rosalyntan Please take a look.

Note the CI failure can be disregarded. (#7476)

**Review by rosalyntan — COMMENTED** [review]
Thanks for finding and fixing this issue! Your fix should work, but I took a look into the code, and I think you'll actually want to make a change in https://github.com/firebase/firebase-ios-sdk/blob/025eecd1fcad2eaf84e73deb923a7f54004981cc/FirebaseAuth/Sources/Auth/FIRAuth.m#L2261 instead -- I believe we should be using the passed-in `accessGroup` rather than `self.userAccessGroup` there.

**Comment by joehinkle11** [comment]
@rosalyntan updated!

**Review by rosalyntan — APPROVED** [review]
Thanks! LGTM

**Comment by mikehardy** [comment]
Irony: react-native-firebase was inadvertently relying on the old behavior in our E2E test suite, and now that this is working our test suite broke when I attempted to adopt v7.8.0. To be clear: as far as I can tell our test suite was not using the API correctly, but the way unintended consequences ripple out always fascinates me. Cheers all

**Comment by joehinkle11** [comment]
@mikehardy Glad I was a service in breaking something 😅

**Comment by peterfriese** [comment]
> @mikehardy Glad I was a service in breaking something 😅

Breaking Stuff as a Service ;-)

**Pull request merged**
