### PR TITLE
s/withMaxResults/maxResults

### PR DESCRIPTION
**Pull request by schmidt-sebastian**
Feel free to push back, but it would be nice to align this name with `data(maxSize)`.

### CODE REVIEW

**Review by paulb777 — COMMENTED** [review]
Please fix CI

**Comment by paulb777** [comment]
The change sounds reasonable to me. We'll discuss on the iCore team tomorrow.

**Comment by ryanwilson** [comment]
I'm good with the change, I don't think we'd have the functionality to be able to deprecate the Swift naming anyways so it's acceptable in my eyes to do it at breaking change time. Definitely worth an email to the API council though, but LGTM for iOS.

**Comment by schmidt-sebastian** [comment]
> I'm good with the change, I don't think we'd have the functionality to be able to deprecate the Swift naming anyways so it's acceptable in my eyes to do it at breaking change time. Definitely worth an email to the API council though, but LGTM for iOS.

I will email the council. The naming in this PR is the approved name from the review, so any pushback will likely just be from the breaking change.

**Review by paulb777 — APPROVED** [review]

**Review by maksymmalyhin — APPROVED** [review]
LGTM

**Pull request merged**
