### PR TITLE
Clarify GA CHANGELOG wording

### PR DESCRIPTION
**Pull request by samedson**

### CODE REVIEW

**Comment by morganchen12** [comment]
Do you want these changes to go into devsite today as well?

**Comment by samedson** [comment]
If possible, that would be awesome @morganchen12. I think I left a comment on the CL, but LGTM'd at the same time.

**Comment by morganchen12** [comment]
Changes staged in cr/307640018

**Comment by samedson** [comment]
LGTM and shipping this

**Pull request merged**
