### PR TITLE
adding more token tests

### PR DESCRIPTION
**Pull request by chliangGoogle**
Move the following token class tests from IID to Messaging
TokenInfo
TokenOperation
TokenStore
Utilities
#no-changelog

### CODE REVIEW

**Comment by chliangGoogle** [comment]
Not sure the breakage is related, sth to do with Firestore.

**Comment by paulb777** [comment]
I suspect the CI failure may resolve with a merge or rebase of origin/master

**Comment by chliangGoogle** [comment]
That means I will need to rebase for both my dev branch and master branch.

**Comment by paulb777** [comment]
Sorry I missed that this was targeting the feature branch. That makes the git foo a bit more complicated. I believe the diffs might get cleaned up if you rebase and force push `chen/fm-master`.  Let me know if you want me to work on fixing both branches or schedule a GVC if you want to pair on it.

**Comment by chliangGoogle** [comment]
@paulb777 I'm not sure we can fix chen/fm-master, unless we can revert my previous commit. But yeah feel free to do it without me or we can schedule a time when you are free.

**Pull request closed without merging**
