### PR TITLE
Fix import for watchOS

### PR DESCRIPTION
**Pull request by peterfriese**
This needs to be TARGET_OS_WATCH (also see the corresponding .m file, where it actually already is TARGET_OS_WATCH)

#no-changelog

### CODE REVIEW

**Review by ryanwilson — APPROVED** [review]

**Comment by derkaramma** [comment]
I'm having trouble with this error. My app is not and will not be available for Apple Watch. Would anyone know how I go about quitting the error till the update is pushed?

**Comment by paulb777** [comment]
You could either edit the file manually in your installation or keep using Xcode 12.4 or earlier

**Comment by pistoleta** [comment]
> file

This means edit the file on every build? isn't there a file on unity  that could be modified to avoid this ?
Thanks

**Comment by pistoleta** [comment]
> You could either edit the file manually in your installation or keep using Xcode 12.4 or earlier

This means edit the file on every build? isn't there a file on unity that could be modified to avoid this ?
Thanks

**Comment by paulb777** [comment]
Edit the file after any `pod install` or `pod update`.  You may want ask the Unity question in a different forum - there may not be too much Unity expertise here.

**Comment by pistoleta** [comment]
> Edit the file after any `pod install` or `pod update`. You may want ask the Unity question in a different forum - there may not be too much Unity expertise here.

ooh right, I thought this was from the firebase for unity sdk , thanks

**Pull request merged**
