### PR TITLE
WIP: RTDB swift combine

### PR DESCRIPTION
**Pull request by mortenbekditlevsen**
This is basically a merge of two other works-in-progress: #6976 and #6568

Just so that we have a place to start experimenting with RTDB/Combine.

### CODE REVIEW

**Comment by peterfriese** [comment]
Hi Morten,

Thanks for building this!

Just a heads-up: [peterfriese/combine-main](https://github.com/firebase/firebase-ios-sdk/tree/peterfriese/combine-main) is my working branch. I am happy for you to use it to work against until we've merged it into [combine-main](https://github.com/firebase/firebase-ios-sdk/tree/combine-main).

Once we've done this, I will also make sure to catch up [combine-main](https://github.com/firebase/firebase-ios-sdk/tree/combine-main) to master, which should hopefully remove the ML-related noise in your PR.

If possible, can you provide a test for your publisher(s)?

Cheers,
Peter

**Comment by mortenbekditlevsen** [comment]
Hi Peter,
Thanks a lot - I know that I'll have to change the PR target once your PR is merged, but I thought that your branch was a good starting place for my experiments. 😊

I am also awaiting further review of the FirebaseDatabaseSwift target, so this is a WIP on top of two other WIPs. 😊

I'd like to add tests too. I need to figure out how to create testable instances of DatabaseReference, but it appears that I can get inspiration in the obj-c tests for FirebaseDatabase.

I'll definitely add Publishers too for database subscriptions. I'll follow your lead from the Auth extension and use existing Publisher building blocks rather than trying to roll my own. 😊

**Comment by peterfriese** [comment]
> Thanks a lot - I know that I'll have to change the PR target once your PR is merged, but I thought that your branch was a good starting place for my experiments. 😊

Agree!

> I'd like to add tests too. I need to figure out how to create testable instances of DatabaseReference, but it appears that I can get inspiration in the obj-c tests for FirebaseDatabase.

That's what I've ben doing. I'm quite happy with the test for Anonymous Auth I wrote just now (see 2214cd0ae3f330797a08fd0cfb9c28dabe71a92a ) - much cleaner than the ones I wrote before (I'll update the code to match): it essentially is a re-write of https://github.com/firebase/firebase-ios-sdk/blob/fa5ff62138a251dd45af1c927d34591a97539815/FirebaseAuth/Tests/Unit/FIRAuthTests.m#L1385

> I'll definitely add Publishers too for database subscriptions. I'll follow your lead from the Auth extension and use existing Publisher building blocks rather than trying to roll my own. 😊

After having the tried the other approach, I do believe that using Futures and `PassthroughSubject` is probably the right thing to do. Following the "don't write your own publishers if you can avoid it" mantra, and "Wrapping existing asynchronous processes with Futures" in Donny Wals' book.

**Comment by mortenbekditlevsen** [comment]
Hi @peterfriese ,
I have some trouble building and running the tests you made for Auth. I’d like to copy some of the concepts (importing header files I need for testing into the bridging module, etc), but I haven’t been able to make it work.
I looked at your PR and the CI steps to see how they are built, but I can’t seem to find them.
Are they being run on CI? If so, where might I look?
Do you run them locally be opening the project as a swift package? If so, which target do you use?
Sincerely,
/morten

**Comment by peterfriese** [comment]
Hi @mortenbekditlevsen -

here are the steps to run the tests I wrote:

```bash
$ gh repo clone firebase/firebase-ios-sdk
$ cd firebase-ios-sdk
$ gh pr checkout 6976
$ pod gen FirebaseCombineSwift.podspec --local-sources=./ --auto-open --platforms=ios
```

This will generate a dummy project and open it in Xcode.

- Make a copy of `FirebaseCombineSwift/Tests/Unit/CredentialsTemplate.swift`, naming it `Credentials.swift`
- Add this file to the project (easiest by selecting _Add Files to "Pods"_ from the context menu of the `FirebaseCombineSwift/Tests/Unit` folder in Xcode
- You'll need to provide some of these values (take them from a `GoogleService-Info.plist` file)
- Select the `FirebaseComboneSwift-Unit-unit` scheme
- Press `CMD + U` to run the tests

These tests currently don't run on CI - this is something I'll have to look into.

LMK if this helps.

**Comment by mortenbekditlevsen** [comment]
Hi @peterfriese ,
Thank you very much - it did help me getting your tests building and running.
I continued experimentation in that fashion by adding private headers for FirebaseDatabase so that I can mock `DatabaseReference` and the like.
I ran in to an issue, however. I need to import "FirebaseDatabase/Sources/Api/Private/FIRDatabaseReference_Private.h" in order to get access to a private initializer. But when I do that, then the test module itself defines the `DatabaseReference` type - and it is no longer the same as the version imported from the "FirebaseDatabase" module...

My next issue is that I can't find any unit tests for FirebaseDatabase that tests the 'old' (Objective-C) observing of values from a `DatabaseReference`. I would like to copy something similar to that in order to test my publishers.

**Comment by peterfriese** [comment]
Sorry this got closed - I was cleaning up and deleted my personal working branch.

Please rebase this work onto `combine-main`.

**Comment by mortenbekditlevsen** [comment]
No worries - it's now resurrected as #7544. :-) 
And it's still just a playground - mainly for myself. Once #6568 is done, I'll get started on the actual PR.

**Comment by peterfriese** [comment]
This is continued in #7544.

**Pull request closed without merging**
