### PR TITLE
Add Swift API for recording errors with userInfo parameters

### PR DESCRIPTION
**Pull request by sergiocampama**
https://github.com/firebase/firebase-ios-sdk/discussions/8815

This is an additive API change which should have no effect on existing clients.

### CODE REVIEW

**Comment by sergiocampama** [comment]
@googlebot I signed it!

**Comment by sergiocampama** [comment]
updating the pr, but highly disappointed on the lack of communications from the firebase team, especially on cases where the work is provided for you

**Comment by morganchen12** [comment]
Hey Sergio, apologies for the slow response. We'll take a look. Thanks for making this PR!

**Comment by samedson** [comment]
@sergiocampama we are able to approve this API now. I'm just going to make a small addition to the comment and then submit the change.

**Comment by sergiocampama** [comment]
@samedson thanks! I've updated the PR with the comments change and made sure to run the style script for the check to pass.

**Review by samedson — APPROVED** [review]
Awesome - thank you for contributing!

**Comment by elenadoty** [comment]
Hi @sergiocampama - I'm working on Google Open Source Peer Bonus nominations and would like to recognize your contribution to improving Crashlytics. I couldn't find an email address for you, so if you're interested please email it to elenadoty at google.com and I'll make the nomination.

**Pull request merged**
