### PR TITLE
Parallelize the Travis run using build stages

### PR DESCRIPTION
**Pull request by wilhuff**
Not yet ready for review

    https://docs.travis-ci.com/user/build-stages/
    
This will run source checks first (style, lint) and then if all pass,
kick off all platforms and builds in parallel.

### CODE REVIEW

**Comment by paulb777** [comment]
Looking good! What's left?

**Comment by wilhuff** [comment]
This doesn't actually work yet.

See https://travis-ci.org/firebase/firebase-ios-sdk/jobs/350427153
```
WARNING: Using Objective-C testing without specifying a scheme and either a workspace or a project is deprecated.
0.01s  Check out our documentation for more information: http://about.travis-ci.org/docs/user/languages/objective-c/
```
So far we're splitting things correctly but failing to run the `before_install` or `script` bits for any of the stages. I'm trying to figure out why but this day is getting away from me :-(.

**Comment by paulb777** [comment]
Ah, I thought it was short because no files changed and build was skipped.

Perhaps, need to add an XCWORKSPACE setting like https://stackoverflow.com/a/19652397/556617?  Although I don't understand why the -workspace option to the xcodebuild command wouldn't be sufficient.

**Comment by wilhuff** [comment]
Yeah, we'd see at least that it ran the command (and that it took no time and produced no output).

**Comment by wilhuff** [comment]
Yeah, I think this is enough to avoid build timeouts and so it's worthwhile even on its own.

**Pull request merged**
