### PR TITLE
Use a separate class to wrap the user queue instead of FSTDispatchQueue

### PR DESCRIPTION
**Pull request by var-const**

### CODE REVIEW

**Comment by wilhuff** [comment]
Given the existence of a trivial workaround for the issue motivating this change it seems as if we could just write the equivalent of the `FSTUserQueue` in C++ directly, no?

**Comment by var-const** [comment]
@wilhuff If you're okay with the general idea (introduce a separate class, even if it's just a wrapper for `dispatch_async`, and pass it around to applicable objects), then sure, I can rewrite this in C++.

**Comment by var-const** [comment]
By the way, I'm a little concerned that `if_changed` apparently decided this PR doesn't deserve a test run (see Travis run [here](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/367358331)).

**Comment by wilhuff** [comment]
AFAICT this object is largely just the low-level portable interface to dispatch_async that we discussed adding as the underlying primitive we would build the async queue on.

**Comment by wilhuff** [comment]
I have a fix forthcoming for travis in #1117.

**Pull request closed without merging**
