### PR TITLE
Update binary install instructions for disabling AdId

### LINKED ISSUE #9609: Feature: Support dynamic targets
### Feature proposal

* Firebase Component: **FirebaseCrashlytics** (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Can we support dynamic targets for Crashlytcs / Analytics by adding an additional library target in `Package.swift` such as this?

```
.library(
      name: "FirebaseCrashlyticsDynamic",
      type: .dynamic,
      targets: ["FirebaseCrashlytics"]
    ),
```

This way we'll be able to ship a single dynamic framework for all the targets of the app that wish to link with Crashlytics (if crash reporting will still work when it's loaded dynamically?) This would considerably shrink the size of our app bundle as currently each target that links with crashlytics, does so statically, resulting in a much larger overall .app bundle.

Clients could then wish to link against `FirebaseCrashlyticsDynamic` instead. 

Most Swift Packages support dynamic targets now, such as RxSwift: https://github.com/ReactiveX/RxSwift/blob/main/Package.swift

### PR DESCRIPTION
**Pull request by paulb777**
Fix #9609 

#no-changelog

### CODE REVIEW

**Comment by guidedways** [comment]
@paulb777 I find this instruction confusing:

```
*Do not add the Firebase frameworks to the "Embed Frameworks" Xcode build
   phase. The Firebase frameworks are not embedded dynamic frameworks, but are
   [static frameworks](https://www.raywenderlich.com/65964/create-a-framework-for-ios)
   which cannot be embedded into your application's bundle.*
```

To me this sounded like "do not embed any of the Firebase frameworks the instructions asked us to copy" - and so the app crashed at runtime since we had marked "GoogleUtilities" with "do not embed". I think it should clearly mention that only the `FirebaseXXXXXX.xcframeworks` are not to be embedded.

**Comment by paulb777** [comment]
@guidedways Sorry, I'm not following. The GoogleUtilities.xcframework in the FirebaseAnalytics directory should have the same characteristics as the `FirebaseXXXXXX.xcframeworks`

**Comment by guidedways** [comment]
@paulb777 Our app seems to crash:

```
8.14.0 - [Firebase/Analytics][I-ACS030000] Exception on worker queue. Block ID=APMMeasurement:1651. Exception: -[APMDatabase insertBundle:isRealtime:error:]: +[NSData gul_dataByGzippingData:error:]: unrecognized selector sent to class 0x210eee4e8
```

We've got two targets in our macOS app. I added all the xcframeworks and then set them to "Do Not embed". The app crashed a few seconds into the launch with:

`+[NSData gul_dataByGzippingData:error:]: unrecognized selector sent to class 0x210eee4e8`

I then set GoogleUtilities.xcframework to "Embed & Sign", this prevented the crash but now our plugin is crashing. Even with "Embed & Sign" it seems to be constantly crashing with the error above. Strangely it seems it can't find GoogleUtilities at runtime.

**Comment by guidedways** [comment]
I'm seeing other messages on the console:

```
+[FBLPromise onQueue:do:]: unrecognized selector sent to class 0x100fc39f8
```

So far we've followed the instructions to the T, I'll go over these again to see if we've missed something. The app compiles and launches but crashes at runtime with missing symbols from frameworks / libraries used by Firebase.

**Comment by paulb777** [comment]
Unrecognized selector errors can happen if you miss the instruction to add `-ObjC` to the linker options.

**Comment by guidedways** [comment]
@paulb777 I could have sworn I did just that - in fact we had that set already, but now that I checked a second time, it wasn't set! I'm so sorry... 😅 Thank you for your help!

**Review by ryanwilson — APPROVED** [review]

**Pull request merged**
