### PR TITLE
Upgrade ABSL and GRPC for Firestore

### PR DESCRIPTION
**Pull request by wu-hui**

### CODE REVIEW

**Comment by ryanwilson** [comment]
Does this need an accompanying change to SwiftPM as well?

**Comment by wu-hui** [comment]
> Does this need an accompanying change to SwiftPM as well?

Yes! I have not yet figured out how to do this..

**Comment by ryanwilson** [comment]
> > Does this need an accompanying change to SwiftPM as well?
> 
> Yes! I have not yet figured out how to do this..

cc @paulb777 we'll need to update these two repos: https://github.com/firebase/abseil-cpp-SwiftPM and https://github.com/firebase/grpc-SwiftPM although I'm fairly certain we've squashed history for each of them. Paul, are there instructions written down anywhere for this?

**Comment by paulb777** [comment]
@ryanwilson The initial implementation was a one-off and a sustainable process needs to be developed. I've discussed with @schmidt-sebastian and @var-const and can resync when the Firestore team is ready.

**Comment by paulb777** [comment]
Closing since this task was done in later PRs. Reopen if still needed.

**Pull request closed without merging**
