### PR TITLE
Patch nanopb CMakeLists.txt to look for python 3.7 instead of python 2.7

### PR DESCRIPTION
**Pull request by dconeybe**
This fixes the following cmake build error on machines that lack a python 2.7 interpreter (e.g. a fresh macbook):

```
CMake Error at Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at
  least version "2.7")
Call Stack (most recent call first):
  Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  Cellar/cmake/3.23.2/share/cmake/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  build/external/src/nanopb/CMakeLists.txt:44 (find_package)
```

when the following command is run:

```
cmake -S . -B build
```

#no-changelog

### CODE REVIEW

**Review by cherylEnkidu — APPROVED** [review]
Thank you for your work!

**Review by ehsannas — COMMENTED** [review]
Drive-by review: newer nanopb versions don't rely on python 2.7. Is there a reason we're not upgrading to a newer nanopb version?

**Comment by paulb777** [comment]
Drive-by answer: Firestore's nanopb version needs to match the rest of Firebase and since Firebase supports 1P clients needs to be compatible with the rest of Google. Updating Firestore's nanopb version requires updating all Google nanopb clients.

**Comment by ehsannas** [comment]
I see. Thanks @paulb777

**Pull request merged**
