### PR TITLE
Don't init FIRAuthStoredUserManager with a nil keychainServiceName.

### PR DESCRIPTION
**Pull request by mikelehen**
I DON'T KNOW IF THIS IS THE RIGHT FIX, but FYI it resolves the crash I mentioned...

### CODE REVIEW

**Comment by mikelehen** [comment]
FYI- There are 3 travis failures...  I'm trying to figure out if I actually caused them:
```
Failing tests:
	-[FIRMessagingRemoteNotificationsProxyTest testIncompleteAppDelegateRemoteNotificationWithFetchHandlerMethod]
	-[FIRMessagingRemoteNotificationsProxyTest testSwizzledAppDelegateRemoteNotificationMethods]
	-[FIRMessagingRemoteNotificationsProxyTest testSwizzledIncompleteAppDelegateRemoteNotificationMethod]
```

**Comment by paulb777** [comment]
https://github.com/firebase/firebase-ios-sdk/issues/2724

**Comment by paulb777** [comment]
The Messaging failures are not from this PR, but there is an Auth linkage failure in the tvOS tests that does not have a cause identified that I know of.

**Comment by mikelehen** [comment]
@paulb777 Ahh, excellent.  Thanks Paul!

**Comment by renkelvin** [comment]
@patm1987 Which is that Auth failure?

**Comment by paulb777** [comment]
@renkelvin 
❌  Undefined symbols for architecture x86_64
> Pods-InstanceID_Example_tvOS-dummy.o
> Pods_InstanceID_Example_tvOS_vers.o

See https://travis-ci.org/firebase/firebase-ios-sdk/jobs/515807643

**Comment by renkelvin** [comment]
@paulb777 Thanks! taking a look.

**Comment by paulb777** [comment]
Seems fixed on master now. Perhaps was the same bad revert that led to the Messaging test failures.

**Pull request merged**
