### PR TITLE
[Release] Update versions for Release 10.18.0

### PR DESCRIPTION
**Pull request by ncooke3**
Screenshot 2023-10-31 at 9 39 36 PM

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]
LGTM on acceptable CI

**Comment by TokenPayId** [comment]
> 1 Warning
> ⚠️	Did you forget to add a changelog entry? (Add #no-changelog to the PR description to silence this warning.)
> Generated by 🚫 [Danger](https://danger.systems/)

**Comment by ncooke3** [comment]
I see they affected the nightly zip as well. The error though seems to be Xcode related:
```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:latest, name:iPhone 15 }

	The requested device could not be found because no available devices matched the request.
```

**Comment by paulb777** [comment]
No, but they're almost certainly a regression from #11983, so shouldn't block this PR. I'll investigate today.

**Pull request merged**
