### PR TITLE
Fix output of proto_generator.py

### PR DESCRIPTION
**Pull request by samedson**
I'm planning on combining these files soon

### Before

```
b'Options file not found: clientanalytics.options\nOptions for clientanalytics.proto: \nOptions for NetworkConnectionInfo: \nOptions for NetworkConnectionInfo.network_type: \nOptions for NetworkConnectionInfo.mobile_subtype: \nOptions for NetworkConnectionInfo.NetworkType: \nOptions for NetworkConnectionInfo.MobileSubtype: \nReading options from /Users/samedson/Firebase/firebase-ios-sdk/FirebaseSessions/ProtoSupport/Protos/sessions.options\nOptions for sessions.proto: proto3: true\n\nOptions for firebase.appquality.sessions.EventType: proto3: true\n\nOptions for firebase.appquality.sessions.DataCollectionState: proto3: true\n\nOptions for firebase.appquality.sessions.OsName: proto3: true\n\nOptions for firebase.appquality.sessions.SessionEvent: proto3: true\n\nOptions for firebase.appquality.sessions.SessionEvent.event_type: proto3: true\n\nOptions for firebase.appquality.sessions.SessionEvent.session_data: proto3: true\n\nOptions for firebase.appquality.sessions.SessionEvent.application_info: proto3: true\n\nOptions for firebase.appquality.sessions.SessionInfo: proto3: true\n\nOptions for fi
```

### After

```
Options file not found: clientanalytics.options
Options for clientanalytics.proto:
Options for NetworkConnectionInfo:
Options for NetworkConnectionInfo.network_type:
Options for NetworkConnectionInfo.mobile_subtype:
Options for NetworkConnectionInfo.NetworkType:
Options for NetworkConnectionInfo.MobileSubtype:
Reading options from /Users/samedson/Firebase/firebase-ios-sdk/FirebaseSessions/ProtoSupport/Protos/sessions.options
Options for sessions.proto: proto3: true

Options for firebase.appquality.sessions.EventType: proto3: true

Options for firebase.appquality.sessions.DataCollectionState: proto3: true

Options for firebase.appquality.sessions.OsName: proto3: true

Options for firebase.appquality.sessions.SessionEvent: proto3: true

Options for firebase.appquality.sessions.SessionEvent.event_type: proto3: true

Options for firebase.appquality.sessions.SessionEvent.session_data: proto3: true

Options for firebase.appquality.sessions.SessionEvent.application_info: proto3: true
```

### CODE REVIEW

**Comment by paulb777** [comment]
Consider also FirebaseInAppMessaging/ProtoSupport/nanopb_proto_generator.py and Firestore/Protos/nanopb_cpp_generator.py

**Comment by samedson** [comment]
Oh awesome I totally missed those

**Comment by samedson** [comment]
Might do https://github.com/firebase/firebase-ios-sdk/pull/10439 instead if I can get it working

**Comment by samedson** [comment]
Closing in favor of https://github.com/firebase/firebase-ios-sdk/pull/10439

That PR handles FIAM, but not Firestore

**Pull request closed without merging**
