### PR TITLE
Update versions for Release 9.6.0

### PR DESCRIPTION
**Pull request by andrewheard**
Updated version numbers in preparation for the next Firebase release (9.6.0).

#no-changelog

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]
LGTM on green

**Comment by ncooke3** [comment]
Regarding some of the failures, the `remoteconfig / watchOS` one looks to be a flake of some kind. I've seen it appear in the nightlies.

The `appcheck / macos` is related to GoogleUtilities 7.8.0. The AppCheck tests need to be disabled on macOS. I will send a PR but feel free to not let that failure block you!

**Comment by ncooke3** [comment]
`mlmodeldownloader / macos` is related to keychain fix as well. I will disable offending tests on macOS. MLModelDownloader depends on Installations.

**Comment by ncooke3** [comment]
Two of the three failures have been addressed in merged PRs.

The remaining watchOS x remote config failure looks like a flake. Kicked off a deflake: https://github.com/firebase/firebase-ios-sdk/actions/runs/2936339297

**Comment by ncooke3** [comment]
> Two of the three failures have been addressed in merged PRs.
> 
> The remaining watchOS x remote config failure looks like a flake. Kicked off a deflake: https://github.com/firebase/firebase-ios-sdk/actions/runs/2936339297

Ok so the watchOS failure was indeed an integration flake.

@andrewheard, this PR is now unblocked.

**Review by ncooke3 — APPROVED** [review]

**Review by ncooke3 — APPROVED** [review]
LGTM

**Pull request merged**
