### PR TITLE
[DNM] Smoke test everything following staging of GULs 7.13.2

### PR DESCRIPTION
**Pull request by ncooke3**
#no-changelog

### CODE REVIEW

**Comment by ncooke3** [comment]
There are a couple failures, but nothing concerning imo. There was a Crashlytics x Catalyst failure of `-[FIRCLSUserDefaults testSynchronize]` which looked suspicious, but Crashlytics doesn't depend (directly/transitively on the staged GULs so it was unrelated).

**Comment by paulb777** [comment]
This one looks strange https://github.com/firebase/firebase-ios-sdk/actions/runs/8807907835/job/24175997864 - restarted it

**Comment by ncooke3** [comment]
> This one looks strange https://github.com/firebase/firebase-ios-sdk/actions/runs/8807907835/job/24175997864 - restarted it

Agreed. Though it did pass in the nightly: https://github.com/firebase/firebase-ios-sdk/actions/runs/8813941317

**Comment by paulb777** [comment]
And retry succeeded. In any case, the issue looks related to default GHA Xcode versions changing, so shouldn't be a blocker  here.

**Pull request closed without merging**
