### PR TITLE
Escaping  url string from dynamic link parameter (issue 6786)

### PR DESCRIPTION
**Pull request by cjimenezpacho**
More info here: https://github.com/firebase/firebase-ios-sdk/issues/6786

### CODE REVIEW

**Comment by paulb777** [comment]
@cjimenezpacho Thanks for the PR! Please resolve the unit test failure and see [here](https://github.com/firebase/firebase-ios-sdk#code-formatting) to run clang-format to fix the formatting.

**Review by 86Whiskey — APPROVED** [review]

**Comment by eldhosembabu** [comment]
This change looks good to me. Could you please add some tests for the same?

**Comment by cjimenezpacho** [comment]
@eldhosembabu yes, sorry, I have been very busy, as soon as I have time I will add tests. Thank you for the feedback :)

**Comment by eldhosembabu** [comment]
> you

thanks

**Comment by paulb777** [comment]
@eldhosembabu What is the next step on this PR? Can your team add the tests and merge?

**Comment by eldhosembabu** [comment]
> @eldhosembabu What is the next step on this PR? Can your team add the tests and merge?

Hi @paulb777 

I’ve tried creating a new PR with the changes copied and unit tests, but I could see chance for backward compatibility issues here since we are doing string escaping using encoding for the deep link url which is getting passed back to the developer. So the existing developers who expects the regular url as of now will be given encoded url which might break their code.

I think its better not to do this fix at SDK level (until we find a better solution), instead as a workaround the developer can encode the URL at the application level before passing it into the SDK as mentioned here: https://github.com/firebase/firebase-ios-sdk/issues/6786#issuecomment-1301884080

**Comment by paulb777** [comment]
thanks for investigating @eldhosembabu. I'll close based on your conclusions.

**Pull request closed without merging**
