### PR TITLE
[API Diff Report] Add mixed-language module support 

### PR DESCRIPTION
**Pull request by sunmou99**
Fix issue "No Green Diff" in this report: https://github.com/firebase/firebase-ios-sdk/pull/11720#issuecomment-1690478267

This is because, when detect changed modules, we only considered source code files and excluded ".podspec" files. 
Fix the issue by 
1. adding ".podspec" files detection. 
2. adding mixed-language module support as `FirebaseRemoteConfig` module now build both objc and swift code.

Also, formatted the code.

### API Changes

No API changes

### CODE REVIEW

**Review by ncooke3 — APPROVED** [review]

**Comment by ncooke3** [comment]
@sunmou99, where is the green diff in https://github.com/firebase/firebase-ios-sdk/pull/11743#issuecomment-1698069274?

**Comment by sunmou99** [comment]
> @sunmou99, where is the green diff in [#11743 (comment)](https://github.com/firebase/firebase-ios-sdk/pull/11743#issuecomment-1698069274)?

One more fix is required. I won't merge the PR until I see a green diff.

**Comment by paulb777** [comment]
Please close, merge, or comment. We plan to close stale PRs on November 28, 2023.

**Comment by sunmou99** [comment]
> Please close, merge, or comment. We plan to close stale PRs on November 28, 2023.

Thanks for the reminder. I have a quick questions: What's the plan for mixed-language modules? i.e. What are the modules that will have mixed-language codes? And when? Thanks!

**Comment by paulb777** [comment]
We released mixed-language modules in 10.17.0. @ncooke3 Please clarify.

**Comment by ncooke3** [comment]
> We released mixed-language modules in 10.17.0. @ncooke3 Please clarify.

Hi @sunmou99, the following module contain mixed-language API and were released in 10.17.0

- Firestore
- Remote Config
- In App Messaging
- Analytics
- Database

The packaging strategy varies per product, but I can give more details regarding each one.

**Comment by sunmou99** [comment]
> > We released mixed-language modules in 10.17.0. @ncooke3 Please clarify.
> 
> Hi @sunmou99, the following module contain mixed-language API and were released in 10.17.0
> 
> * Firestore
> * Remote Config
> * In App Messaging
> * Analytics
> * Database
> 
> The packaging strategy varies per product, but I can give more details regarding each one.

Thanks. I will share with you the next step at the end of this week. And I will merge/close this PR before November 28, 2023.

**Comment by sunmou99** [comment]
Close it for now. Will have a design first, and then test on mixed-language modules during Dec. 2023.

**Pull request closed without merging**
