### PR TITLE
Add multiple workflows for coverage tests.

### PR DESCRIPTION
**Pull request by granluo**

### CODE REVIEW

**Comment by paulb777** [comment]
Why is only Storage shown in the report?

Why are there two reports for Storage?

The first report seems to be measuring coverage of the unit test sources instead of the library source coverage.

**Comment by granluo** [comment]
> Why is only Storage shown in the report?
> 
> Why are there two reports for Storage?
> 
> The first report seems to be measuring coverage of the unit test sources instead of the library source coverage.

That is because the json file containing path under the script directory, [code_coverage_file_list.json](https://github.com/firebase/firebase-ios-sdk/pull/7470/files?file-filters%5B%5D=.json#diff-9c1ae229ad74af4f23ec5a48b047e66e74497f77af2924c0eabe614306b42138R127).
I saw the [storage.yml](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/storage.yml#L9) workflow had this path.

Will remove the path in the json file.

**Comment by paulb777** [comment]
Makes sense. I think that answers the first question. What about the other two?

**Comment by granluo** [comment]
> Makes sense. I think that answers the first question. What about the other two?

`FirebaseStorage-Unit-unit.xctest` is the coverage for unit test.  Should this one be removed?

**Comment by paulb777** [comment]
I don't think we need the coverage info for the test sources - only for the library sources.

**Review by paulb777 — APPROVED** [review]
I'm not sure it's quite right yet, but fine to merge and do additional fixes as we evaluate the reports.

**Comment by granluo** [comment]
Will test the tool in the pr before merge.

**Pull request merged**
