### PR TITLE
Add platform specific macros make it compatible with google3

### PR DESCRIPTION
**Pull request by renkelvin**
Add platform specific macros make it compatible with google3

### CODE REVIEW

**Comment by renkelvin** [comment]
Running ./scripts/check.sh results in changing the styles of other 4 fiels. Any ideas why it happens?
see https://github.com/firebase/firebase-ios-sdk/pull/4500/commits/86d8d57ef068601db3e90d028f32fa66d05affcb

**Comment by paulb777** [comment]
Do you have the right versions? https://github.com/firebase/firebase-ios-sdk#code-formatting

**Comment by renkelvin** [comment]
Yeah, swiftformat 0.40.14 clang-format 9.0.0

**Comment by paulb777** [comment]
The formatters change without changing the version. The timestamps need to match.

**Comment by renkelvin** [comment]
Is there a way to see the formatting issues? I doubt it's not because of the style since linter test for Auth is not enabled yet.

**Comment by paulb777** [comment]
I suspect the issue is related to running on a branch from August.  I suggest merging or rebasing to latest master.

```
 $ git log
commit 76405d60554570bc2f6b631d3c6c99d525f68835 (HEAD -> platform-compile, origin/platform-compile)
Author: Chuan Ren <renkelvin@gmail.com>
Date:   Fri Dec 13 16:21:09 2019 -0800

    Revert "style fix"

    This reverts commit 86d8d57ef068601db3e90d028f32fa66d05affcb.

commit 86d8d57ef068601db3e90d028f32fa66d05affcb
Author: Chuan Ren <renkelvin@gmail.com>
Date:   Fri Dec 13 16:17:20 2019 -0800

    style fix

commit 927ada7b7e077138e254436e0a7003605c9e8b1e
Author: Chuan Ren <renkelvin@gmail.com>
Date:   Fri Dec 13 14:40:29 2019 -0800

    Add platform specific macros

commit d70c873654a3dbfd5171fb2fb60ddb6580b5d974
Author: Paul Beusterien <paulbeusterien@google.com>
Date:   Wed Aug 21 15:41:58 2019 -0700

    Release 6.7.0 (#3646)

```

**Comment by renkelvin** [comment]
Submitted in https://github.com/firebase/firebase-ios-sdk/pull/4501

**Pull request closed without merging**
