### PR TITLE
[Infra] Update Package.swift for Firebase 11

### PR DESCRIPTION
**Pull request by ncooke3**

### CODE REVIEW

**Comment by ncooke3** [comment]
investigating one of the failures:
```
 ./scripts/build.sh objc-import-test macOS spm

Testing failed:
	xctest (57642) encountered an error (Failed to load the test bundle. (Underlying Error: The bundle “objc-import-test” couldn’t be loaded. The bundle couldn’t be loaded. Try reinstalling the bundle. dlopen(/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/objc-import-test, 0x0109): Library not loaded: @rpath/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop
  Referenced from: <E8432472-463F-30FF-A84E-F48A84A05863> /Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/FirebaseFirestoreInternal.framework/Versions/A/FirebaseFirestoreInternal
  Reason: tried: '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/SharedFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Xcode/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/FirebaseFirestoreInternal.framework/Versions/A/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/../Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/../Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/PrivateFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file)))
```

**Comment by ncooke3** [comment]
> investigating one of the failures:
> 
> ```
>  ./scripts/build.sh objc-import-test macOS spm
> 
> Testing failed:
> 	xctest (57642) encountered an error (Failed to load the test bundle. (Underlying Error: The bundle “objc-import-test” couldn’t be loaded. The bundle couldn’t be loaded. Try reinstalling the bundle. dlopen(/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/objc-import-test, 0x0109): Library not loaded: @rpath/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop
>   Referenced from: <E8432472-463F-30FF-A84E-F48A84A05863> /Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/FirebaseFirestoreInternal.framework/Versions/A/FirebaseFirestoreInternal
>   Reason: tried: '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/SharedFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Xcode/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/FirebaseFirestoreInternal.framework/Versions/A/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/../Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/../Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/PrivateFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file)))
> ```

Swapping the `test` action for `build-for-testing` got it to work.

**Comment by ncooke3** [comment]
> > investigating one of the failures:
> > ```
> >  ./scripts/build.sh objc-import-test macOS spm
> > 
> > Testing failed:
> > 	xctest (57642) encountered an error (Failed to load the test bundle. (Underlying Error: The bundle “objc-import-test” couldn’t be loaded. The bundle couldn’t be loaded. Try reinstalling the bundle. dlopen(/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/objc-import-test, 0x0109): Library not loaded: @rpath/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop
> >   Referenced from: <E8432472-463F-30FF-A84E-F48A84A05863> /Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/FirebaseFirestoreInternal.framework/Versions/A/FirebaseFirestoreInternal
> >   Reason: tried: '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/SharedFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Xcode/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/FirebaseFirestoreInternal.framework/Versions/A/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/../Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/PackageFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Build/Products/Debug/objc-import-test.xctest/Contents/MacOS/../Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/PrivateFrameworks/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/FirebaseAppCheckInterop.framework/Versions/A/FirebaseAppCheckInterop' (no such file)))
> > ```
> 
> Swapping the `test` action for `build-for-testing` got it to work.

Addressable by #13303

**Comment by ncooke3** [comment]
Another failure similar to the objc-import-test failure:
https://github.com/firebase/firebase-ios-sdk/actions/runs/9981192175/job/27587471962?pr=13301#step:7:182

**Comment by paulb777** [comment]
Sorry I saw that in the review and thought I was missing something about how the objc tests would need to change but not the swift ones.

**Comment by ncooke3** [comment]
idea– perhaps the issue is from testing a test target that does not have a test case.

**Comment by ncooke3** [comment]
https://github.com/firebase/firebase-ios-sdk/actions/runs/9993711581/job/27621729698?pr=13309#step:8:7402

**Comment by ncooke3** [comment]
hint:   
```
Referenced from: <D3A695DB-7FCC-3252-A994-431966D3BBB2> /Users/runner/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-dkhlbuenaibuowhffbszhgvmwpqa/Build/Products/Debug-iphonesimulator/FirebaseFirestoreInternal.framework/FirebaseFirestoreInternal
```

**Comment by ncooke3** [comment]
Latest failure is reproducible by opening Package.swift on this branch and testing the `swift-test` scheme. Currently investigating if this failure is something we can ignore or if it could surface for clients.

**Comment by ncooke3** [comment]
This may be more serious than I thought.

Also reproducible when:
- close out of firebase package window in Xcode
- xed IntegrationTesting/ClientApp/ClientApp.xcodeproj
- wait for package dependency to resolve
- **run** on iOS
- app crashes due to missing dylibs

**Comment by ncooke3** [comment]
Narrowing down the issue: running `otool -L` on Analytics binary will show that it's looking for FirebaseCore.framework but SPM/Xcode does not seem smart enough to build FirebaseCore as a dylib _because_ it's a dependency of Analytics

**Comment by ncooke3** [comment]
It's likely that the wrapper targets we use for the binary targets are no longer necessary when using dylibs. I'm going to try:
- removing the wrapper targets
- manually setting our libary targets to have type dynamic

**Pull request closed without merging**
