### PR TITLE
Remove references to UIWebView from DynamicLinks to comply with Apple…

### PR DESCRIPTION
**Pull request by dloic**
Linked to https://github.com/firebase/firebase-ios-sdk/issues/3722

### CODE REVIEW

**Comment by paulb777** [comment]
cc: @dmandar

**Comment by cipriancaba** [comment]
Hi @paulb777 .. Can we please have a release that includes this commit? Cheers

**Comment by paulb777** [comment]
We plan to release M55 (Firebase 6.8.0) later this week.

**Comment by yadits** [comment]
I update to release 6.8.0 and I still get the error from App Store Connect of UIWebView. I searched the code and the only reference I get is to UIWebViewDelegate in Firebase DynamicLinks. Do you think this is the issue?

**Comment by paulb777** [comment]
Hmm, it's possible - although surprising that the original reporter didn't see that. Perhaps Apple just recently changed the criteria to include the delegate class?

In any case, we definitely don't need those references and I made #3799 to remove them.

**Comment by SistemasIntegrales** [comment]
Hi, just wanted to check the status. I've tried to update the packages for an app I made in Unity and tried to upload to App Store. But even downloading the most recent packages of Unity Firebase I still get the email from apple that the references to UIWebView needs to be removed.

**Comment by paulb777** [comment]
@SistemasIntegrales There is some amount of lag between fixes in the iOS SDK and integration into the Unity SDK.  Unity specific questions should be routed to https://github.com/firebase/quickstart-unity

**Comment by matte5031** [comment]
I'm confused, I got dynamic links plugin and I get this warning when uploading to itunes connect. Do I need to change to the master branch or what do I need to do to get this fix (I'm in the stable branch atm)? Thanks

**Pull request merged**
