### PR TITLE
feature: use app name instance in firebase messaging

### PR DESCRIPTION
**Pull request by aspicas**
### Discussion

* Use a different firebase instance than the default
* https://github.com/firebase/firebase-ios-sdk/issues/8968

### Testing

  * TODO

### API Changes

```Swift
Messaging.messaging(appName: "InstancedName")
```

### CODE REVIEW

**Comment by paulb777** [comment]
Thanks for the PR and sorry about the slow response. 

We're not likely to move too quickly on this one since there are back-end implications of multiple-app support that we're not ready to address.

**Comment by Bolik** [comment]
> Thanks for the PR and sorry about the slow response.
> 
> We're not likely to move too quickly on this one since there are back-end implications of multiple-app support that we're not ready to address.

Hi, is there any progress on this issue ? May I help with something?

**Comment by charlotteliang** [comment]
In the meantime you can upvote the feature request  https://github.com/firebase/firebase-ios-sdk/issues/8968 to help the team prioritize.

**Comment by ryanwilson** [comment]
Thanks @aspicas for the contribution. I'm sorry that we aren't able to merge this right now, but we'll keep tracking it in #8968 and revisit this PR if we move forward to ensure you get credit for it. I'll close it for now since we don't have active plans to merge it. Thanks again and feel free to follow up with any further conversation on this PR or the feature request!

**Pull request closed without merging**
