### PR TITLE
Placeholder Analytics 11.0.0

### PR DESCRIPTION
**Pull request by htcgh**
Placeholder Analytics 11.0.0 #no-changelog

### CODE REVIEW

**Comment by ncooke3** [comment]
I'll wait to see some results from the SPM CI. Then, I'll merge, re-tag, and stage.

**Review by ncooke3 — APPROVED** [review]
thanks!

**Comment by ncooke3** [comment]
investigating spm failures locally...

**Comment by ncooke3** [comment]
Latest commit to address these failures: https://github.com/firebase/firebase-ios-sdk/actions/runs/9913363297/job/27390217206

**Review by paulb777 — APPROVED** [review]
Still more to go - but a good step forward

**Pull request merged**
