### PR TITLE
Update Firebase SPM version to 7.6.0

### PR DESCRIPTION
**Pull request by 4brunu**
Firebase was updated to version 7.6.0 but the SPM version was still on 7.5.0, so I opened this PR to fix it.

### CODE REVIEW

**Comment by 4brunu** [comment]
@googlebot I signed it!

**Review by paulb777 — APPROVED** [review]
Thanks!

**Comment by 4brunu** [comment]
Could you please create a new tag to reference in SPM? Thanks

**Comment by paulb777** [comment]
Note that the 7.6.0 release was still getting installed. The fix only impacts the version logged with the release.

I'll need to wait for #7533 to get this change approved to the release branch to update the tag.  Since today is a holiday, this may not happen until tomorrow.

**Comment by 4brunu** [comment]
Thanks 👍

**Comment by paulb777** [comment]
The tag is now updated. Thanks @4brunu!

**Comment by 4brunu** [comment]
Thanks for your help and the quick resolution of this 👍

**Pull request merged**
