### PR TITLE
macOS support for Firestore

### PR DESCRIPTION
**Pull request by wilhuff**
This doesn't work yet because when building the `Firestore_Tests_macOS` target https://github.com/grpc/grpc/issues/7406 prevents the build from succeeding. `Firestore_Tests_iOS` continues to work. I can't figure out what's different about these two targets that would cause one to fail and one not to.

@paulb777 Does anything jump out at you?

Implements https://github.com/firebase/firebase-ios-sdk/issues/434

### CODE REVIEW

**Comment by wilhuff** [comment]
I've rebased this change on top of the recent changes imposed by `sync_project.rb`. Still doesn't work :-(.

**Comment by paulb777** [comment]
It looks like a cyclic header/module issue - although it's unclear why it occurs in a macOS build and not iOS.

Next step could be to make a reduced repro case just with gRPC.  

This doesn't seem to be exactly grpc/grpc#7406, but worth trying the fix now that it will be deployed in the next grpc release.

**Comment by mathieutozer** [comment]
I patched the pod spec changes to a local checkout of the repository (master) and was able to build it into my macOS target, however let db = Firestore.firestore() returns nil even after FirebaseApp.configure(). I get the 'officially unsupported' warning that's compiled in so I think I'm on the right track. Debugging I noticed that

```
- (nullable id)instanceForProtocol:(Protocol *)protocol {
```

tries to get a creationBlock out of a dictionary, but the dictionary is empty, meaning that it returns nil. I'm completely new to firebase development so wonder if on macOS I have to do some more registration?

**Comment by paulb777** [comment]
@mathieutozer This PR was created before the `instanceForProtocol:` mechanism was created, so I suspect something is out of sync.

There should be no difference between iOS and macOS for this, so I would recommend debugging to track down how they're going different.

**Comment by mathieutozer** [comment]
I've dug some more and I think it's the difference between the way iOS and macOS load static / dynamic libraries. The stack trace on iOS show dyld calling +load on each class it finds.

This is the stack trace on iOS 

```
#0	0x000000010e535970 in ::+[FSTFirestoreComponent load]() at /Users/tozer/code/firebase-ios-sdk/Firestore/Source/API/FSTFirestoreComponent.mm:115
#1	0x00000001105b778b in call_load_methods ()
#2	0x00000001105b840a in load_images ()
#3	0x000000010eaaccb7 in dyld::notifySingle(dyld_image_states, ImageLoader const*, ImageLoader::InitializerTimingList*) ()
#4	0x000000010eab8f88 in ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) ()
#5	0x000000010eab815e in ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) ()
#6	0x000000010eab81f2 in ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) ()
#7	0x000000010eaad052 in dyld::initializeMainExecutable() ()
#8	0x000000010eab0b6b in dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) ()
#9	0x000000010eaac3db in start_sim ()
#10	0x000000011a9f6ded in dyld::useSimulatorDyld(int, macho_header const*, char const*, int, char const**, char const**, char const**, unsigned long*, unsigned long*) ()
#11	0x000000011a9f47a3 in dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) ()
#12	0x000000011a9f03d4 in dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) ()
#13	0x000000011a9f01d2 in _dyld_start ()
```

I disassembled my binary and can see the appropriate classes in the source, I just need to figure out how to get the app to discover and load the classes... anyone have any ideas? I'm a bit rusty with my library loading!

**Comment by paulb777** [comment]
@mathieutozer I'd be surprised if there was a difference between iOS and macOS on how +load gets processed. The order might differ, but I would expect it to still be called.

**Comment by wilhuff** [comment]
The state of this PR is unlikely to be useful as a starting point because it's so old. This code should work on macOS, and the equivalent component loading strategy that depends on `+load` works on macOS in the other Firebase components so there's likely some other explanation at play.

**Comment by mathieutozer** [comment]
@wilhuff @paulb777 I spent a bit more time reproducing the issue with a fresh fork of the repo. As in my commit message as far as I can tell the symbols are linked, everything compiles correctly but + (void)load is not called. If I reference them directly it does, but then I start getting errors which led me to https://github.com/CocoaPods/CocoaPods/pull/7946. Could it be related?

https://github.com/mathieutozer/firebase-ios-sdk

**Comment by paulb777** [comment]
@mathieutozer Sorry that we don't have too much time to help with this right now, but here are a few thoughts based on your comments:

- How does `+load` work for FirebaseStorage on macOS?
- If it's related to CocoaPods/CocoaPods#7946, does adding `-ObjC` to the `Other Linker Flags` Build Setting make a difference?
- Does using the CocoaPods master branch make a difference?

**Comment by wilhuff** [comment]
Closing in favor of #2241.

**Pull request closed without merging**
