### PR TITLE
Fix lack of parse for fiam modal action button

### PR DESCRIPTION
**Pull request by fumito-ito**
Firebase user can set action button's text color on firebase console for Firebase InAppMessaging. But the parser is ignoring button text color.
This PR fixes a issues of parsing data of modal message.

### CODE REVIEW

**Comment by christibbs** [comment]
@fumito-ito Thanks for the catch. Could you add unit tests in this [file](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInAppMessaging/Tests/Unit/FIRIAMFetchResponseParserTests.m)? Looks like this was a gap in unit test coverage.

If you're having trouble with the tests or feel like they're taking too much time I can just close this out and send out a PR myself, just let me know.

**Comment by fumito-ito** [comment]
hi @christibbs, thanks for your replay. I just added a test to check button text color of modal view. please review it.

**Review by christibbs — APPROVED** [review]

**Comment by christibbs** [comment]
@fumito-ito Please run the `scripts/style.sh` script to format your code changes. See instructions [here](https://github.com/firebase/firebase-ios-sdk#code-formatting).

**Comment by fumito-ito** [comment]
> @fumito-ito Please run the `scripts/style.sh` script to format your code changes. See instructions [here](https://github.com/firebase/firebase-ios-sdk#code-formatting).

sorry, I run format scripts and force push changes.

**Comment by christibbs** [comment]
@fumito-ito Looks like the test you added is failing. See results here: https://github.com/firebase/firebase-ios-sdk/pull/8140/checks?check_run_id=2740296359#step:4:53. 

Are the tests succeeding when you run them in Xcode?

1.  Install [cocoapods-generate](https://github.com/square/cocoapods-generate).
2. Run `pod gen FirebaseInAppMessaging.podspec` from the `firebase-ios-sdk` directory.
3. Run unit tests from the `.xcworkspace` file that gets generated.

**Comment by fumito-ito** [comment]
@christibbs I fixed failed tests and rerun check. But some checks, `test_coverage / create_reports` were not successful. Could you tell me hot to fix it ?

**Comment by paulb777** [comment]
@fumito-ito Thanks. You can disregard the `test_coverage` failure.  It's a result of the known issue #7476. cc: @granluo

**Comment by christibbs** [comment]
@fumito-ito Thanks for contributing to Firebase!

**Pull request merged**
