### PR TITLE
Move fuzzers out of core/test

### PR DESCRIPTION
**Pull request by wilhuff**

### CODE REVIEW

**Comment by minafarid** [comment]
@var-const OSS Fullz will not work in this case. Our [build script](https://github.com/google/oss-fuzz/blob/master/projects/firestore/build.sh#L38) assumes that fuzzing is in core/test

**Comment by var-const** [comment]
@minafarid Would that be a trivial fix (just changing that path in the build script), or are there any issues involved?

**Comment by minafarid** [comment]
Yes it is trivial but requires OSS Fuzz approval. I will make the necessary changes in the OSS Fuzz repository and merge this PR.

**Comment by minafarid** [comment]
I will fix the conflicts as well.

**Comment by minafarid** [comment]
Changes to OSS Fuzz are done and Merged (quickly!) in [PR](https://github.com/google/oss-fuzz/pull/1701).

I will merge this PR right after PR #1669 because I merged that branch here.

**Comment by minafarid** [comment]
Edit - will remove dependency on PR #1669 and merge this.

**Pull request merged**
