### PR TITLE
[Infra] Migrate away from macos-12 in performance.yml

### PR DESCRIPTION
**Pull request by ncooke3**
Related to #11903

#no-changelog

### CODE REVIEW

**Comment by ncooke3** [comment]
Edit: I think https://github.com/firebase/firebase-ios-sdk/issues/11903 is still valid because pod gen locally reveals the failures, but it's weird that the tests passed...

**Comment by ncooke3** [comment]
Hmm, looks like xcbeautify doesn't surface a failing exit code when tests crash:

https://github.com/firebase/firebase-ios-sdk/actions/runs/11862154195/job/33061011258?pr=14131#step:6:893

**Review by andrewheard — COMMENTED** [review]
> Hmm, looks like xcbeautify doesn't surface a failing exit code when tests crash

This was a good catch. Let's investigate what to do next before merging.

**Review by andrewheard — APPROVED** [review]
Although this doesn't fully resolve https://github.com/firebase/firebase-ios-sdk/issues/11903, moving off of `macos-12` will soon be important and the jobs that are changed in this PR (see below) are passing on CI.
https://github.com/firebase/firebase-ios-sdk/blob/d84d5ef671d30428215869fe6ab003894d5a7f25/scripts/build.sh#L637-L660

Unlike the `spm` jobs, the ones touched in this PR don't appear to be crashing:
- [`performance (iOS, unit)`](https://github.com/firebase/firebase-ios-sdk/actions/runs/11903111835/job/33169435805?pr=14131#step:7:1426)
- [`performance (iOS, proddev)`](https://github.com/firebase/firebase-ios-sdk/actions/runs/11903111835/job/33169436645?pr=14131) (build only)
- [`performance (tvOS, unit)`](https://github.com/firebase/firebase-ios-sdk/actions/runs/11903111835/job/33169437183?pr=14131#step:7:1428)
- [`performance (tvOS, proddev)`](https://github.com/firebase/firebase-ios-sdk/actions/runs/11903111835/job/33169437705?pr=14131) (build only)

**Review by paulb777 — APPROVED** [review]

**Pull request merged**
