### PR TITLE
Fix Auth API docs typo

### PR DESCRIPTION
**Pull request by paulb777**
Fix typo

Thanks to @frboulais for pointing this out in  #9820

### CODE REVIEW

**Comment by peterfriese** [comment]
LGTM

**Comment by peterfriese** [comment]
LGTM on the typo, but the `OAuthProvider` addition doesn't seem to belong into the Combine module.

**Comment by paulb777** [comment]
Thanks, I'll reevaluate

**Review by renkelvin — APPROVED** [review]
Thanks!

**Review by morganchen12 — APPROVED** [review]

**Pull request merged**
