### PR TITLE
Update Functions emulator to fix CI regression

### PR DESCRIPTION
**Pull request by paulb777**
#no-changelog

### CODE REVIEW

**Review by ryanwilson — APPROVED** [review]

**Comment by paulb777** [comment]
Going to merge here to fix CI, but would still appreciate a deeper look @morganchen12 on if the emulator is being set up correctly

**Comment by morganchen12** [comment]
Where is the functions emulator setup located?

**Comment by paulb777** [comment]
It's located in https://github.com/firebase/firebase-ios-sdk/tree/master/Functions/Backend and used like https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/functions.yml#L30

**Comment by morganchen12** [comment]
Functions usage LGTM, but @samtstern can probably give better scrutiny here than I can.

**Comment by samtstern** [comment]
👍

**Pull request merged**
