### PR TITLE
Update versions for Release 9.5.0

### PR DESCRIPTION
**Pull request by chliangGoogle**

### CODE REVIEW

**Review by ncooke3 — APPROVED** [review]
LGTM on green.

**Review by paulb777 — APPROVED** [review]

**Comment by paulb777** [comment]
Looks like an unrelated infra issue in the firestore tests - https://github.com/firebase/firebase-ios-sdk/runs/7755695980?check_suite_focus=true#step:5:42

**Comment by chliangGoogle** [comment]
Yeah, will submit if the rest is green.

**Comment by ncooke3** [comment]
I believe the failing watchOS workflow is due to #10082. It should have been surfaced by #10082 but wasn't so I have sent #10091 to fix that.

I'll look into fixing the watchOS workflow.

**Pull request merged**
