### PR TITLE
 Merge branch 'main' into 'release-11.0'

### PR DESCRIPTION
**Pull request by ncooke3**
Includes secrets PRs to fix secrets dependent CI on 'release-11.0' branch.

#no-changelog

### CODE REVIEW

**Comment by ncooke3** [comment]
Oh, CI failures are real. Addressing...

**Review by paulb777 — APPROVED** [review]
LGTM on acceptable CI

**Review by andrewheard — APPROVED** [review]
LGTM. Might want to merge by pushing to `release-11.0` from the command line instead of squashing.

**Comment by ncooke3** [comment]
> LGTM. Might want to merge by pushing to `release-11.0` from the command line instead of squashing.

@andrewheard @paulb777 
Does `git checkout release-11.0; git merge --no-ff nc/merge-main` for that sound familiar?

**Comment by ncooke3** [comment]
`git checkout release-11.0; git merge --no-ff nc/merge-main; git push origin HEAD`

**Pull request merged**
