### PR TITLE
Add phone number property to NSSecureCoding

### LINKED ISSUE #67: Phone Auth user not behaving as expected
### [READ] Step 1: Are you in the right place?

I really hope so, and am very sorry if not.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 8.3.2
  * Firebase SDK version: 4.0.0
  * Library version: 4.0.0?
  * Firebase Product: auth (specifically, phone auth)

#### Steps to reproduce:

I have implemented phone auth, using the sample code provided in the docs.  When I call `            Auth.auth().signIn(with: credential) { user, error in ....`, the `user` seems to be valid, with a non-nil phoneNumber (I'm using phone auth).  Later, when I call `Auth.auth().currentUser`, the user I get back also has a non-nil phoneNumber.  However, when I kill my app, and restart it, if I call `Auth.auth().currentUser`, the user I get back has the .phoneNumber property set to nil.

I'm really sorry to bother you, and hope I haven't broken any rules.

### PR DESCRIPTION
**Pull request by protocol86**
Encodes and decodes the phone number property of FIRUser.
Fixes #67

### CODE REVIEW

**Comment by IHEARTCOOKIES** [comment]
When will this be merged into cocoa pods? @protocol86

**Comment by paulb777** [comment]
This PR was included in the push to CocoaPods with Firebase 4.1.0 and FirebaseCommunity 0.1.0.

**Comment by IHEARTCOOKIES** [comment]
Could you please confirm that this bug was fixed in 4.1.0? Still shows up as nil for me. However, if I access it through `providerData`, it works fine.

I'm using:
```
Firebase 4.1.0
FirebaseAnalytics 4.0.3
FirebaseAuth 4.1.0
FirebaseCore 4.0.5
FirebaseInstanceID 2.0.1
FirebaseMessaging 2.0.1
```

Or do I explicitly have to include FirebaseCommunity?

**Comment by XiangtianDai** [comment]
@IHEARTCOOKIES Please note that while the bug has been fixed in the code, if the current user data was saved to the Keychain by a previous version of FirebaseAuth, that data would have missed the phone number, and a new version of FirebaseAuth in the running app won't help. Either reloading the user data (by calling `[[FIRAuth auth].currentUser reloadWithCompletion(...)` (or `Auth.auth().currentUser.reload() {...}` in Swift)) or signing in the user again should update the saved user data in the Keychain to contain the phone number.

**Comment by IHEARTCOOKIES** [comment]
You are correct. I missed this and that is what was causing nil. Thanks @XiangtianDai

**Pull request merged**
