### PR TITLE
Be sure to validate return code when calling sysctlbyname function (C…

### PR DESCRIPTION
**Pull request by dloic**
Hi!

This is a simple PR to fix an issue related to not checking return code of a C function.
The issue was raised by a static code/binary analysis we use to validate our app. 

Firebase SDK (in DynamicLinks part) is using the C function sysctlbyname without being sure the call was successful. 
The issue is related to the following CWE: http://cwe.mitre.org/data/definitions/391.html.

Let me know if I should made any other adjustment to this PR.

Best regards.

### CODE REVIEW

**Comment by dloic** [comment]
I did fix the issue with whitespace, forgot to run the script to check before first commit.

**Comment by paulb777** [comment]
Hi @dloic Thanks for the contribution! And sorry about our slow response.

The whitespace issue is fixed, and travis is now showing a style issue from clang-format. Please run the script [./scripts/style.sh](https://github.com/firebase/firebase-ios-sdk/blob/master/scripts/style.sh) with the right version of [clang-format](https://github.com/firebase/firebase-ios-sdk#code-formatting).

**Comment by paulb777** [comment]
cc: @dmandar

**Comment by dloic** [comment]
@paulb777 no worries for slow response :) I did run the script and git add the changes. I'm now aware of what is required before pushing another PR!

**Pull request merged**
