### PR TITLE
Adding UI Test (fdl-deprecation)

### PR DESCRIPTION
**Pull request by srushtisv**
test to verify email link sent successfully

### CODE REVIEW

**Comment by ncooke3** [comment]
clang-format versions disappear from homebrew every few months. `main` should always be fixed, but branches off of main like this one may stop working until they are synced with main again

**Review by Xiaoshouzi-gh — COMMENTED** [review]
can you also add a custom domain test?  The custom domain for CI projects should be "firebaseiosauthsample.testdomaindonotuse.com"

**Review by Xiaoshouzi-gh — COMMENTED** [review]
The base branch fdl-dep has rebased from main by a force push.
If the CI did not reflect please try following steps:

1. squash all our commits in fdl-dep-test into 1 commit (note down the hash)
You can do this by git reset --soft to the last commit that is not yours then do a git commit.
3. clone a new branch base of fdl-dep
4. cherry-pick the commit from step 1 to 2.

**Comment by srushtisv** [comment]
completed in #1400

**Comment by srushtisv** [comment]
completed in #140000

**Pull request closed without merging**
