### PR TITLE
Firestore: Fix FAILED_PRECONDITION when writing to a deleted document in a transaction

### PR DESCRIPTION
**Pull request by dconeybe**
This PR ports https://github.com/firebase/firebase-js-sdk/pull/6550, and its follow-up PR https://github.com/firebase/firebase-js-sdk/pull/6729. A similar port to the Android SDK was done in https://github.com/firebase/firebase-android-sdk/pull/4257.

### CODE REVIEW

**Review by milaGGL — COMMENTED** [review]
As far as  I can understand, the bug fix logic is in sync with web and android SDK.

**Review by milaGGL — APPROVED** [review]
LGTM

**Review by wu-hui — APPROVED** [review]
LGTM!

**Comment by dconeybe** [comment]
FYI This fix has been incorporated into version 10.2.0 released November 15, 2022 https://firebase.google.com/support/release-notes/ios#version_1020_-_november_15_2022

**Pull request merged**
