### PR TITLE
Add coverage test workflow.

### PR DESCRIPTION
**Pull request by granluo**

### CODE REVIEW

**Comment by granluo** [comment]
Testings for database and functions are in cd54ecf
This is the prerequisite for code coverage report post. The workflow will check file patterns to determine if pod tests should be run. Once pod tests are run, xcresult will be generated and uploaded. This pr will not affect current workflows or pull requests.
The following pr will arrange all uploaded xcresult bundle into a json file and send out a request to the Metrics service, which will generate a code coverage report.

**Comment by paulb777** [comment]
Will you describe what this PR does? Are reports generated somewhere?

**Comment by granluo** [comment]
> Will you describe what this PR does? Are reports generated somewhere?

This PR is a prerequisite for reports. Reports will not be generated in this pr yet. To avoid a PR with too many updated/new files, I split it into two. This might make the review process easier.

1. get_updated_files.sh will help get updated files to determine which sdk workflow to trigger.
2. pod_test_code_coverage_report.sh will run pod tests and create xcresult bundles, with code coverage report, for SDKs 3. The workflow test_coverage.yml will determine testing jobs to trigger and all xcresult bundles will be uploaded as artifacts on Github Actions.

An upcoming PR will fetch these artifacts and combine coverage reports into a json file and then an API request will be sent with the json file to the Metrics Service, which will help generate a report.

**Review by paulb777 — APPROVED** [review]

**Comment by granluo** [comment]
This PR is a prerequisite for generating code coverage report.

get_updated_files.sh will help get updated files to determine which sdk workflow to trigger.
pod_test_code_coverage_report.sh will run pod tests and create xcresult bundles, with code coverage report, for SDKs 
The workflow test_coverage.yml will determine testing jobs to trigger and all xcresult bundles will be uploaded as artifacts on Github Actions.

An upcoming PR will fetch these artifacts and combine coverage reports into a json file and then an API request will be sent with the json file to the Metrics Service, which will help generate a report.

**Pull request merged**
