### PR TITLE
feat: add basic support to build frameworks and zip them for the Apple Watch

### LINKED ISSUE #8731: FR: Support watchOS platform in xcframework, Carthage distribution
### Issue
Downloading frameworks from Firebase distribution (https://firebase.google.com/download/ios) is not included watchOS platform support.
watchOS support is included in SPM and Cocoapods. 

### Proposal
Add support watchOS in the xcframework.

### PR DESCRIPTION
**Pull request by jasesuperhero**
Fix #8731

These PRs add the ability to build frameworks using ReleaseTooling for Apple Watch. In my project I want to use Carthage as a dependency manager and by chance, I realized that the Firebase built frameworks do not support the architecture for Apple Watch.

The following changes are made in this PR:
- Added support for the Apple Watch platform and declared all necessary paths.
- Added arm64_32 architecture to build frameworks for Apple Watch device above Series 4. According to this documentation https://docs.elementscompiler.com/Platforms/Cocoa/CpuArchitectures/
- The minimal version is set as watchOS 6, according to podspecs.

As far as I understand supporting for different platforms is a part of the roadmap for the ReleaseTooling.

### CODE REVIEW

**Comment by jasesuperhero** [comment]
Sorry, I don't know how to add labels for the pr. Looks like I don't have such permissions

**Comment by paulb777** [comment]
Thanks for working on this @jasesuperhero!

There will also need to be updates to the `platforms` flag to exclude products that aren't supported for watchos, like FirebaseDatabase and FirebaseFirestore.

**Comment by jasesuperhero** [comment]
> Thanks for working on this @jasesuperhero!
> 
> There will also need to be updates to the `platforms` flag in the [manifest](https://github.com/firebase/firebase-ios-sdk/blob/main/ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift#L47) to exclude products that aren't supported for watchos, like FirebaseDatabase and FirebaseFirestore.

Thanks for the quick response! Yes, of course. I'll fix the manifest to remove unsupported frameworks. 

I just have one question. I see that FirebaseDatabase supports watchos, but only since version 7. Right now all other frameworks have version 6. 

What is the more correct way to proceed here? Just make it unavailable for watchos according to the [documentation here](https://firebase.google.com/docs/ios/learn-more) or set the minimum version as 7.0 and add it to the build?

**Comment by jasesuperhero** [comment]
@ncooke3 Thanks for the clarification! 
Fixed all remarks!

**Comment by jasesuperhero** [comment]
@paulb777 @ncooke3 looks like the build failed.

I checked the code and changes again and realized that it may be necessary to also add **s.watchos.deployment_target = '6.0'** also in **Firebase.podspec**. According to this error in the logs:

```
Output from `pod install`:
Analyzing dependencies

[!] The platform of the target `FrameworkMaker` (watchOS 6.0) is not compatible with `Firebase (10.24.0)`, which does not support `watchOS`.
```

Also, I changed **minimumWatchOSVersion** to "**8.0**" in **useRecentVersions**. As I understand it, we need to use a version higher than 6.0 in case we build frameworks with the **zipPods** parameter

**Comment by paulb777** [comment]
Thanks, good find. The `package-release` job should still fail since it's building the latest release tags. `package-head` should succeed.

**Comment by jasesuperhero** [comment]
Ok, I think I understand the stages of the build and why it fell over last time. I also added platforms for GoogleAppMeasurement, Firebase podspecs.

**Comment by jasesuperhero** [comment]
@paulb777 Great, the PR build is green and I tested the build again locally. Watch specific binaries included in the xcframeworks.

**Comment by paulb777** [comment]
Thanks @jasesuperhero ! We appreciate the contribution. Looks good so far. We'll do a more thorough review and try to merge in for our next release.

**Comment by jasesuperhero** [comment]
Hey @paulb777! I tried testing the assembled binary on a real device and when building on the Apple Watch Ultra 2, I found that it was missing some architecture. I understand that we also need to add arm64 for watchos targeting.

So I updated that and also updated the template README.md to match all available platforms.

**Comment by paulb777** [comment]
Good spot! Have you confirmed the one of the zips built at https://github.com/firebase/firebase-ios-sdk/actions/runs/8468158559 addresses the Apple Watch Ultra 2 issue?

**Comment by jasesuperhero** [comment]
@paulb777 I haven't had time to test the built frameworks from github yet, but I've been building them locally with the latest changes. Everything works without any problems. I also tried submitting some crashes to Crashlytics and they showed up there.

**Review by paulb777 — APPROVED** [review]
Thanks @jasesuperhero! I'll merge now and add a release note in a subsequent PR

**Pull request merged**
