### PR TITLE
Release 7.1.0 cherry picks

### PR DESCRIPTION
**Pull request by maksymmalyhin**
- cherry pick of #6863
- GDT 8.0.1 added to the release

### CODE REVIEW

**Comment by maksymmalyhin** [comment]
@mikeger Could you please provide your consent following the instructions from the [comment](https://github.com/firebase/firebase-ios-sdk/pull/6917#issuecomment-723137967).

**Comment by mikeger** [comment]
@googlebot I consent.

**Review by paulb777 — APPROVED** [review]
LGTM - CI failures are expected on release branch because latest Analytics isn't available in GHA

**Review by morganchen12 — APPROVED** [review]
Changelogs LGTM

**Pull request merged**
