### PR TITLE
Add Performance podspec

### PR DESCRIPTION
**Pull request by paulb777**
Enable more shared test and release processes between binary and source pods.

#no-changelog

### CODE REVIEW

**Review by visumickey — COMMENTED** [review]
How are we planning to have this updated on a regular basis? Is this planned to be updated as a part of every release?

**Comment by paulb777** [comment]
Yep, the proposed process is that your team updates the source field of the podspec by code freeze if you want to make an update and the iCore team manages the versioning and release from there.

**Comment by visumickey** [comment]
> Yep, the proposed process is that your team updates the source field of the podspec by code freeze if you want to make an update and the iCore team manages the versioning and release from there.

Thanks Paul.

Just to clarify - Perf team, when we plan to make a release, we make changes to the podspec in the "FirebasePrivate/perf" branch and we also make the change to this public podspec? Want to make sure I update the steps for making a release from private Github.

**Review by visumickey — APPROVED** [review]

**Comment by paulb777** [comment]
Confirmed.

After the next release, we'll stop managing releases via spreadsheet and the GitHub master branch becomes the mechanism for identifying what is part of a release.

**Pull request merged**
