### PR TITLE
Fix a race condition involving binary images being changed.

### PR DESCRIPTION
**Pull request by elenadoty**
#no-changelog

### CODE REVIEW

**Comment by chrisvasselli** [comment]
I am still seeing the crash even with this change, in my reproduction here: https://github.com/samedson/issues/pull/1

**Comment by chrisvasselli** [comment]
Here's the new stack I'm seeing, and the line in the changed code that is still leading to the crash. 

Screen Shot 2021-02-04 at 1 35 32 PM
Screen Shot 2021-02-04 at 1 35 42 PM

**Review by samedson — APPROVED** [review]
Just a changelog and ship it!

**Comment by samedson** [comment]
Oh looks like @chrisvasselli is crashing on the added callback too

**Comment by chrisvasselli** [comment]
@samedson @elenadoty let me know if there's any more information about my system/setup you think might be useful. If you have any other fixes you'd like me to try, I'm happy to help.

**Comment by elenadoty** [comment]
Hi @chrisvasselli ,
Thanks so much for helping us out on this. I've just pushed another change, would you mind trying that out?

**Comment by chrisvasselli** [comment]
@elenadoty that one seems to be working!

**Review by samedson — APPROVED** [review]
Doubly approved!

**Pull request merged**
