### PR TITLE
Analytics 10.24.0

### PR DESCRIPTION
**Pull request by tsunghung**
#no-changelog

### CODE REVIEW

**Review by ncooke3 — APPROVED** [review]
LGTM. I see symlinks for macOS/Catalyst frameworks and code signatures for all XCFrameworks.

**Comment by ncooke3** [comment]
CI failures looks like an Auth x macOS 13 flake. I say still gtg 👍

**Review by paulb777 — APPROVED** [review]

**Comment by ncooke3** [comment]
Passed on that re-run (thanks @paulb777!).  Merging.

**Comment by ncooke3** [comment]
Moved tags and re-pushed pods.

**Pull request merged**
