### PR TITLE
[auth-swift] Style auth-swift with clang-format16

### PR DESCRIPTION
**Pull request by ncooke3**
#no-changelog

### CODE REVIEW

**Comment by ncooke3** [comment]
I'll merge on green check. cc: @paulb777

**Comment by ncooke3** [comment]
Err, actually, @paulb777, let me know you are actively working on these affected files and I can hold off.

**Comment by paulb777** [comment]
I'm not sure we want to do this, since ideally the ObjC sample should stay as close as possible to the one in master.

**Comment by ncooke3** [comment]
@paulb777, fair point, though I'm not sure why these style changes are failing in master. Closing.

**Comment by paulb777** [comment]
See https://github.com/firebase/firebase-ios-sdk/blob/master/scripts/style.sh#L162

**Pull request closed without merging**
