### PR TITLE
Remove InstanceID from Github repo

### PR DESCRIPTION
**Pull request by chliangGoogle**
Sunsetting Firebase InstanceID and please use Firebase Installations to manage app identifier and use Firebase Messaging to manage FCM registration token. 
See migration guide: https://firebase.google.com/docs/projects/manage-installations#fid-iid

### CODE REVIEW

**Review by maksymmalyhin — APPROVED** [review]
`−13,361` line of code 🎉 

LGTM on CI green

**Comment by paulb777** [comment]
See the results of `git grep -i instanceid`.

Some other removals are needed across scripts, ReleaseTooling, Dangerfile, .github/workflows/instanceid.yml, .travis.yml, FirebaseAuth/Tests/Sample/Podfile

**Comment by paulb777** [comment]
Needs a rebase or a merge to run CI

**Review by paulb777 — APPROVED** [review]

**Review by morganchen12 — APPROVED** [review]

**Comment by rsattar** [comment]
Woo hoo! 🎉 
LGTM! 😄 ❤️

**Pull request merged**
