### PR TITLE
Make use of SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION conditional.

### PR DESCRIPTION
**Pull request by cprince-foreflight**
https://github.com/firebase/firebase-ios-sdk/issues/10884

### Testing

  * I ran Firebase remote config tests locally.

### CODE REVIEW

**Comment by paulb777** [comment]
Thanks! This is a much simpler solution than completely replacing sqlite. What is the implication of running without the `SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION` when it's not available?

**Comment by cprince-foreflight** [comment]
> Thanks! This is a much simpler solution than completely replacing sqlite. What is the implication of running without the `SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION` when it's not available?

Well, good question :). I see basically no docs for this. E.g., I wouldn't call [this](https://lists.apple.com/archives/cocoa-dev/2012/Aug/msg00512.html) docs. I'm *assuming* from the naming that it relates to [standard concepts of file protection/encrpytion with iOS](https://support.apple.com/guide/security/data-protection-classes-secb010e978a/web#:~:text=or%20are%20authenticated.-,Protected%20Until%20First%20User%20Authentication,or%20the%20user%20logged%20out.).

I'm about to test this in our app (hence the DRAFT status), and hopefully my colleague [aaron-foreflight](https://github.com/aaron-foreflight) will add his 2 cents.

**Comment by ncooke3** [comment]
@cprince-foreflight, thanks! I think one case worth checking will be the following:
1. use Remote Config without this change to initialize DB
2. try to access the same DB again (without deleting the app) with the change
This could help rule out the risk of the pre-change DB becoming inaccessible when it is accessed with one less flag after upgrading.

**Comment by cprince-foreflight** [comment]
> @cprince-foreflight, thanks! I think one case worth checking will be the following:
> 
> 1. use Remote Config without this change to initialize DB
> 2. try to access the same DB again (without deleting the app) with the change
>    This could help rule out the risk of the pre-change DB becoming inaccessible when it is accessed with one less flag after upgrading.

Definitely. And I think it's particularly important for step 2), when `SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION` is *not* defined. Shall have to stare at this a bit to see if I can test it. Our use isn't exactly simple :).

**Comment by cprince-foreflight** [comment]
> > @cprince-foreflight, thanks! I think one case worth checking will be the following:
> > 
> > 1. use Remote Config without this change to initialize DB
> > 2. try to access the same DB again (without deleting the app) with the change
> >    This could help rule out the risk of the pre-change DB becoming inaccessible when it is accessed with one less flag after upgrading.
> 
> Definitely. And I think it's particularly important for step 2), when `SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION` is _not_ defined. Shall have to stare at this a bit to see if I can test it. Our use isn't exactly simple :).

Well. Hmmm. My first thought to test this was to put together a demo/test app that creates a `RCNConfigDBManager` instance to try the tests above. However, it seems like `RCNConfigDBManager` isn't in scope when using the package imports.

So, I had to hack a bit, but got there. I added in a "testDb" static method to the "RemoteConfig" class which I can access from my app. That method is defined as:
```
+ (void) testDb {
    RCNConfigDBManager *manager = [[RCNConfigDBManager alloc] init];
}
 ```

And I call this from my test app that I run an iOS simulator.

# Test 1

To start with, I deleted the app.

This has [the original flags code](https://github.com/firebase/firebase-ios-sdk/blob/6238c935fb69597bf2e2b17e70dd1d364b11ca42/FirebaseRemoteConfig/Sources/RCNConfigDBManager.m#L218-L220):

     int flags = SQLITE_OPEN_CREATE | SQLITE_OPEN_READWRITE |
                  SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION |
                  SQLITE_OPEN_FULLMUTEX;

I set various breakpoints after that and when I run my test, I get  to:
Screenshot 2024-04-02 at 3 09 19 PM

That is [here](https://github.com/firebase/firebase-ios-sdk/blob/6238c935fb69597bf2e2b17e70dd1d364b11ca42/FirebaseRemoteConfig/Sources/RCNConfigDBManager.m#L245).

After it gets to this breakpoint, I let it continue execution.

# Test 2

I then stop the app. I do *not* remove it.
I change to the new flag code:

   int flags = SQLITE_OPEN_CREATE | SQLITE_OPEN_READWRITE | SQLITE_OPEN_FULLMUTEX;
#ifdef SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION
    flags |= SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION;
#endif

And I re-run/re-launch the app.I get to the same place again. That is [here](https://github.com/firebase/firebase-ios-sdk/blob/6238c935fb69597bf2e2b17e70dd1d364b11ca42/FirebaseRemoteConfig/Sources/RCNConfigDBManager.m#L245).
Screenshot 2024-04-02 at 3 05 28 PM

# Conclusion

I think this is a successful (non-failure) result. Happy to upload the full test code, but I've got the sdk inside of it, so it's somewhat large (122MB). Please let me know.

**Comment by cprince-foreflight** [comment]
I repro'd those test steps on my iPhone hardware too. Between Test 1 and Test 2 I restarted my device to ensure that I had to sign back in. Same results as on simulator.

**Comment by cprince-foreflight** [comment]
I ran another test sequence, on my iPhone. Test 1 was the same with this setup:
Test1
Test 2 had:
Test2

Between Test 1 and Test 2 I powered down my iPhone and powered it backup to ensure it was locked prior to Test 2.
Same (positive) results. On both tests:
Result

**Review by karenyz — APPROVED** [review]
thanks for the detailed testing notes for the upgrade case!

**Pull request merged**
