### PR TITLE
Improve/use shorthand syntax for unwrapping optionals and fix typos

### PR DESCRIPTION
**Pull request by sheikhbayazid**
Improved code with shorthand syntax for unwrapping optionals and fixed a few typos in documentation.

For example:

This code: 
```
if let error = error { ... }
```
 is replaced with 
```
if let error { ... }
```

### CODE REVIEW

**Comment by paulb777** [comment]
Thanks for the PR! 

Looks like there are some build errors on Xcode 14 in CI which we plan to support for the next few months as long as the App Store does.

**Comment by paulb777** [comment]
Marking for review and merge for the next major release, when we'll have dropped Xcode 14 support.

**Comment by sheikhbayazid** [comment]
> Marking for review and merge for the next major release, when we'll have dropped Xcode 14 support.

Great!

**Review by paulb777 — APPROVED** [review]
Thanks!

**Review by romankulkovsf — COMMENTED** [review]
@all good

**Pull request merged**
