### PR TITLE
[Release] Re-spin FST with signed artifact

### PR DESCRIPTION
**Pull request by ncooke3**
#no-changelog

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]
LGTM on green

**Comment by ncooke3** [comment]
```
 Downloads 
‣ diff -r /Users/nickcooke/Downloads/FirebaseFirestoreInternal.xcframework  /Users/nickcooke/Downloads/FirebaseFirestoreInternal_old.xcframework                                   
Only in /Users/nickcooke/Downloads/FirebaseFirestoreInternal.xcframework: _CodeSignature
```

**Comment by ncooke3** [comment]
I don't think there is an issue but making a note here...

This is the build log that seems to confirm it is picking up a signature. Unfortunately, I cannot double click into the "Show Signature Information" part. Xcode 15.3 RC doesn't do anything when you double click that.
Screenshot 2024-03-13 at 6 54 42 PM

But, I manually dragged in the xcframework and you can see the signature pick up:
Screenshot 2024-03-13 at 6 54 27 PM

**Comment by ncooke3** [comment]
Pointing to this branch, I built my test app for iOS and also for macOS. Both archives validated successfully. This is gtg on green.

**Comment by ncooke3** [comment]
@paulb777, despite the failing CI,  think this can still merge. WDYT? I've never seen these failures before but they are mainly FirebasweFunctions integration tests.

**Comment by paulb777** [comment]
SGTM - I would think any signing issues would show up at build time - not runtime.

**Comment by paulb777** [comment]
I'll merge and retag now.

**Pull request merged**
