### PR TITLE
Add new firestore-nightly workflow

### PR DESCRIPTION
**Pull request by wu-hui**
Example run: https://github.com/firebase/firebase-ios-sdk/actions/runs/7132339153/job/19424930017?pr=12180

Note the tests failed due to some composite indexes missing, and nightly seems to have large serverTimestamp drifts.

### CODE REVIEW

**Review by tom-andersen — APPROVED** [review]
This seems fine, with no customer facing consequence, so I will approve.

But how will we know this is working?

**Comment by wu-hui** [comment]
> This seems fine, with no customer facing consequence, so I will approve.
> 
> But how will we know this is working?

The test outputs where it is connecting to, and the check is added as an optional CI workflow now.

**Comment by paulb777** [comment]
@wu-hui This job is both starting too late and consistently failing since added. Please address. https://github.com/firebase/firebase-ios-sdk/actions/workflows/firestore-nightly.yml

**Comment by wu-hui** [comment]
Nightly is unstable, i am going to make this workflow an on-demand one, instead of a scheduled or PR run.

**Pull request merged**
