### PR TITLE
Add AppDistribution to SwiftPM.

### PR DESCRIPTION
**Pull request by ryanwilson**
~~Tests aren't ported yet due to an import OCMock issue.~~
Tests are now ported.

### CODE REVIEW

**Comment by ryanwilson** [comment]
No rush for review until after Thanksgiving holidays of course!

**Review by jeremydurham — APPROVED** [review]

**Comment by jeremydurham** [comment]
@ryanwilson Thank you for doing this!

**Review by paulb777 — APPROVED** [review]
What's the OCMock issue?

Add a CHANGELOG update for 7.3.0

**Comment by ryanwilson** [comment]
> What's the OCMock issue?

The `#import <OCMock/OCMock.h>` imports were failing, but `@import OCMock;` passes. I was under the impression it was a common issue with SwiftPM since the other products I saw didn't have unit tests added. Maybe I missed something?

> Add a CHANGELOG update for 7.3.0

Will do.

**Comment by paulb777** [comment]
`#import "OCMock.h"` works with both

**Comment by ryanwilson** [comment]
> I'm ok to defer tests to a future PR though

I added tests in this PR so I wouldn't forget eventually :P

**Review by paulb777 — APPROVED** [review]

**Pull request merged**
