### PR TITLE
Merge the M68 6.22.0 release branch

### PR DESCRIPTION
**Pull request by ryanwilson**

### CODE REVIEW

**Comment by wilhuff** [comment]
I'm not sure about the rest, but #5286 was definitely made directly against the release branch.

**Comment by ryanwilson** [comment]
> Can you explain the source diffs? Were there changes made on the release branch that didn't come from cherry-picks?

I'm not sure why some are showing up in the diff - #5266 definitely merged in master and the diff is showing here.

**Comment by paulb777** [comment]
Oh, I see. This PR didn't follow the new process in go/firi.

**Comment by ryanwilson** [comment]
Apologies, followed the wrong process due to cherry-picks. Thanks Paul for the heads up - closing this in favour of #5319 which has a much cleaner diff.

**Pull request closed without merging**
