### PR TITLE
Mark ObjC typedefs as unavailable in Swift.

### PR DESCRIPTION
**Pull request by ryanwilson**
ATTN: BREAKING CHANGE FOR SWIFT USERS

This is part of the larger Swift API improvements effort. These reduce
visibility in autocomplete, and we've mostly migrated away from them
already. This hides the unused type from the API surface to avoid
cluttering the list of types available.

### CODE REVIEW

**Comment by ryanwilson** [comment]
Fixes #9341. Need to actually fix the CombineSwift unit tests.

**Comment by paulb777** [comment]
The API review is approved. This can be rebased to v9 and merged.

**Review by paulb777 — COMMENTED** [review]
Need a discussion about Storage and Remote Config if we go with Swift-libraries for them.

Also, the conflict needs to be resolved.

**Review by paulb777 — APPROVED** [review]
We cam sort out the Storage conflicts when they come up.

**Comment by ryanwilson** [comment]
Pretty sure the Auth lib lint is a flake, will merge and address if it's failing in other PRs.

**Pull request merged**
