### PR TITLE
pass appData for In-App Messaging's test message

### LINKED ISSUE #9126: In-App Messaging's test message does not include `appData` in response (and also not in `InAppMessagingDisplayMessage` )
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.4.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: In-App Messaging
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

In-App Messaging' message has `appData` property. But it looks always `nil` for test message.

#### Steps to reproduce:

1. Make an App to receive In-App Messaging
1. Create and send Test message from Firebase Console
1. Set a break point at `displayMessage(:displayDelegate:)` in `1.`'s App and run the App in Debug mode
1. See `messageForDisplay.appData` in debug console. It shows `nil`.

#### Relevant Code:

There are two causes of this problem.

##### 1. `FIRIAMFetchResponseParser` always ignores `appData` for test message

https://github.com/firebase/firebase-ios-sdk/blob/d28849cb12de765d013b7222123bd3b8ae8c4f0a/FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m#L357-L367

In this code, `FIRIAMFetchResponseParser` looks ignore `appData` for test message.

##### 2. In-App Messaging's response does not contain `appData` property for test message.

https://github.com/firebase/firebase-ios-sdk/blob/480178b0871217c5f4fd3dd3c3a309c78c1d5c4c/FirebaseInAppMessaging/Sources/Flows/FIRIAMMsgFetcherUsingRestful.m#L171-L173

I found that `appData` also does not be included in `responseDict` for test message. It looks happened every time for test message.

### PR DESCRIPTION
**Pull request by fumito-ito**
refs: #9126 

`FIRIAMFetchResponseParser` is better not to ignore appData for test message. This PR fixes #9126 problems particaly but not completely.

### CODE REVIEW

**Comment by paulb777** [comment]
Thanks for the PR @fumito-ito! Many people are currently out, so it may be a few weeks before we can do a review.

**Comment by eldhosembabu** [comment]
hi @fumito-ito ,

Thanks for doing this fix and it looks good. But did you get any chance to check whether with this fix you were able to receive the data bundle for a test campaign. When I checked I was not able to receive the databundle and it seems like the back end is not sending it. Could you please confirm?

**Review by eldhosembabu — APPROVED** [review]
Please wait till we test this changes before merging.

**Comment by paulb777** [comment]
@eldhosembabu You can merge it when ready.

**Comment by fumito-ito** [comment]
hi @eldhosembabu,

Thanks for your review.

> Thanks for doing this fix and it looks good. But did you get any chance to check whether with this fix you were able to receive the data bundle for a test campaign. When I checked I was not able to receive the databundle and it seems like the back end is not sending it. Could you please confirm?

#9126 is caused by both sdk and backend. This PR fixes only sdk problem. Could you report this problem to backend team ? Or to report this problem, could you let me know a backend team's public contact point If you have ?

**Comment by eldhosembabu** [comment]
I've already brought it to the backend team attention. Merging this PR as it looks good for the SDK side.

**Pull request merged**
