### PR TITLE
Update release setup to released tags.

### PR DESCRIPTION
**Pull request by granluo**

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]
LGTM on green

**Comment by granluo** [comment]
The failed [release test](https://github.com/firebase/firebase-ios-sdk/runs/4861287674?check_suite_focus=true) was caused by the `Cocoapods-8.11.0` tag pointing to the [commit ](https://github.com/firebase/firebase-ios-sdk/commit/5344857522053b5d4403ec8173ec0d23200a97ea) before the [update](https://github.com/firebase/firebase-ios-sdk/pull/9215).
The job is running to the latest Cocoapods tag. Will merge and updating  `Cocoapods-8.11.0` tag or adding a new Cocoapods version tag should help fix the failed job.

**Comment by paulb777** [comment]
Understood. I'm fine to merge as is.   

I'll push initial 8.12.0 tags tomorrow.

**Comment by paulb777** [comment]
On second thought, shouldn't the `CocoaPods-8.11.0` tag build correctly since both the FirebaseSegmentation podspec and source are still available at that tag?

**Comment by granluo** [comment]
> On second thought, shouldn't the `CocoaPods-8.11.0` tag build correctly since both the FirebaseSegmentation podspec and source are still available at that tag?

The FirebaseSegmentation was not run before until this [change](https://github.com/firebase/firebase-ios-sdk/pull/9215/files#diff-884bb2e52646d4b226c75e5dd7c196f9d654accb529fef4b6eeb401daa83144eL96) was merged.

**Comment by paulb777** [comment]
Now I understand. the segmentations removal also changed the `.yml` file. Thanks!

**Review by paulb777 — APPROVED** [review]

**Pull request merged**
