### PR TITLE
Revert "[Release Tooling] Stop including 'Info.plist's in static xcframeworks (#12243)"

### LINKED ISSUE #12390: Xcode 15.3b3: app installation failed due to missing Info.plist
### Description

Installing an app on a simulator or a device using the latest Xcode beta fails due a missing `Info.plist` with Firebase version `10.21.0`. The problem is solved when downgrading to `10.19.0`. I assume it's related to the removal of this file mentioned in the release notes here: https://firebase.google.com/support/release-notes/ios#version_10200_-_january_16_2023

The framework is included through SPM. I've tried clearing project and SPM caches, and resetting the simulator, but the issue persists.

### Reproducing the issue

_No response_

### Firebase SDK Version

10.21.0

### Xcode Version

15.3b3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Please try again later. Failed to load Info.plist from bundle at path /Users/<snip>/Library/Developer/CoreSimulator/Devices/FE2E39CC-56A1-41B2-AB52-8C7E3F4B0483/data/Library/Caches/com.apple.mobile.installd.staging/temp.WoIC6R/extracted/Payload/<snip>.app/Frameworks/GoogleAppMeasurement.framework; Extra info about "/Users/<snip>/Library/Developer/CoreSimulator/Devices/FE2E39CC-56A1-41B2-AB52-8C7E3F4B0483/data/Library/Caches/com.apple.mobile.installd.staging/temp.WoIC6R/extracted/Payload/<snip>.app/Frameworks/GoogleAppMeasurement.framework/Info.plist": Couldn't stat /Users/<snip>/Library/Developer/CoreSimulator/Devices/FE2E39CC-56A1-41B2-AB52-8C7E3F4B0483/data/Library/Caches/com.apple.mobile.installd.staging/temp.WoIC6R/extracted/Payload/<snip>.app/Frameworks/GoogleAppMeasurement.framework/Info.plist: No such file or directory
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by ncooke3**
This reverts commit 0fa8498f4b97e2ac1e550100e1996e13888d03fc.

Fix #12390

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]
Please confirm the presence of the plist in the generated zip.

**Comment by paulb777** [comment]
And add a release note.

**Comment by ncooke3** [comment]
Release note added and verified that platform framework plists are back.

**Comment by ncooke3** [comment]
Still working on the second piece, which involves changing how resources are bundled. Will open another PR for that.

**Review by paulb777 — APPROVED** [review]

**Comment by TakasurAtWork** [comment]
Is it released yet? I am facing an issue with Xcode 15.3 stable.

**Comment by ncooke3** [comment]
@TakasurAtWork, yes. Please update to the latest Firebase version, 10.22.0. If you run into any issues, please open an issue and I'll help triage.

**Pull request merged**
