### PR TITLE
Warn user if we raise with empty while not online

### PR DESCRIPTION
**Pull request by zxu123**
To avoid surprise by adding a warning. Right now, when offline, empty result is returned with no log nor error, see https://groups.google.com/forum/#!topic/google-cloud-firestore-discuss/puFl9HVU57I/discussion

### CODE REVIEW

**Comment by zxu123** [comment]
re-do on another code path.

**Comment by zxu123** [comment]
ready for review. PTAL.

**Comment by wilhuff** [comment]
Please resolve comments in the other other reviews, e.g. https://github.com/firebase/firebase-js-sdk/pull/352/files

**Comment by zxu123** [comment]
Updated with the same logic when to fire warning. PTAL.

**Pull request merged**
