### PR TITLE
Updating Advanced test app with live activity support

### PR DESCRIPTION
**Pull request by eldhosembabu**
Updating Advanced test app with live activity support

#no-changelog

### CODE REVIEW

**Comment by paulb777** [comment]
Please fix the CI

**Review by paulb777 — COMMENTED** [review]
We should have a changelog update to announce Live Activities support.

**Comment by eldhosembabu** [comment]
> We should have a changelog update to announce Live Activities support.

We don't have any changes in our FCM SDK with respect to live activity support addition..so not sure whether we will be needing a changelog.

**Comment by eldhosembabu** [comment]
> Please fix the CI

done

**Pull request merged**
