### PR TITLE
Fix secure coding bugs in MFA

### LINKED ISSUE #10632: `FIRMultiFactor` does not support `NSSecureCoding` correctly
### Description

The `FIRMultiFactor` conforms to `NSSecureCoding` but does not support it correctly. 

According to Apple:

> An object that does override `init(coder:)` must decode any enclosed objects using the `decodeObjectOfClass:forKey:` method.

[(NSSecureCoding documentation)](https://developer.apple.com/documentation/foundation/nssecurecoding)

In addition, the `user` property is a weak reference to parent object and should be set outside encode/decode.

### Reproducing the issue

_No response_

### Firebase SDK Version

10.3.0

### Xcode Version

14.1

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

_No response_

### If using Swift Package Manager, the project's Package.resolved

_No response_

### If using CocoaPods, the project's Podfile.lock

_No response_

### PR DESCRIPTION
**Pull request by igor-makarov**
Fixes #10632

### CODE REVIEW

**Comment by paulb777** [comment]
Thanks @igor-makarov !

Here's a diff to fix the style CI problem:
```
diff --git a/FirebaseAuth/Sources/MultiFactor/FIRMultiFactor.m b/FirebaseAuth/Sources/MultiFactor/FIRMultiFactor.m
index 3ef2ad469..8cd66b9bc 100644
--- a/FirebaseAuth/Sources/MultiFactor/FIRMultiFactor.m
+++ b/FirebaseAuth/Sources/MultiFactor/FIRMultiFactor.m
@@ -178,8 +178,9 @@ static NSString *kUserCodingKey = @"user";
 - (nullable instancetype)initWithCoder:(NSCoder *)aDecoder {
   self = [self init];
   if (self) {
-    NSSet *enrolledFactorsClasses =
-        [NSSet setWithArray:@[ [NSArray class], [FIRMultiFactorInfo class], [FIRPhoneMultiFactorInfo class] ]];
+    NSSet *enrolledFactorsClasses = [NSSet setWithArray:@[
+      [NSArray class], [FIRMultiFactorInfo class], [FIRPhoneMultiFactorInfo class]
+    ]];
```

**Comment by renkelvin** [comment]
Thanks @igor-makarov! Please apply the fix as @paulb777 suggests and I'll approve this PR.

**Comment by igor-makarov** [comment]
@paulb777 @renkelvin I've applied the style fixes

**Review by renkelvin — APPROVED** [review]
Thanks!

**Pull request merged**
