### PR TITLE
[DNM] Building the zip for a single product

### PR DESCRIPTION
**Pull request by ncooke3**
I've identified the unlinked Firestore using a script and am tried to programmatically force link them via [approach 1](87622ffb0cc1c8a358fff10a724b3856f96bee94). That approach did not work so I'm trying to force link them via a .m rather than a .mm file. 

I'm trying to iterate as fast as possible so I've removed all pods from the FirebaseManifest except Firestore, this yielded the following [zip build error](https://github.com/firebase/firebase-ios-sdk/actions/runs/4319398343/jobs/7538557080#step:7:2511) (I saw this locally as well.)

@paulb777 , any advice on speeding up zip build for iterating on a single product's zip distro?

### CODE REVIEW

**Comment by paulb777** [comment]
The zip-builder is designed to build any CocoaPod, in addition to building Firebase releases. See the zip-builder instructions at https://github.com/firebase/firebase-ios-sdk/tree/master/ReleaseTooling to use it just to build Firestore. See the analytics instructions for a specific example.

Also you can use the platforms and archs flags to build for just a single slice, since you only need the simulator to test.

**Comment by ncooke3** [comment]
@paulb777: Sorry, where is the archs flags? I've been using  `--platforms ios`
```
‣ swift run --package-path ReleaseTooling zip-builder --help
USAGE: zip-builder-tool <options>

OPTIONS:
  --enable-apple-silicon-support/--disable-apple-silicon-support
                          Enables or disables building arm64 slices for Apple silicon Macs. (default: true)
  --enable-build-dependencies/--disable-build-dependencies
                          Whether or not to build dependencies of requested pods. (default: true)
  --enable-carthage-version-check/--disable-carthage-version-check
                          A flag for enabling or disabling versions checks for Carthage builds. (default: true)
  --dynamic/--no-dynamic  A flag specifying to build dynamic library frameworks. (default: false)
  --keep-build-artifacts/--no-keep-build-artifacts
                          A flag to indicate keeping (not deleting) the build artifacts. (default: false)
  --include-catalyst/--no-include-catalyst
                          A flag to indicate skip building the Catalyst slice. (default: true)
  --update-pod-repo/--no-update-pod-repo
                          A flag to run `pod repo update` and `pod cache clean -all` before building the "zip file". (default: true)
  --custom-spec-repos <custom-spec-repos>
                          A list of private CocoaPod Spec repos. If not provided, the tool will only use the CocoaPods master repo. 
  --minimum-ios-version <minimum-ios-version>
                          The minimum supported iOS version. (default: 11.0)
  --minimum-mac-os-version <minimum-mac-os-version>
                          The minimum supported macOS version. (default: 10.13)
  --minimum-tvos-version <minimum-tvos-version>
                          The minimum supported tvOS version. (default: 12.0)
  --platforms <platforms> The list of platforms to build for. The default list is ["ios", "macos", "tvos"]. 
  --pods <pods>           List of pods to build. 
  --zip-pods <zip-pods>   The path to a JSON file of the pods (with optional version) to package into a zip. 
  --local-podspec-path <local-podspec-path>
                          Path to override podspec search with local podspec. 
  --build-root <build-root>
                          The root directory for build artifacts. If `nil`, a temporary directory will be used. 
  --output-dir <output-dir>
                          The directory to copy the built Zip file to. If this is not set, the path to the Zip file will be logged to the console. 
  -h, --help              Show help information.
```

**Comment by ncooke3** [comment]
Nevermind, found it mentioned in `ZipBuilderV2Plan.md`. I don't think it is an available option yet.

**Comment by ncooke3** [comment]
For future reference:

```
swift run zip-builder --package-path ReleaseTooling \                                                                                         (34ms) 
  --keep-build-artifacts \
  --local-podspec-path $(pwd) \
  --output-dir zip_output_dir \
  --disable-carthage-version-check \
  --platforms ios \
  --pods FirebaseFirestore \
  --no-update-pod-rep \
  --includeCatalyst false \
  -- appleSiliconSupport false \
  --buildDependencies false
```

**Pull request closed without merging**
