### PR TITLE
Restore 10.23.0 versions to main after 10.22.1

### LINKED ISSUE #12494: Nightly Testing Report
# Nightly Testing Report
This issue([log](https://github.com/firebase/firebase-ios-sdk/actions/runs/8202943031)) is generated at 03/08/2024 04:02 AM, fetching workflow runs triggered in the last 24 hrs.
| Workflow |03/07|
| -------- | -------- |
| [sessions](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/sessions.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/8197306855) |

### PR DESCRIPTION
**Pull request by paulb777**
Fix #12494

### CODE REVIEW

**Review by ncooke3 — APPROVED** [review]
LGTM, and will need to re-stage the GoogleAppMeasurementOnDeviceConversion.podspec. Was this the culprit of the nightly failure or was it that SpecsStaging had 10.22.1 pods?

**Review by andrewheard — APPROVED** [review]

**Comment by ncooke3** [comment]
> LGTM, and will need to re-stage the GoogleAppMeasurementOnDeviceConversion.podspec. Was this the culprit of the nightly failure or was it that SpecsStaging had 10.22.1 pods?

Ah, it looks like the the 10.22.1 pods confused the builder: https://github.com/firebase/firebase-ios-sdk/actions/runs/8198520159/job/22422203430#step:7:109

**Comment by paulb777** [comment]
But still failed after removing from SpecsStaging https://github.com/firebase/firebase-ios-sdk/actions/runs/8198520159 leading to this PR ...

**Comment by paulb777** [comment]
Restaging now

**Comment by ncooke3** [comment]
> Restaging now

@paulb777, fyi, the pod was staged without `--use-json` which is ok, but there are now two copies: one json, one ruby: https://github.com/firebase/SpecsStaging/tree/main/GoogleAppMeasurementOnDeviceConversion/10.23.0

**Comment by paulb777** [comment]
Repushed a new json one and removed the non-json one.

Good catch! thanks

**Pull request merged**
