### PR TITLE
create firebase messaging folder

### PR DESCRIPTION
**Pull request by chliangGoogle**
To follow the current folder style in Firebase.

### CODE REVIEW

**Comment by paulb777** [comment]
Other option would be update scripts/check_no_module_imports.sh to exclude FirebaseMessaging/Tests

**Comment by chliangGoogle** [comment]
Does it have to use module? I just update the import syntax.

**Comment by paulb777** [comment]
Yep that's fine to change the syntax.  The CI check is really meant for the libraries though which aren't allowed to have module imports. In theory, `@import` is fine in tests.

**Comment by chliangGoogle** [comment]
- Remove FirebaseMessaging/Tests/App

Didn't know this is no longer in use

- Can be in a later PR - move Example/Messaging/Sample to FirebaseMessaging/Tests/
Yeah I plan to move this after Ryan's session this friday

**Comment by chliangGoogle** [comment]
yeah, that's what I will work on next. We also need to adjust internal test app path, etc.

**Pull request merged**
