### PR TITLE
FirebaseInstallations import added to Firebase.h

### PR DESCRIPTION
**Pull request by maksymmalyhin**
#no-changelog

### CODE REVIEW

**Comment by ryanwilson** [comment]
This doesn't have to wait for the Firebase 7 milestone - can be merged whenever, but it may be a reasonable time to add it for convenience.

**Comment by ryanwilson** [comment]
If this is going to be added to the umbrella header we should also include it to the Firebase umbrella pod and the Swift Package Manifest as a product.

**Review by paulb777 — APPROVED** [review]
LGTM

The Firebase.podspec and Package.swift can be done here or in a separate PR.

**Comment by maksymmalyhin** [comment]
Looks like SwiftPM product has been added already (see [here](https://cs.opensource.google/firebase-sdk/firebase-ios-sdk/+/master:Package.swift)).

**Review by paulb777 — APPROVED** [review]

**Pull request merged**
