### PR TITLE
Fix Auth Domain search code to match comment

### LINKED ISSUE #7992: Incorrect comment in code.
The comment on the referred line specifies that the order of `supportedAuthDomains` matters. But the outer loop is the authorized domains from the web request, so actually the first match in the authorized domains list 'wins'.
The inner and outer loops should be switched for the comment to be correct.

https://github.com/firebase/firebase-ios-sdk/blob/31307cdf7e2e7f0cf931ccf30f54fb409cad037d/FirebaseAuth/Sources/Utilities/FIRAuthWebUtils.m#L107

### PR DESCRIPTION
**Pull request by paulb777**
Fix #7992

### CODE REVIEW

**Review by ncooke3 — APPROVED** [review]
LGTM! optional: Should a unit test be added to assert this behavior? And a changelog entry?

**Comment by paulb777** [comment]
@ncooke3 Thanks for keeping me honest. I've updated the unit tests so it fails with the old code and passes with the new - and added a CHANGELOG update.

**Review by ncooke3 — APPROVED** [review]
LGTM! CI failure looks GoogleUtilities related and can be ignored

**Comment by paulb777** [comment]
Merging here. I'll address any additional comments in a later PR.

**Pull request merged**
