### PR TITLE
Added methods for removing Crashlytics user info (#9212)

### PR DESCRIPTION
**Pull request by a-25**

### CODE REVIEW

**Comment by elenadoty** [comment]
Hi @a-25,
Thanks for the pr. Have you tried passing null as a value for a key you'd like to clear?

**Comment by a-25** [comment]
Hi. @elenadoty. You mean that it is unnecessary to introduce new methods but better to add nullability to existing ones?

**Comment by elenadoty** [comment]
Hi @a-25 ,
It turns out there was a long-standing bug in the SDK preventing this from working as intended. I've put up a PR that should fix the problem.

**Comment by a-25** [comment]
Hi, @elenadoty. Got it.
Is there anything I could do in this PR?

**Comment by elenadoty** [comment]
Hi @a-25 ,
There shouldn't be any need for more changes, but let me know if the solution doesn't work for you.

**Comment by paulb777** [comment]
Thanks @a-25 for getting the fix started and thanks @elenadoty for landing it!

**Pull request closed without merging**
