### PR TITLE
[Infra] Update release testing workflows

### LINKED ISSUE #13194: Nightly Testing Report
# Nightly Testing Report
This issue([log](https://github.com/firebase/firebase-ios-sdk/actions/runs/9696165851)) is generated at 06/27/2024 05:03 AM, fetching workflow runs triggered in the last 24 hrs.
| Workflow |06/26|
| -------- | -------- |
| [abtesting](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/abtesting.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/9693720753) |
| [core_internal](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/core_internal.yml) | [in_process](https://github.com/firebase/firebase-ios-sdk/actions/runs/9694589801) |
| [crashlytics](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/crashlytics.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/9689633493) |
| [database](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/database.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/9694589433) |
| [dynamiclinks](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/dynamiclinks.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/9693720714) |
| [installations](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/installations.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/9691503557) |
| [messaging](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/messaging.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/9691472736) |
| [performance](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/performance.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/9692150388) |
| [prerelease](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/prerelease.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/9690970712) |
| [release](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/release.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/9690936864) |
| [storage](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/storage.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/9692847704) |

### PR DESCRIPTION
**Pull request by ncooke3**
Added two encrypted tokens that provide scoped access for `FirebasePrivate/SpecsReleasing` and `Firebase/SpecsTesting`, respectively.

---

CI passing in manual invocations: 
- prerelease.yml – https://github.com/firebase/firebase-ios-sdk/actions/runs/9747736140
- release.yml – https://github.com/firebase/firebase-ios-sdk/actions/runs/9749764585 

Before merging
- [x] Audit unused tokens

Next steps once this PR is merged:
- [ ] Audit internal usage of removed secret
- [ ] Open source the SpecsReleasing testing repo so token isn't needed in Podfile source URL
- [ ] Audit unused tokens
- [ ] Consolidate jobs yml files via matrix
- [ ] Audit secret usage

Fix #13194

#no-changelog

### CODE REVIEW

**Comment by ncooke3** [comment]
Checkpoint as of 9b21d8d

Green prerelease.yml CI:  https://github.com/firebase/firebase-ios-sdk/actions/runs/9747736140

**Comment by ncooke3** [comment]
release.yml is working as well: https://github.com/firebase/firebase-ios-sdk/actions/runs/9749764585 as of [6df3b58](https://github.com/firebase/firebase-ios-sdk/pull/13203/commits/6df3b58b7d92dd3d4612976c696716669b12b6b3)

**Comment by ncooke3** [comment]
The `bot-access.txt.gpg` is no longer used in favor of the new fine-access access tokens, so I'm removing it.

**Review by paulb777 — APPROVED** [review]
Thanks!

**Pull request merged**
