### PR TITLE
Remove Xcode 12.0 explicit version requirement

### PR DESCRIPTION
**Pull request by ryanwilson**
- Remove Xcode 12.0 explicit version requirement.
- Update simulator selections for Xcode 12.2

Note that this comes with less stability, but gives us early visibility on new Xcode issues. If there's a transition that breaks, we will likely re-instate the explicit Xcode version locking. This paired with nightly testing though will let us catch things quickly.

#no-changelog

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]
LGTM on green

Please add to the description that we're explicitly trading off less stability for early visibility on new Xcode issues

**Comment by ryanwilson** [comment]
> LGTM on green
> 
> Please add to the description that we're explicitly trading off less stability for early visibility on new Xcode issues

Good call, done. Thanks!

**Comment by paulb777** [comment]
Looks like we need to adapt or remove failing travis tests. Either way, we should keep build.sh supporting Xcode 11 for at least awhile longer

**Comment by ryanwilson** [comment]
Closing for now until Xcode 11 isn't being run anymore.

**Pull request closed without merging**
