### PR TITLE
Cherry picks #5147 onto release-6.21.0

### PR DESCRIPTION
**Pull request by mikehaney24**
Cherry picks #5147

### CODE REVIEW

**Comment by paulb777** [comment]
Wrong target. Change it to release-6.21.0

**Comment by paulb777** [comment]
Please address the test failures. It looks like only 7 of 10 passed on #5147 also

**Comment by mikehaney24** [comment]
Looking into it, though test failure is likely a flake, all tests on #5147
passed on the last run.

https://github.com/firebase/firebase-ios-sdk/actions/runs/58508277

**Comment by paulb777** [comment]
I did see a flake once when I set up Catalyst for GDT - maybe the same one ...

**Comment by mikehaney24** [comment]
It is a flake, I'm able to occasionally reproduce locally. I'll try to get
to the bottom of it and fix it on master.

**Pull request merged**
