### PR TITLE
Clean up LRU tests

### PR DESCRIPTION
**Pull request by gsoltis**
I've added a bunch of helpers and some comments to the tests. Hopefully this is a little more clear. 

The final test is still large. My intention was to have something that exercised many of the cases together in addition to the smaller tests that exercise smaller scenarios. However, if you think it's an issue I can probably break it up into a 2-3 smaller tests.

There are still 2 tests that add multiple targets in a single transaction. One of them verifies that if we collect more than the number of targets added, we get those targets plus whatever is next. The other verifies that if we collect less than the number of targets added, we don't get anything additional. The large tests that exercise more typical usage do not include multiple targets in a single transaction.

### CODE REVIEW

**Comment by wilhuff** [comment]
Review status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @gsoltis and @wilhuff)

---

*[Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm, line 179 at r1](https://reviewable.io/reviews/firebase/firebase-ios-sdk/1433#-LFcs-0pAqukduEINMMv:-LFcs-0pAqukduEINMMw:bwpnvzd) ([raw file](https://github.com/firebase/firebase-ios-sdk/blob/6c803c89325caacbc6bf9a6a6f252c5c41695268/Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm#L179)):*
> ```
> toQueryInTransaction
> ```
This could probably just be `toTarget:`?

---

*[Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm, line 183 at r1](https://reviewable.io/reviews/firebase/firebase-ios-sdk/1433#-LFcsHhP-NehSZ5xXA7H:-LFcsHhP-NehSZ5xXA7I:b-i9xi5z) ([raw file](https://github.com/firebase/firebase-ios-sdk/blob/6c803c89325caacbc6bf9a6a6f252c5c41695268/Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm#L183)):*
> ```
> fromQueryInTransaction
> ```
Similarly could be just `fromQuery:`. All of these helpers are assumed to do the right thing w/r/t transactions.

---

*[Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm, line 187 at r1](https://reviewable.io/reviews/firebase/firebase-ios-sdk/1433#-LFcsmw7-Jx9r1si5jyV:-LFcsmw8CwnyWKjcQs_q:b-h2tqgo) ([raw file](https://github.com/firebase/firebase-ios-sdk/blob/6c803c89325caacbc6bf9a6a6f252c5c41695268/Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm#L187)):*
> ```XML
> }
> 
> - (FSTDocument *)cacheADocumentInTransaction {
> ```

A comment here on what this is doing would be helpful.

One question I had was when preloading a document this way, it seems like this is immediately an orphan. Is that a sane state? I suppose this really happens in normal operation as we're writing new documents from query results. It's only later that we add the query cache references. Just wanted to confirm.

---


*Comments from [Reviewable](https://reviewable.io/reviews/firebase/firebase-ios-sdk/1433)*

**Comment by wilhuff** [comment]
Basically LGTM. If you feel that naming should include "in transaction" I'm okay with that too.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 3 unresolved discussions (waiting on @gsoltis)

---



*Comments from [Reviewable](https://reviewable.io/reviews/firebase/firebase-ios-sdk/1433#-:-LFctwBo8ryA2XPxCpkL:b-czaxw)*

**Comment by gsoltis** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @wilhuff)

---

*[Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm, line 179 at r1](https://reviewable.io/reviews/firebase/firebase-ios-sdk/1433#-LFcs-0pAqukduEINMMv:-LFd74FYE0zd5bZon4i5:bbhrgtb) ([raw file](https://github.com/firebase/firebase-ios-sdk/blob/6c803c89325caacbc6bf9a6a6f252c5c41695268/Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm#L179)):*
<details><summary><i>Previously, wilhuff (Gil) wrote…</i></summary><blockquote>

> ```
> toQueryInTransaction
> ```
This could probably just be `toTarget:`?
</blockquote></details>

Yeah, I guess that works, since this method and the one below don't have a not-in-transaction variant.

---

*[Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm, line 183 at r1](https://reviewable.io/reviews/firebase/firebase-ios-sdk/1433#-LFcsHhP-NehSZ5xXA7H:-LFd7bJd4GHsQsDwgixJ:b-3qkkbr) ([raw file](https://github.com/firebase/firebase-ios-sdk/blob/6c803c89325caacbc6bf9a6a6f252c5c41695268/Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm#L183)):*
<details><summary><i>Previously, wilhuff (Gil) wrote…</i></summary><blockquote>

> ```
> fromQueryInTransaction
> ```
Similarly could be just `fromQuery:`. All of these helpers are assumed to do the right thing w/r/t transactions.
</blockquote></details>

Changed to `fromTarget:`. As above, it does not have a not-in-transaction variant. Some other helpers do though, so I'd prefer to keep the distinction in the method name.

---

*[Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm, line 187 at r1](https://reviewable.io/reviews/firebase/firebase-ios-sdk/1433#-LFcsmw7-Jx9r1si5jyV:-LFd8UGC5rGdJC5UWU3K:b-12v8gf) ([raw file](https://github.com/firebase/firebase-ios-sdk/blob/6c803c89325caacbc6bf9a6a6f252c5c41695268/Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm#L187)):*
<details><summary><i>Previously, wilhuff (Gil) wrote…</i></summary><blockquote>

A comment here on what this is doing would be helpful.

One question I had was when preloading a document this way, it seems like this is immediately an orphan. Is that a sane state? I suppose this really happens in normal operation as we're writing new documents from query results. It's only later that we add the query cache references. Just wanted to confirm.
</blockquote></details>

I added a comment to note that this must be paired with some other action to explain why the document is in the cache, but yes, you are essentially correct. It's not a sane state on its own, this is just a helper to get to certain scenarios. 

There are a number of ways a document could end up in the cache, this is a helper to get into the end state of a couple of different paths. For instance, adding a new document to a target or having a mutation pending against a document that was maybe previously part of a target but is no longer.

---


*Comments from [Reviewable](https://reviewable.io/reviews/firebase/firebase-ios-sdk/1433)*

**Comment by wilhuff** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/firebase/firebase-ios-sdk/1433#-:-LFdChu53qjTOtrUVJ7S:bnfp4nl)*

**Pull request merged**
