### PR TITLE
Delete app from Database when deleted in Core.

### PR DESCRIPTION
**Pull request by ryanwilson**
When a FIRApp is deleted in Core, it should also be deleted from
the instances array in Database.

See #160 for more details.

### CODE REVIEW

**Comment by ryanwilson** [comment]
@dylancopeland I'll look into it!

**Comment by ryanwilson** [comment]
@mikelehen - is calling `goOffline` on the instance enough to clear everything out, or what should I be doing in order to ensure everything's cleaned up well?

**Comment by mikelehen** [comment]
I think the best cleanup you can do is:

```
[FRepoManager disposeRepos:self.config];
```
But this mostly exists for testing purposes and isn't guaranteed to clean everything up (there will likely be memory leaks) and it doesn't really transition our objects into a permanent zombie state.  Some operations against existing FIRDatabaseReference instances may still work, or appear to work, and if you were to manually call goOnline it may bring the instance back to life.

So it's better than nothing, but if we care about delete working properly, we'll need to invest in more code to do proper cleanup / zombification of our objects.

**Comment by ryanwilson** [comment]
Added the cleanup call, thanks @mikelehen.

**Pull request merged**
