### PR TITLE
[Auth] Revert unintentional commits on main

### PR DESCRIPTION
**Pull request by ncooke3**
I unintentionally pushed to main (wasn't on a local branch). Usually, it stops me. I didn't force push but I saw `remote: Bypassed rule violations for refs/heads/main:`.

#no-changelog

### CODE REVIEW

**Review by andrewheard — APPROVED** [review]
I'll double check the branch rules to see if I can find anything unexpected.

**Comment by ncooke3** [comment]
I see that we have admin roles and admin roles are allowed to bypass branch protections.

**Comment by ncooke3** [comment]
Settings > Teams and Member roles > Admin

**Comment by ncooke3** [comment]
Ah, we could make turn off the ability to bypass branch protections:

branches > main > edit > scroll down and see:

Screenshot 2024-11-13 at 12 01 57 PM

**Comment by ncooke3** [comment]
We could always uncheck it if needed so I'm thinking it's worth checking this to avoid accidental pushes to main?

**Comment by ncooke3** [comment]
SG, I enabled it and did a quick test:
```console
nickcooke@nickcooke-mac firebase-ios-sdk % git commit -m "[NFC] Test branch protection"
[main 35bbafb41] [NFC] Test branch protection
 1 file changed, 1 insertion(+)
nickcooke@nickcooke-mac firebase-ios-sdk % git push origin HEAD
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 536 bytes | 536.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: 
remote: - Changes must be made through a pull request.
remote: 
remote: - 2 of 2 required status checks are expected.
To github.com:firebase/firebase-ios-sdk.git
 ! [remote rejected]     HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'github.com:firebase/firebase-ios-sdk.git'
```

**Pull request merged**
