### PR TITLE
Configure Messaging for default FIRApp only.

### PR DESCRIPTION
**Pull request by ryanwilson**
Currently Messaging will use the most recent FIRApp configured which
isn't obvious. This will limit it to only the default FIRApp.

### CODE REVIEW

**Comment by nmDejamobile** [comment]
Hi,
If only the default FireApp (or the latest as it was before this PR) can receive notifications, how can we configure multiple sender ids in an iOS app ?
Can we add multiple sender ids on the same default "__FIRAPP_DEFAULT" FireApp ? How ?
Thanks.
Note: I ended here after trying to solve https://stackoverflow.com/questions/45801656/in-ios-swift-app-registration-of-a-second-firebase-app-cant-receive-remote-n

**Comment by ryanwilson** [comment]
@rsattar - Riz, is this supposed to be a supported action for Messaging?

**Comment by nmDejamobile** [comment]
@ryanwilson I don't know if this is supposed to be supported on iOS but it work with Android so I assume that both iOS and Android SDK provides the same possibilities.

**Comment by rsattar** [comment]
Hey folks — yeah unfortunately because of how there is a single APNs device token per app, and also how the Messaging code base is set up (singleton-based), there is only one `FIRMessaging` instance for an app.

However, this is designed to still allow you create FCM tokens for different sender IDs. The idea is that you still create FIRMessaging for your default/primary app. The default FCM token reflects that default Firebase app's sender id.

You can create additional FCM tokens for _different_ sender IDs by calling [this method](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Messaging/Public/FIRMessaging.h#L385-L387):

```ObjectiveC
[[FIRMessaging messaging] retrieveFCMTokenForSenderID:otherSenderID completion:^(NSString *FCMToken, NSError *error) {

}];
```

```Swift
Messaging.messaging.retrieveFCMToken(forSenderID: otherSenderID) { (fcmToken, error) in

}
```

Hope that helps!

**Comment by nmDejamobile** [comment]
Hi, thanks for your answer.
I tried your way to retrieve a second token for the second sender, but I can't receive any notifications with this token. However, the first default app token well works. Both senders are different Firebase projects using the same Google account. Do I need to configure something special on the Google Firebase console ?

**Comment by rsattar** [comment]
@nmDejamobile Hmm the way you are using it is the intended approach, so this is unusual. 

A couple of questions:
1. Are you using the appropriate API key (different for each Firebase project) for the requests?
2. Do the tokens have the same prefix? e.g. `[same-prefix-string]:[different-alpha-numeric-string]`

**Comment by nmDejamobile** [comment]
@rsattar 
Yes for both questions:
- I use Insomnia to send my request and have both API keys configured for each project separately.
- both keys begins with the same thing (I deleted center content here) : eMNAm71AWWY:APA91bFO-tpIJY1Hl[...]h8It and eMNAm71AWWY:APA91bHqey5fxYShq[...]dD3a

**Comment by rsattar** [comment]
@nmDejamobile as a sanity check (it probably still is a bug in the SDK), could you try doing a [getinfo request on both of those tokens, using the IID API](https://developers.google.com/instance-id/reference/server#get_information_about_app_instances)?

That will tell us what "authorizedEntity" (i.e. the Sender ID) is used for each of the tokens. Note that you have to supply the correct server key in the `Authorization` header for each. Here's an example cURL command:

```
curl "https://iid.googleapis.com/iid/info/YOUR_FCM_TOKEN?details=true" \
     -H "Authorization: key=YOUR_SERVER_KEY"
```

**Comment by nmDejamobile** [comment]
@rsattar it tested this request and here are the json results.
For the default app token : 
{
	"applicationVersion": "0.1.1",
	"application": "com.mycompany.SampleApp",
	"scope": "*",
	"authorizedEntity": "632154525911",
	"platform": "IOS"
}

for the second app token : 
{
	"applicationVersion": "0.1.1",
	"application": "com.mycompany.SampleApp",
	"scope": "*",
	"authorizedEntity": "752355958747",
	"platform": "IOS"
}

**Pull request merged**
