### PR TITLE
Log incoming notifications to console as JSON

### PR DESCRIPTION
**Pull request by rsattar**
This is a change to the sample app, to help debug incoming notifications.

### CODE REVIEW

**Comment by paulb777** [comment]
travis failure - 

❌  /Users/travis/build/firebase/firebase-ios-sdk/Example/Messaging/App/iOS/AppDelegate.swift:140:42: type 'JSONSerialization.WritingOptions' has no member 'sortedKeys'

**Comment by rsattar** [comment]
Ah, I was doing the check locally for the sortedKeys (iOS 11 SDK), but I guess Travis isn't using it yet. Will compiler-check the `.sortedKeys` flag.

**Comment by rsattar** [comment]
Ended up just removing the `.sortedKeys` enum value for now, since `#available` is a run-time check, and there doesn't seem to be an easy way to check for the Foundation version at compile time.

**Comment by rsattar** [comment]
Absolutely. Carelessly thought `if #available` in Swift would be a compile time check, but it's not 😄

**Pull request merged**
