### PR TITLE
Database: fix App Check token refresh

### LINKED ISSUE #8544: Crash in App Check token fetch with force refresh
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.5.0 (but I scanned commits through 8.6.0, doesn't look addressed)
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: App Check 

#### Steps to reproduce:

Send `YES` for "forceRefresh" argument in this method

(DLog is just a wrapper for standard logging, use what you need)

#### Relevant Code:

```objective-c
- getToken
                  : (FIRApp *)firebaseApp
                  : (BOOL)forceRefresh) {
  FIRAppCheck *appCheck = [FIRAppCheck appCheckWithApp:firebaseApp];
  [appCheck tokenForcingRefresh:NO
                     completion:^(FIRAppCheckToken *_Nullable token, NSError *_Nullable error) {
                       if (error != nil) {
                         // Handle any errors if the token was not retrieved.
                         DLog(@"Unable to retrieve App Check token: %@", error);
                         return;
                       }
                       if (token == nil) {
                         DLog(@"Unable to retrieve App Check token.");
                         return;
                       }
                     DLog(@"fetched token successfully");
                     }];
}
```

```
App crashed: Exception was thrown: 
NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
(
        0   CoreFoundation                      0x00007fff20422faa __exceptionPreprocess + 226
        1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff204a1523 _CFThrowFormattedException + 194
        3   CoreFoundation                      0x00007fff204ac91d -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
        4   CoreFoundation                      0x00007fff2048f4c6 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 251
        5   CoreFoundation                      0x00007fff20421c42 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 49
        6   testing                             0x000000010ff2525a -[FPersistentConnection sendAppCheckToken:] + 154
        7   testing                             0x000000010ff251a1 -[FPersistentConnection refreshApp<…>

```

No crash if you send `NO` in there

### PR DESCRIPTION
**Pull request by maksymmalyhin**
Fixes #8544

### CODE REVIEW

**Comment by maksymmalyhin** [comment]
@schmidt-sebastian Could you please help to figure out automated tests strategy for this code section to prevent such issues from happening in the future. I could not find test infra covering this class.

**Comment by nilsreichardt** [comment]
@maksymmalyhin FYI: You forgot a `#` in your PR description, so the linked issue (#8544) will **not** be closed after merging this PR.

**Comment by maksymmalyhin** [comment]
@schmidt-sebastian We may have to defer adding automated tests for it again to merge the fix earlier to unblock developers. WDYT?

**Review by schmidt-sebastian — APPROVED** [review]

**Comment by maksymmalyhin** [comment]
Quickstart tests failures are present in master and are not relevant to the change.

**Comment by mikehardy** [comment]
Fantastic! Thank you @maksymmalyhin - I have automated test infrastructure for this and can test integrate 8.7.0 as soon as it pops out.

**Comment by mikehardy** [comment]
Hmm @maksymmalyhin - testing 8.7.0 with app check token fetch and forceRefresh == true, I no longer see a crash, which is a big win, but it is still not fetching a fresh token. It's my understanding that if I fetch the token with forceRefresh == true I should *always* receive a new token?

Android SDK has the same issue - tracking it here https://github.com/firebase/firebase-android-sdk/issues/2954 - do you want me to log a separate issue for this? Or if my understanding of the API is incorrect please let me know! Thanks

**Comment by maksymmalyhin** [comment]
@mikehardy Thank you for testing it! 

Yes, if you can could you please create a new one with a description/sample for us to reproduce it.

**Comment by mikehardy** [comment]
@maksymmalyhin false alarm, sorry for the noise! I still had it hard-wired in our obj-c code to pass 'NO' so it would not crash, vs sending in the parameter from javascript-land. firebase-ios-sdk AppCheck full API exercise via react-native-firebase appears to be :100:  now with 8.7.0. Thanks

**Pull request merged**
