### PR TITLE
Support NSPredicate CONTAINS and IN with new filter queries

### PR DESCRIPTION
**Pull request by goose2460**
Firebase introduced `arrayContainsAny` and `queryWhereField:in` in 2019. This PR adds support to NSPredicate for these queries

### CODE REVIEW

**Comment by goose2460** [comment]
@googlebot I signed it!

**Comment by paulb777** [comment]
@goose2460 Thanks for the PR! Much of the team is off now, so it may be a few weeks before we're able to review.

**Review by dstiers11 — APPROVED** [review]
8

**Review by wilhuff — APPROVED** [review]
LGTM

**Comment by wilhuff** [comment]
Thanks for the PR!

Are you finding the NSPredicate-based query methods useful/preferable to the Firestore public query API?

**Comment by goose2460** [comment]
Yes, I find them preferable to the public query API due to my background and I also prefer to depend on Foundation instead of Firebase at this layer in my project

```
extension Challenge {
    static func predicateForChallenges(createdBy userUid: String) -> NSPredicate {
        return NSPredicate(format: "%K = %@", Challenge.CodingKeys.creatorUid.stringValue, userUid)
    }
    
    static func predicateForChallenges(with participant: String) -> NSPredicate {
        return NSPredicate(format: "%K CONTAINS %@", Challenge.CodingKeys.participantUids.stringValue, participant)
    }
}
```

**Pull request merged**
