### PR TITLE
Combine support for the Decodable QuerySnapshot publisher

### PR DESCRIPTION
**Pull request by ziadtamim**
Here is a proposal for a `Decodable` publisher for the upstream `QuerySnapshot`.  

Here is a code snippet using the publisher returned by `getDocument()`

```swift
    let noBooks = [Book]()
    db.collection("books").getDocuments()
       .decode(type: Book.self)
       .collect()
       .replaceError(with: noBooks)
       .assign(to: \.books, on: self)
       .store(in: &cancellables)
```

### CODE REVIEW

**Comment by ziadtamim** [comment]
@googlebot I signed it!

**Comment by peterfriese** [comment]
Thanks for your contribution, @ziadtamim !

We're in the process of adding Combine support to Firebase, and have already started work on this:

- The plan is to develop this feature on the [combine-main](https://github.com/firebase/firebase-ios-sdk/tree/combine-main) working branch.
- We've got a project set up to track work [here](https://github.com/firebase/firebase-ios-sdk/projects/3).
- PR #6976 will act as the model implementation - it adds some infrastructure, and is intended to set the style for how Combine support should look like. The [initial comment](https://github.com/firebase/firebase-ios-sdk/pull/6976#issue-522002691) on the PR discusses some decisions we made so far.
- There's also a suggestion for adding Combine support to Firestore in this PR: #6960, which is based on #6940
- Adding support for `Result` type will (by way of #6940) allow us to simplify much of the code.

That being said, I will take a closer look and review your PR once I get back to work next week.

**Comment by peterfriese** [comment]
@ziadtamim we'd like to delete `combine-master` in favour of `combine-main` for clarity (see #7238) - would you mind re-targeting this PR to `peterfriese-combine`?

**Comment by ziadtamim** [comment]
> @ziadtamim we'd like to delete `combine-master` in favour of `combine-main` for clarity (see #7238) - would you mind re-targeting this PR to `peterfriese-combine`?

@peterfriese Done.

**Comment by lorenzofiamingo** [comment]
Was considered to extend `Firestore.Decoder` to adopt the protocol [`TopLevelDecoder`](https://developer.apple.com/documentation/combine/topleveldecoder) (and [`TopLevelEncoder`](https://developer.apple.com/documentation/combine/toplevelencoder))? 

Combine already has a builtin [`decode`](https://developer.apple.com/documentation/combine/publishers/merge/decode(type:decoder:)) (and [`encode`](https://developer.apple.com/documentation/combine/publishers/merge/encode(encoder:))) method. 

I'm not 100% sure `TopLevelDecoder.Input` will work with both `DocumentSnapshot` and `QueryDocumentSnapshot`, though. Maybe will be necessary to make a dummy protocol.

**Comment by peterfriese** [comment]
Sorry this got closed - I was cleaning up and deleted my personal working branch.

Please rebase this work onto `combine-main`.

**Comment by peterfriese** [comment]
This is continued in #7549.

**Pull request closed without merging**
