### PR TITLE
Release artifacts for M66.1

### PR DESCRIPTION
**Pull request by ryanwilson**

### CODE REVIEW

**Comment by wilhuff** [comment]
Note that we released Firestore 1.11.2 on top of release-6.19. Should release 6.20 include that?

**Comment by paulb777** [comment]
Yep the Firebase.podspec should be updated to include 1.11.2

**Comment by wilhuff** [comment]
OK. I created https://github.com/firebase/firebase-ios-sdk/pull/5091 to merge that to master.

**Comment by ryanwilson** [comment]
Thanks for doing that - I can cherry-pick now!

**Pull request merged**
