### PR TITLE
Update swiftpm docs for Xcode 13

### PR DESCRIPTION
**Pull request by ncooke3**
Preview: https://github.com/firebase/firebase-ios-sdk/blob/befebff/SwiftPackageManager.md

#no-changelog

### CODE REVIEW

**Comment by ryanwilson** [comment]
One thing in reviewing that I realized we should add, can you please change from `Requires Xcode 12.5` to `Requires Xcode 12.5 or above`?

**Comment by ryanwilson** [comment]
Another thing, can you please add ABTesting to the watchOS product availability?

**Review by ryanwilson — APPROVED** [review]
Looks great, thanks! If you don't mind those two small tweaks as well that would be great.

**Comment by ncooke3** [comment]
Small improvements

**Review by ryanwilson — APPROVED** [review]
Thanks!

**Pull request merged**
