### PR TITLE
Surface `registerLibrary:withVersion:`

### PR DESCRIPTION
**Pull request by bstpierr**
This moves the method from the FIRAppInternal header to the public header.

### CODE REVIEW

**Comment by paulb777** [comment]
What's the reason for making it public?

**Comment by bstpierr** [comment]
This is to enable second-party SDKs like Firebase Unity to depend on a properly semver'ed API.

**Comment by paulb777** [comment]
Why don't they use the private API like the other Firebase SDKs?

registerLibrary doesn't seem like something we'd want to support publicly.

**Comment by bstpierr** [comment]
My understanding was that we would support it for libraries that wanted to report their versions. @davidair might be able to provide more context.

**Pull request closed without merging**
