### PR TITLE
Remove UIWebViewDelegate references

### PR DESCRIPTION
**Pull request by paulb777**
Follow up to #3722 and #3723 for UIWebViewDelegate in addition to UIWebView

### CODE REVIEW

**Comment by dloic** [comment]
I did search for each ref, but obviously missed this one. Sorry for this, will have a better look next time.

**Comment by yadits** [comment]
Thanks!! when can we expect a release? I'm using CocoaPods

**Comment by paulb777** [comment]
We'll see if we can release this sometime this week. In the meantime, the workaround would be deleting the UIWebKitDelegate references after the CocoaPods install.

**Comment by dmandar** [comment]
LGTM

**Comment by eleomilagrosa** [comment]
Hi I am still getting an error from the app store.
Can anyone confirm this fix works?

"ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information."

**Comment by paulb777** [comment]
@eleomilagrosa This fix is only for FirebaseDynamicLinks which does not seem to be in your app.  Use `grep` to search source libraries for UIWebView and `nm` to search binary libraries to isolate the problem library.

**Pull request merged**
